package hardware

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// PiConfigOptions drives generation of pi_client/config.yaml from DB wiring.
type PiConfigOptions struct {
	FarmID    int64
	DeviceID  int64
	DeviceUID string
	DeviceName string
	BaseURL   string
	APIKey    string // empty → placeholder in output
	Sensors   []PiConfigSensor
	Actuators []PiConfigActuator
}

// PiConfigSensor is a sensor row + optional wiring for generation.
type PiConfigSensor struct {
	ID                     int64
	SensorType             string
	ReadingIntervalSeconds *int32
	Config                 json.RawMessage
	CalibrationData        json.RawMessage
}

// PiConfigActuator is an actuator row + optional wiring for generation.
type PiConfigActuator struct {
	ID                 int64
	ActuatorType       string
	DeviceID           *int64
	HardwareIdentifier *string
	Config             json.RawMessage
}

type piConfigFile struct {
	API struct {
		BaseURL        string `yaml:"base_url"`
		TimeoutSeconds int    `yaml:"timeout_seconds"`
		APIKey         string `yaml:"api_key"`
	} `yaml:"api"`
	Farm struct {
		FarmID int64 `yaml:"farm_id"`
	} `yaml:"farm"`
	Sensors                     []piSensorEntry    `yaml:"sensors"`
	Actuators                   []piActuatorEntry  `yaml:"actuators"`
	SchedulePollIntervalSeconds int                `yaml:"schedule_poll_interval_seconds"`
	OfflineQueuePath            string             `yaml:"offline_queue_path"`
	OfflineFlushIntervalSeconds int                `yaml:"offline_flush_interval_seconds"`
}

type piSensorEntry struct {
	SensorID            int64                  `yaml:"sensor_id"`
	SensorType          string                 `yaml:"sensor_type"`
	Source              string                 `yaml:"source"`
	Pin                 *int                   `yaml:"pin,omitempty"`
	Channel             *int                   `yaml:"channel,omitempty"`
	Port                string                 `yaml:"port,omitempty"`
	Inputs              map[string]int         `yaml:"inputs,omitempty"`
	InputMaxAgeSeconds  *int                   `yaml:"input_max_age_seconds,omitempty"`
	IntervalSeconds     int                    `yaml:"interval_seconds"`
	Calibration         map[string]float64     `yaml:"calibration,omitempty"`
}

type piActuatorEntry struct {
	ActuatorID int64  `yaml:"actuator_id"`
	DeviceID   int64  `yaml:"device_id"`
	DeviceType string `yaml:"device_type"`
	Driver     string `yaml:"driver,omitempty"`
	GPIOPin    *int   `yaml:"gpio_pin,omitempty"`
	Channel    *int   `yaml:"channel,omitempty"`
}

var actuatorTypeToPiDevice = map[string]string{
	"grow_light": "light",
	"light":      "light",
	"pump":       "irrigation",
	"irrigation": "irrigation",
	"exhaust_fan": "fan",
	"fan":        "fan",
	"valve":      "irrigation",
	"relay":      "relay",
}

// GeneratePiConfigYAML renders a valid pi_client/config.yaml for one edge device.
func GeneratePiConfigYAML(opts PiConfigOptions) ([]byte, error) {
	if opts.FarmID <= 0 || opts.DeviceID <= 0 {
		return nil, fmt.Errorf("farm_id and device_id are required")
	}
	baseURL := strings.TrimSpace(opts.BaseURL)
	if baseURL == "" {
		baseURL = "http://<api-lan-ip>:8080"
	}
	apiKey := strings.TrimSpace(opts.APIKey)
	if apiKey == "" {
		apiKey = "<PI_API_KEY from server env>"
	}

	sensors, err := buildPiSensorEntries(opts.Sensors, opts.DeviceID)
	if err != nil {
		return nil, err
	}
	actuators, err := buildPiActuatorEntries(opts.Actuators, opts.DeviceID)
	if err != nil {
		return nil, err
	}

	cfg := piConfigFile{
		SchedulePollIntervalSeconds: 30,
		OfflineQueuePath:            "/var/lib/gr33n/queue.db",
		OfflineFlushIntervalSeconds: 60,
	}
	cfg.API.BaseURL = baseURL
	cfg.API.TimeoutSeconds = 5
	cfg.API.APIKey = apiKey
	cfg.Farm.FarmID = opts.FarmID
	cfg.Sensors = sensors
	cfg.Actuators = actuators

	var buf bytes.Buffer
	writePiConfigHeader(&buf, opts)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&cfg); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func writePiConfigHeader(buf *bytes.Buffer, opts PiConfigOptions) {
	name := strings.TrimSpace(opts.DeviceName)
	if name == "" {
		name = fmt.Sprintf("device %d", opts.DeviceID)
	}
	uid := strings.TrimSpace(opts.DeviceUID)
	fmt.Fprintf(buf, "# gr33n Pi Client - config.yaml\n")
	fmt.Fprintf(buf, "# Generated by gr33n platform for %s", name)
	if uid != "" {
		fmt.Fprintf(buf, " (%s)", uid)
	}
	fmt.Fprintf(buf, "\n# Edit api.base_url and api.api_key for your LAN, then copy to the Pi.\n\n")
}

func buildPiSensorEntries(rows []PiConfigSensor, deviceID int64) ([]piSensorEntry, error) {
	type item struct {
		entry    piSensorEntry
		derived  bool
		sortName string
	}
	var items []item
	for _, row := range rows {
		w, err := ExtractWiring(row.Config)
		if err != nil {
			return nil, fmt.Errorf("sensor %d: %w", row.ID, err)
		}
		if !belongsToDevice(w, nil, deviceID) {
			continue
		}
		entry, err := sensorToPiEntry(row, w)
		if err != nil {
			continue // skip sensors without complete wiring
		}
		items = append(items, item{
			entry:    entry,
			derived:  w.Source == "derived",
			sortName: row.SensorType,
		})
	}
	sort.SliceStable(items, func(i, j int) bool {
		if items[i].derived != items[j].derived {
			return !items[i].derived
		}
		return items[i].entry.SensorID < items[j].entry.SensorID
	})
	out := make([]piSensorEntry, len(items))
	for i, it := range items {
		out[i] = it.entry
	}
	return out, nil
}

func buildPiActuatorEntries(rows []PiConfigActuator, deviceID int64) ([]piActuatorEntry, error) {
	var out []piActuatorEntry
	for _, row := range rows {
		w, err := ExtractWiring(row.Config)
		if err != nil {
			return nil, fmt.Errorf("actuator %d: %w", row.ID, err)
		}
		if w != nil && w.GPIOPin != nil && belongsToDevice(w, row.DeviceID, deviceID) {
			pin := *w.GPIOPin
			out = append(out, piActuatorEntry{
				ActuatorID: row.ID,
				DeviceID:   deviceID,
				DeviceType: mapActuatorTypeToPi(row.ActuatorType),
				Driver:     "gpio",
				GPIOPin:    &pin,
			})
			continue
		}
		if row.DeviceID == nil || *row.DeviceID != deviceID {
			continue
		}
		if row.HardwareIdentifier == nil {
			continue
		}
		ch, ok := parseRelayHATChannel(*row.HardwareIdentifier)
		if !ok {
			continue
		}
		out = append(out, piActuatorEntry{
			ActuatorID: row.ID,
			DeviceID:   deviceID,
			DeviceType: mapActuatorTypeToPi(row.ActuatorType),
			Driver:     "relay_hat",
			Channel:    &ch,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ActuatorID < out[j].ActuatorID })
	return out, nil
}

func parseRelayHATChannel(raw string) (int, bool) {
	s := strings.TrimSpace(raw)
	if s == "" {
		return 0, false
	}
	var ch int
	if _, err := fmt.Sscanf(s, "%d", &ch); err == nil && ch >= 0 {
		return ch, true
	}
	// relay_3, ch-3 — trailing digits
	i := len(s)
	for i > 0 && s[i-1] >= '0' && s[i-1] <= '9' {
		i--
	}
	if i >= len(s) {
		return 0, false
	}
	if _, err := fmt.Sscanf(s[i:], "%d", &ch); err != nil || ch < 0 {
		return 0, false
	}
	return ch, true
}

func belongsToDevice(w *Wiring, rowDeviceID *int64, targetID int64) bool {
	if w != nil && w.DeviceID != nil && *w.DeviceID == targetID {
		return true
	}
	if rowDeviceID != nil && *rowDeviceID == targetID {
		if w == nil || w.DeviceID == nil {
			return true
		}
	}
	return false
}

func sensorToPiEntry(row PiConfigSensor, w *Wiring) (piSensorEntry, error) {
	if w == nil || w.Source == "" {
		return piSensorEntry{}, fmt.Errorf("wiring missing")
	}
	if err := ValidateSensorWiring(w); err != nil {
		return piSensorEntry{}, err
	}
	interval := 60
	if row.ReadingIntervalSeconds != nil && *row.ReadingIntervalSeconds > 0 {
		interval = int(*row.ReadingIntervalSeconds)
	}
	entry := piSensorEntry{
		SensorID:        row.ID,
		SensorType:      row.SensorType,
		Source:          w.Source,
		IntervalSeconds: interval,
	}
	switch w.Source {
	case "dht22", "gpio_digital":
		entry.Pin = w.GPIOPin
	case "ads1115":
		entry.Channel = w.I2CChannel
	case "mhz19":
		entry.Port = w.SerialPort
	case "derived":
		if len(w.Inputs) > 0 {
			var inputs map[string]int
			if err := json.Unmarshal(w.Inputs, &inputs); err == nil && len(inputs) > 0 {
				entry.Inputs = inputs
			}
		}
	case "bh1750":
		// I2C-only; no extra keys in pi yaml
	}
	if len(row.CalibrationData) > 0 {
		var cal map[string]float64
		if err := json.Unmarshal(row.CalibrationData, &cal); err == nil && len(cal) > 0 {
			entry.Calibration = cal
		}
	}
	return entry, nil
}

func mapActuatorTypeToPi(actuatorType string) string {
	k := strings.ToLower(strings.TrimSpace(actuatorType))
	if v, ok := actuatorTypeToPiDevice[k]; ok {
		return v
	}
	if k != "" {
		return k
	}
	return "relay"
}

// PiSensorEntryToWiring maps a parsed pi_client sensor stanza back to WS1 wiring.
func PiSensorEntryToWiring(entry piSensorEntry, deviceID int64) *Wiring {
	w := &Wiring{
		Source:   entry.Source,
		DeviceID: &deviceID,
	}
	if entry.Pin != nil {
		w.GPIOPin = entry.Pin
	}
	if entry.Channel != nil {
		w.I2CChannel = entry.Channel
	}
	if entry.Port != "" {
		w.SerialPort = entry.Port
	}
	if len(entry.Inputs) > 0 {
		b, _ := json.Marshal(entry.Inputs)
		w.Inputs = b
	}
	return w
}

// PiActuatorEntryToWiring maps a parsed pi_client actuator stanza back to WS1 wiring.
func PiActuatorEntryToWiring(entry piActuatorEntry) *Wiring {
	if entry.GPIOPin == nil {
		return nil
	}
	dev := entry.DeviceID
	return &Wiring{
		Source:   "gpio_relay",
		GPIOPin:  entry.GPIOPin,
		DeviceID: &dev,
	}
}

// ParsePiConfigYAML extracts sensor/actuator entries for round-trip tests.
func ParsePiConfigYAML(data []byte) (sensors []piSensorEntry, actuators []piActuatorEntry, err error) {
	var cfg piConfigFile
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, nil, err
	}
	return cfg.Sensors, cfg.Actuators, nil
}
