package procedures

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	"gopkg.in/yaml.v3"
)

var (
	loadOnce sync.Once
	loadErr  error
	byID     map[string]Procedure
)

// RepoRoot returns the repo root for procedure YAML (env GR33N_REPO_ROOT or walk up from cwd).
func RepoRoot() string {
	if v := strings.TrimSpace(os.Getenv("GR33N_REPO_ROOT")); v != "" {
		return v
	}
	if root := discoverRepoRoot(); root != "" {
		return root
	}
	return "."
}

func discoverRepoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		return ""
	}
	dir := wd
	for i := 0; i < 8; i++ {
		if _, err := os.Stat(filepath.Join(dir, "docs", "field-guides", "procedures")); err == nil {
			return dir
		}
		dir = filepath.Dir(dir)
	}
	return ""
}

// Dir returns docs/field-guides/procedures under repoRoot.
func Dir(repoRoot string) string {
	return filepath.Join(repoRoot, "docs", "field-guides", "procedures")
}

func ensureLoaded(repoRoot string) error {
	loadOnce.Do(func() {
		byID = make(map[string]Procedure)
		dir := Dir(repoRoot)
		entries, err := os.ReadDir(dir)
		if err != nil {
			loadErr = fmt.Errorf("read procedures dir %s: %w", dir, err)
			return
		}
		for _, ent := range entries {
			if ent.IsDir() || !strings.HasSuffix(ent.Name(), ".yaml") {
				continue
			}
			data, err := os.ReadFile(filepath.Join(dir, ent.Name()))
			if err != nil {
				loadErr = err
				return
			}
			var p Procedure
			if err := yaml.Unmarshal(data, &p); err != nil {
				loadErr = fmt.Errorf("%s: %w", ent.Name(), err)
				return
			}
			if strings.TrimSpace(p.ID) == "" {
				loadErr = fmt.Errorf("%s: missing id", ent.Name())
				return
			}
			for i := range p.Steps {
				if p.Steps[i].N == 0 {
					p.Steps[i].N = i + 1
				}
			}
			byID[p.ID] = p
		}
		if len(byID) == 0 {
			loadErr = fmt.Errorf("no procedures under %s", dir)
		}
	})
	return loadErr
}

// ResetForTest clears the loader cache (tests only).
func ResetForTest() {
	loadOnce = sync.Once{}
	loadErr = nil
	byID = nil
}

// Get returns one procedure by id.
func Get(repoRoot, id string) (Procedure, error) {
	if err := ensureLoaded(repoRoot); err != nil {
		return Procedure{}, err
	}
	p, ok := byID[strings.TrimSpace(id)]
	if !ok {
		return Procedure{}, fmt.Errorf("unknown procedure %q", id)
	}
	return p, nil
}

// List returns all procedures sorted by title.
func List(repoRoot string) ([]Procedure, error) {
	if err := ensureLoaded(repoRoot); err != nil {
		return nil, err
	}
	out := make([]Procedure, 0, len(byID))
	for _, p := range byID {
		out = append(out, p)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Title < out[j].Title })
	return out, nil
}

// PrintMarkdown renders a printable checklist (Phase 37 WS6).
func PrintMarkdown(p Procedure) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", p.Title)
	fmt.Fprintf(&b, "_Procedure `%s` · domain %s · offline_ok=%v_\n\n", p.ID, p.Domain, p.OfflineOK)
	for _, s := range p.Steps {
		tier := s.NormalizeStepTier()
		fmt.Fprintf(&b, "## Step %d/%d — %s\n\n", s.N, len(p.Steps), tier)
		b.WriteString(strings.TrimSpace(s.Say))
		b.WriteString("\n\n")
		if c := strings.TrimSpace(s.Confirm); c != "" {
			fmt.Fprintf(&b, "**Confirm:** %s\n\n", c)
		}
		if r := strings.TrimSpace(s.Ref); r != "" {
			fmt.Fprintf(&b, "_Ref: field-guides/%s_\n\n", r)
		}
		if tier == "qualified_person_required" || s.StopUnlessQualified {
			b.WriteString("> **STOP — qualified tradesperson required. Do not proceed without a licensed electrician or plumber.**\n\n")
		}
	}
	b.WriteString("---\n\n*Generated by gr33n field assistant. Low-voltage Pi control only — mains and pressurized plumbing need licensed trades.*\n")
	return b.String()
}
