#!/usr/bin/env bash
# Phase 31 WS1 — run pi_client with stub drivers; sensor ids resolved from DB by name.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB_URL="${DATABASE_URL:-postgres://gr33n:gr33n@127.0.0.1:5433/gr33n?sslmode=disable}"
API_URL="${GR33N_API_URL:-http://localhost:8080}"
FARM_ID="${GR33N_FARM_ID:-1}"
PI_KEY="${PI_API_KEY:-}"

if [[ -f "$ROOT/.env" ]]; then
  # shellcheck disable=SC1091
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^DATABASE_URL= ]] && DB_URL="${line#DATABASE_URL=}"
    [[ "$line" =~ ^PI_API_KEY= ]] && PI_KEY="${line#PI_API_KEY=}"
    [[ "$line" =~ ^PORT= ]] && port="${line#PORT=}" && API_URL="http://localhost:${port}"
  done < "$ROOT/.env"
fi

if [[ -z "$PI_KEY" ]]; then
  echo "PI_API_KEY not set — add to $ROOT/.env (required for AUTH_MODE=auth_test)" >&2
  exit 1
fi

lookup_id() {
  local name="$1"
  psql "$DB_URL" -v ON_ERROR_STOP=1 -t -A -c \
    "SELECT MIN(id) FROM gr33ncore.sensors WHERE farm_id = ${FARM_ID} AND deleted_at IS NULL AND name = '${name}'"
}

require_sensor() {
  local id="$1" name="$2"
  if [[ -z "$id" || "$id" == "NULL" ]]; then
    echo "Missing sensor '$name' for farm_id=${FARM_ID}. Run make dev-stack --seed or make seed." >&2
    exit 1
  fi
  echo "$id"
}

AIR_TEMP="$(require_sensor "$(lookup_id 'Air Temp Indoor')" 'Air Temp Indoor')"
AIR_HUM="$(require_sensor "$(lookup_id 'Air Humidity Indoor')" 'Air Humidity Indoor')"
PAR="$(require_sensor "$(lookup_id 'PAR Sensor Indoor')" 'PAR Sensor Indoor')"
EC="$(require_sensor "$(lookup_id 'EC Sensor')" 'EC Sensor')"
PH="$(require_sensor "$(lookup_id 'pH Sensor')" 'pH Sensor')"
CO2="$(require_sensor "$(lookup_id 'CO2 Sensor Indoor')" 'CO2 Sensor Indoor')"

CFG="$ROOT/pi_client/.edge-stub.generated.yaml"
QUEUE="$ROOT/pi_client/.gr33n-edge-queue.db"

cat > "$CFG" <<EOF
# Generated by scripts/run-edge-stub-client.sh — do not commit
api:
  base_url: "${API_URL}"
  timeout_seconds: 5
  api_key: "${PI_KEY}"
farm:
  farm_id: ${FARM_ID}
sensors:
  - sensor_id: ${AIR_TEMP}
    sensor_type: temperature
    source: dht22
    pin: 4
    interval_seconds: 5
  - sensor_id: ${AIR_HUM}
    sensor_type: humidity
    source: dht22
    pin: 4
    interval_seconds: 5
  - sensor_id: ${PAR}
    sensor_type: par
    source: bh1750
    interval_seconds: 10
  - sensor_id: ${EC}
    sensor_type: ec
    source: ads1115
    channel: 1
    interval_seconds: 10
  - sensor_id: ${PH}
    sensor_type: ph
    source: ads1115
    channel: 2
    interval_seconds: 10
  - sensor_id: ${CO2}
    sensor_type: co2
    source: mhz19
    port: "/dev/ttyS0"
    interval_seconds: 10
actuators: []
schedule_poll_interval_seconds: 30
offline_queue_path: "${QUEUE}"
offline_flush_interval_seconds: 30
EOF

echo "Resolved sensor ids: temp=${AIR_TEMP} humidity=${AIR_HUM} par=${PAR} ec=${EC} ph=${PH} co2=${CO2}"
echo "Config: $CFG"
echo "Starting pi_client (Ctrl+C to stop)..."

cd "$ROOT/pi_client"
if ! python3 -c "import requests, yaml" 2>/dev/null; then
  python3 -m pip install -q -r requirements.txt
fi
exec python3 gr33n_client.py --config "$CFG"
