#!/usr/bin/env bash
# Phase 125 — LED simulation rig: resolve sensor/actuator ids by name, run pi_client.
#
# Default driver=gpio — plain breadboard LEDs + resistors (starter kit).
# NeoPixel strip: GR33N_LED_DRIVER=neopixel ./scripts/run-led-simulation.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB_URL="${DATABASE_URL:-postgres://gr33n:gr33n@127.0.0.1:5433/gr33n?sslmode=disable}"
API_URL="${GR33N_API_URL:-http://localhost:8080}"
FARM_ID="${GR33N_FARM_ID:-1}"
PI_KEY="${PI_API_KEY:-}"
DEVICE_UID="${GR33N_DEVICE_UID:-demo-veg-relay-01}"
DRIVER="${GR33N_LED_DRIVER:-gpio}"

if [[ -f "$ROOT/.env" ]]; then
  # shellcheck disable=SC1091
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^DATABASE_URL= ]] && DB_URL="${line#DATABASE_URL=}"
    [[ "$line" =~ ^PI_API_KEY= ]] && PI_KEY="${line#PI_API_KEY=}"
    [[ "$line" =~ ^PORT= ]] && port="${line#PORT=}" && API_URL="http://localhost:${port}"
  done < "$ROOT/.env"
fi

if [[ -z "$PI_KEY" ]]; then
  echo "PI_API_KEY not set — add to $ROOT/.env (required for AUTH_MODE=auth_test)" >&2
  exit 1
fi

lookup_sensor() {
  psql "$DB_URL" -v ON_ERROR_STOP=1 -t -A -c \
    "SELECT MIN(id) FROM gr33ncore.sensors WHERE farm_id = ${FARM_ID} AND deleted_at IS NULL AND name = '$1'"
}

lookup_actuator() {
  psql "$DB_URL" -v ON_ERROR_STOP=1 -t -A -c \
    "SELECT MIN(id) FROM gr33ncore.actuators WHERE farm_id = ${FARM_ID} AND deleted_at IS NULL AND name = '$1'"
}

require_id() {
  local id="$1" label="$2"
  if [[ -z "$id" || "$id" == "NULL" ]]; then
    echo "Missing '$label' for farm_id=${FARM_ID}. Run make dev-stack --seed." >&2
    exit 1
  fi
  echo "$id"
}

MOISTURE="$(require_id "$(lookup_sensor 'Media Moisture Indoor')" 'Media Moisture Indoor')"
EC="$(require_id "$(lookup_sensor 'EC Sensor')" 'EC Sensor')"
AIR_TEMP="$(require_id "$(lookup_sensor 'Air Temp Indoor')" 'Air Temp Indoor')"
AIR_HUM="$(require_id "$(lookup_sensor 'Air Humidity Indoor')" 'Air Humidity Indoor')"
PH="$(require_id "$(lookup_sensor 'pH Sensor')" 'pH Sensor')"
GROW_LIGHT="$(require_id "$(lookup_actuator 'Veg Room Grow Light')" 'Veg Room Grow Light')"
IRR_PUMP="$(require_id "$(lookup_actuator 'Veg Room Irrigation Pump')" 'Veg Room Irrigation Pump')"

CFG="$ROOT/pi_client/.led-simulation.generated.yaml"
QUEUE="$ROOT/pi_client/.gr33n-edge-queue.db"

# Breadboard map: logical pixel → BCM GPIO (CanaKit card physical pin in comments).
# Each LED: GPIO --[220Ω]--> LED anode(+ long) ; LED cathode(- short) --> GND rail → Pi GND.
SIM_BACKEND=""
if [[ "$DRIVER" == "neopixel" ]]; then
  SIM_BACKEND=$(cat <<'YAML'
  driver: neopixel
  neopixel:
    pin: 18
    count: 8
    brightness: 0.4
    pixel_order: GRB
YAML
)
else
  SIM_BACKEND=$(cat <<'YAML'
  driver: gpio
  # pixel → BCM GPIO (plain LED + 220Ω). Same pixel roles as NeoPixel rig.
  discrete_leds:
    0: 18   # Media Moisture — phys pin 12
    1: 23   # EC             — phys pin 16
    2: 24   # Air Temp       — phys pin 18
    3: 25   # Air Humidity   — phys pin 22
    4: 12   # pH             — phys pin 32
    5: 16   # Grow Light     — phys pin 36
    6: 20   # Irr Pump       — phys pin 38
    7: 21   # Activity       — phys pin 40
YAML
)
fi

cat > "$CFG" <<EOF
# Generated by scripts/run-led-simulation.sh — do not commit
api:
  base_url: "${API_URL}"
  timeout_seconds: 5
  api_key: "${PI_KEY}"

device:
  uid: "${DEVICE_UID}"

farm:
  farm_id: ${FARM_ID}

schedule_poll_interval_seconds: 30
offline_queue_path: "${QUEUE}"
offline_flush_interval_seconds: 30

simulation:
  enabled: true
  poll_interval_seconds: 0.25
${SIM_BACKEND}

  gpio_leds:
    heartbeat_pin: 17   # phys pin 11
    fault_pin: 27       # phys pin 13 — on when API unreachable

  sensors:
    - match_name: "Media Moisture Indoor"
      sensor_id: ${MOISTURE}
      pixel: 0
      alert_threshold_low: 25
      alert_threshold_high: 80
      interval_seconds: 120
    - match_name: "EC Sensor"
      sensor_id: ${EC}
      pixel: 1
      alert_threshold_low: 0.5
      alert_threshold_high: 3.5
      interval_seconds: 60
    - match_name: "Air Temp Indoor"
      sensor_id: ${AIR_TEMP}
      pixel: 2
      alert_threshold_low: 16
      alert_threshold_high: 32
      interval_seconds: 60
    - match_name: "Air Humidity Indoor"
      sensor_id: ${AIR_HUM}
      pixel: 3
      alert_threshold_low: 35
      alert_threshold_high: 75
      interval_seconds: 60
    - match_name: "pH Sensor"
      sensor_id: ${PH}
      pixel: 4
      alert_threshold_low: 5.5
      alert_threshold_high: 7.0
      interval_seconds: 60

  actuators:
    - match_name: "Veg Room Grow Light"
      actuator_id: ${GROW_LIGHT}
      actuator_type: light
      pixel: 5
    - match_name: "Veg Room Irrigation Pump"
      actuator_id: ${IRR_PUMP}
      actuator_type: pump
      pixel: 6

  activity_pixel: 7

  synthetic_sensors:
    - sensor_id: ${MOISTURE}
      mode: demo_moisture
      interval_seconds: 5
    - sensor_id: ${EC}
      mode: sine
      center: 1.5
      amplitude: 0.4
      period_seconds: 90
      interval_seconds: 10
EOF

echo "Resolved ids: moisture=${MOISTURE} ec=${EC} air_temp=${AIR_TEMP} air_hum=${AIR_HUM} ph=${PH}"
echo "  actuators: grow_light=${GROW_LIGHT} irr_pump=${IRR_PUMP}"
echo "Driver: ${DRIVER}"
echo "Config: $CFG"
if [[ "$DRIVER" != "neopixel" ]]; then
  cat <<'HINT'

Breadboard plug map (POWER OFF). a–e side only. Full doc:
  docs/pi-light-simulation-runbook.md  →  "Starter-kit breadboard plug map"

  Shared once: Pi pin 6 (GND) → blue (−) rail

  RED    heartbeat  pin 11 → a13 | R b13–b11 | LED+ a11 | LED− a10 | b10→blue
  YELLOW moisture   pin 12 → a20 | R b20–b18 | LED+ a18 | LED− a17 | b17→blue
  BLUE   pump       pin 38 → a30 | R b30–b28 | LED+ a28 | LED− a27 | b27→blue

HINT
fi
echo "Starting pi_client LED simulation (Ctrl+C to stop)..."

cd "$ROOT/pi_client"
if ! python3 -c "import requests, yaml" 2>/dev/null; then
  python3 -m pip install -q -r requirements.txt
fi
exec python3 gr33n_client.py --config "$CFG"
