#!/usr/bin/env bash
# Phase 31 WS3 — pi_client with demo relay actuator (stub GPIO on laptop; real GPIO on Pi).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB_URL="${DATABASE_URL:-postgres://gr33n:gr33n@127.0.0.1:5433/gr33n?sslmode=disable}"
API_URL="${GR33N_API_URL:-http://localhost:8080}"
FARM_ID="${GR33N_FARM_ID:-1}"
PI_KEY="${PI_API_KEY:-}"
DEVICE_UID="${GR33N_DEVICE_UID:-demo-veg-relay-01}"
GPIO_PIN="${GR33N_GPIO_PIN:-17}"
POLL_SEC="${GR33N_SCHEDULE_POLL_SECONDS:-5}"

if [[ -f "$ROOT/.env" ]]; then
  # shellcheck disable=SC1091
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^DATABASE_URL= ]] && DB_URL="${line#DATABASE_URL=}"
    [[ "$line" =~ ^PI_API_KEY= ]] && PI_KEY="${line#PI_API_KEY=}"
    [[ "$line" =~ ^PORT= ]] && port="${line#PORT=}" && API_URL="http://localhost:${port}"
  done < "$ROOT/.env"
fi

if [[ -z "$PI_KEY" ]]; then
  echo "PI_API_KEY not set — add to $ROOT/.env" >&2
  exit 1
fi

read -r DEVICE_ID ACTUATOR_ID ACTUATOR_TYPE <<<"$(psql "$DB_URL" -v ON_ERROR_STOP=1 -t -A -F' ' -c \
  "SELECT d.id, a.id, a.actuator_type
   FROM gr33ncore.devices d
   JOIN gr33ncore.actuators a ON a.device_id = d.id AND a.deleted_at IS NULL
   WHERE d.farm_id = ${FARM_ID} AND d.device_uid = '${DEVICE_UID}' AND d.deleted_at IS NULL
   ORDER BY a.id LIMIT 1")"

if [[ -z "${DEVICE_ID:-}" || "$DEVICE_ID" == "NULL" ]]; then
  echo "Missing demo relay device/actuator (device_uid=${DEVICE_UID}). Run make dev-stack --seed." >&2
  exit 1
fi

CFG="$ROOT/pi_client/.edge-actuator.generated.yaml"
QUEUE="$ROOT/pi_client/.gr33n-edge-actuator-queue.db"

cat > "$CFG" <<EOF
# Generated by scripts/run-edge-actuator-client.sh — do not commit
api:
  base_url: "${API_URL}"
  timeout_seconds: 5
  api_key: "${PI_KEY}"
farm:
  farm_id: ${FARM_ID}
sensors: []
actuators:
  - actuator_id: ${ACTUATOR_ID}
    device_id: ${DEVICE_ID}
    device_type: ${ACTUATOR_TYPE}
    gpio_pin: ${GPIO_PIN}
schedule_poll_interval_seconds: ${POLL_SEC}
offline_queue_path: "${QUEUE}"
offline_flush_interval_seconds: 60
EOF

echo "Actuator client: device_id=${DEVICE_ID} actuator_id=${ACTUATOR_ID} gpio=${GPIO_PIN} poll=${POLL_SEC}s"
echo "Config: $CFG"
echo "Polls GET /farms/${FARM_ID}/devices for pending_command; Ctrl+C to stop."

cd "$ROOT/pi_client"
if ! python3 -c "import requests, yaml" 2>/dev/null; then
  python3 -m pip install -q -r requirements.txt
fi
exec python3 gr33n_client.py --config "$CFG"
