// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actuators.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActuator = `-- name: CreateActuator :one

INSERT INTO gr33ncore.actuators (
    device_id, farm_id, zone_id, name, actuator_type,
    hardware_identifier, feedback_sensor_id, config, meta_data, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
RETURNING id, device_id, farm_id, zone_id, name, actuator_type, hardware_identifier, current_state_numeric, current_state_text, last_known_state_time, last_command_sent_time, feedback_sensor_id, config, meta_data, created_at, updated_at, updated_by_user_id, deleted_at, watts
`

type CreateActuatorParams struct {
	DeviceID           *int64  `db:"device_id" json:"device_id"`
	FarmID             int64   `db:"farm_id" json:"farm_id"`
	ZoneID             *int64  `db:"zone_id" json:"zone_id"`
	Name               string  `db:"name" json:"name"`
	ActuatorType       string  `db:"actuator_type" json:"actuator_type"`
	HardwareIdentifier *string `db:"hardware_identifier" json:"hardware_identifier"`
	FeedbackSensorID   *int64  `db:"feedback_sensor_id" json:"feedback_sensor_id"`
	Config             []byte  `db:"config" json:"config"`
	MetaData           []byte  `db:"meta_data" json:"meta_data"`
}

// ============================================================
// Queries: gr33ncore.actuators + actuator_events
// ============================================================
func (q *Queries) CreateActuator(ctx context.Context, arg CreateActuatorParams) (Gr33ncoreActuator, error) {
	row := q.db.QueryRow(ctx, createActuator,
		arg.DeviceID,
		arg.FarmID,
		arg.ZoneID,
		arg.Name,
		arg.ActuatorType,
		arg.HardwareIdentifier,
		arg.FeedbackSensorID,
		arg.Config,
		arg.MetaData,
	)
	var i Gr33ncoreActuator
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.ActuatorType,
		&i.HardwareIdentifier,
		&i.CurrentStateNumeric,
		&i.CurrentStateText,
		&i.LastKnownStateTime,
		&i.LastCommandSentTime,
		&i.FeedbackSensorID,
		&i.Config,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
		&i.Watts,
	)
	return i, err
}

const getActuatorByID = `-- name: GetActuatorByID :one
SELECT id, device_id, farm_id, zone_id, name, actuator_type, hardware_identifier, current_state_numeric, current_state_text, last_known_state_time, last_command_sent_time, feedback_sensor_id, config, meta_data, created_at, updated_at, updated_by_user_id, deleted_at, watts FROM gr33ncore.actuators
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetActuatorByID(ctx context.Context, id int64) (Gr33ncoreActuator, error) {
	row := q.db.QueryRow(ctx, getActuatorByID, id)
	var i Gr33ncoreActuator
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.ActuatorType,
		&i.HardwareIdentifier,
		&i.CurrentStateNumeric,
		&i.CurrentStateText,
		&i.LastKnownStateTime,
		&i.LastCommandSentTime,
		&i.FeedbackSensorID,
		&i.Config,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
		&i.Watts,
	)
	return i, err
}

const insertActuatorEvent = `-- name: InsertActuatorEvent :one
INSERT INTO gr33ncore.actuator_events (
    event_time, actuator_id, command_sent, parameters_sent,
    triggered_by_user_id, triggered_by_schedule_id, triggered_by_rule_id,
    source, execution_status, meta_data
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING event_time, actuator_id, command_sent, parameters_sent, triggered_by_user_id, triggered_by_schedule_id, triggered_by_rule_id, source, response_received_from_device, execution_status, resulting_state_numeric_actual, resulting_state_text_actual, meta_data
`

type InsertActuatorEventParams struct {
	EventTime             time.Time                                `db:"event_time" json:"event_time"`
	ActuatorID            int64                                    `db:"actuator_id" json:"actuator_id"`
	CommandSent           *string                                  `db:"command_sent" json:"command_sent"`
	ParametersSent        []byte                                   `db:"parameters_sent" json:"parameters_sent"`
	TriggeredByUserID     pgtype.UUID                              `db:"triggered_by_user_id" json:"triggered_by_user_id"`
	TriggeredByScheduleID *int64                                   `db:"triggered_by_schedule_id" json:"triggered_by_schedule_id"`
	TriggeredByRuleID     *int64                                   `db:"triggered_by_rule_id" json:"triggered_by_rule_id"`
	Source                Gr33ncoreActuatorEventSourceEnum         `db:"source" json:"source"`
	ExecutionStatus       NullGr33ncoreActuatorExecutionStatusEnum `db:"execution_status" json:"execution_status"`
	MetaData              []byte                                   `db:"meta_data" json:"meta_data"`
}

func (q *Queries) InsertActuatorEvent(ctx context.Context, arg InsertActuatorEventParams) (Gr33ncoreActuatorEvent, error) {
	row := q.db.QueryRow(ctx, insertActuatorEvent,
		arg.EventTime,
		arg.ActuatorID,
		arg.CommandSent,
		arg.ParametersSent,
		arg.TriggeredByUserID,
		arg.TriggeredByScheduleID,
		arg.TriggeredByRuleID,
		arg.Source,
		arg.ExecutionStatus,
		arg.MetaData,
	)
	var i Gr33ncoreActuatorEvent
	err := row.Scan(
		&i.EventTime,
		&i.ActuatorID,
		&i.CommandSent,
		&i.ParametersSent,
		&i.TriggeredByUserID,
		&i.TriggeredByScheduleID,
		&i.TriggeredByRuleID,
		&i.Source,
		&i.ResponseReceivedFromDevice,
		&i.ExecutionStatus,
		&i.ResultingStateNumericActual,
		&i.ResultingStateTextActual,
		&i.MetaData,
	)
	return i, err
}

const listActuatorEventsByActuator = `-- name: ListActuatorEventsByActuator :many
SELECT event_time, actuator_id, command_sent, parameters_sent, triggered_by_user_id, triggered_by_schedule_id, triggered_by_rule_id, source, response_received_from_device, execution_status, resulting_state_numeric_actual, resulting_state_text_actual, meta_data FROM gr33ncore.actuator_events
WHERE actuator_id = $1
  AND event_time >= $2
ORDER BY event_time DESC
LIMIT $3
`

type ListActuatorEventsByActuatorParams struct {
	ActuatorID int64     `db:"actuator_id" json:"actuator_id"`
	EventTime  time.Time `db:"event_time" json:"event_time"`
	Limit      int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListActuatorEventsByActuator(ctx context.Context, arg ListActuatorEventsByActuatorParams) ([]Gr33ncoreActuatorEvent, error) {
	rows, err := q.db.Query(ctx, listActuatorEventsByActuator, arg.ActuatorID, arg.EventTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreActuatorEvent{}
	for rows.Next() {
		var i Gr33ncoreActuatorEvent
		if err := rows.Scan(
			&i.EventTime,
			&i.ActuatorID,
			&i.CommandSent,
			&i.ParametersSent,
			&i.TriggeredByUserID,
			&i.TriggeredByScheduleID,
			&i.TriggeredByRuleID,
			&i.Source,
			&i.ResponseReceivedFromDevice,
			&i.ExecutionStatus,
			&i.ResultingStateNumericActual,
			&i.ResultingStateTextActual,
			&i.MetaData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActuatorEventsBySchedule = `-- name: ListActuatorEventsBySchedule :many
SELECT event_time, actuator_id, command_sent, parameters_sent, triggered_by_user_id, triggered_by_schedule_id, triggered_by_rule_id, source, response_received_from_device, execution_status, resulting_state_numeric_actual, resulting_state_text_actual, meta_data FROM gr33ncore.actuator_events
WHERE triggered_by_schedule_id = $1
  AND event_time >= $2
ORDER BY event_time DESC
LIMIT $3
`

type ListActuatorEventsByScheduleParams struct {
	TriggeredByScheduleID *int64    `db:"triggered_by_schedule_id" json:"triggered_by_schedule_id"`
	EventTime             time.Time `db:"event_time" json:"event_time"`
	Limit                 int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListActuatorEventsBySchedule(ctx context.Context, arg ListActuatorEventsByScheduleParams) ([]Gr33ncoreActuatorEvent, error) {
	rows, err := q.db.Query(ctx, listActuatorEventsBySchedule, arg.TriggeredByScheduleID, arg.EventTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreActuatorEvent{}
	for rows.Next() {
		var i Gr33ncoreActuatorEvent
		if err := rows.Scan(
			&i.EventTime,
			&i.ActuatorID,
			&i.CommandSent,
			&i.ParametersSent,
			&i.TriggeredByUserID,
			&i.TriggeredByScheduleID,
			&i.TriggeredByRuleID,
			&i.Source,
			&i.ResponseReceivedFromDevice,
			&i.ExecutionStatus,
			&i.ResultingStateNumericActual,
			&i.ResultingStateTextActual,
			&i.MetaData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActuatorsByFarm = `-- name: ListActuatorsByFarm :many
SELECT id, device_id, farm_id, zone_id, name, actuator_type, hardware_identifier, current_state_numeric, current_state_text, last_known_state_time, last_command_sent_time, feedback_sensor_id, config, meta_data, created_at, updated_at, updated_by_user_id, deleted_at, watts FROM gr33ncore.actuators
WHERE farm_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListActuatorsByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreActuator, error) {
	rows, err := q.db.Query(ctx, listActuatorsByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreActuator{}
	for rows.Next() {
		var i Gr33ncoreActuator
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.FarmID,
			&i.ZoneID,
			&i.Name,
			&i.ActuatorType,
			&i.HardwareIdentifier,
			&i.CurrentStateNumeric,
			&i.CurrentStateText,
			&i.LastKnownStateTime,
			&i.LastCommandSentTime,
			&i.FeedbackSensorID,
			&i.Config,
			&i.MetaData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
			&i.Watts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActuatorState = `-- name: UpdateActuatorState :one
UPDATE gr33ncore.actuators
SET current_state_numeric = $2, current_state_text = $3,
    last_known_state_time = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, device_id, farm_id, zone_id, name, actuator_type, hardware_identifier, current_state_numeric, current_state_text, last_known_state_time, last_command_sent_time, feedback_sensor_id, config, meta_data, created_at, updated_at, updated_by_user_id, deleted_at, watts
`

type UpdateActuatorStateParams struct {
	ID                  int64          `db:"id" json:"id"`
	CurrentStateNumeric pgtype.Numeric `db:"current_state_numeric" json:"current_state_numeric"`
	CurrentStateText    *string        `db:"current_state_text" json:"current_state_text"`
}

func (q *Queries) UpdateActuatorState(ctx context.Context, arg UpdateActuatorStateParams) (Gr33ncoreActuator, error) {
	row := q.db.QueryRow(ctx, updateActuatorState, arg.ID, arg.CurrentStateNumeric, arg.CurrentStateText)
	var i Gr33ncoreActuator
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.ActuatorType,
		&i.HardwareIdentifier,
		&i.CurrentStateNumeric,
		&i.CurrentStateText,
		&i.LastKnownStateTime,
		&i.LastCommandSentTime,
		&i.FeedbackSensorID,
		&i.Config,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
		&i.Watts,
	)
	return i, err
}
