// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadAlertsByFarm = `-- name: CountUnreadAlertsByFarm :one
SELECT COUNT(*) FROM gr33ncore.alerts_notifications
WHERE farm_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadAlertsByFarm(ctx context.Context, farmID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadAlertsByFarm, farmID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :one

INSERT INTO gr33ncore.alerts_notifications (
  farm_id, recipient_user_id, triggering_event_source_type,
  triggering_event_source_id, severity, subject_rendered,
  message_text_rendered, status
) VALUES ($1,$2,$3,$4,$5,$6,$7,'pending') RETURNING id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at
`

type CreateAlertParams struct {
	FarmID                    int64                                 `db:"farm_id" json:"farm_id"`
	RecipientUserID           pgtype.UUID                           `db:"recipient_user_id" json:"recipient_user_id"`
	TriggeringEventSourceType *string                               `db:"triggering_event_source_type" json:"triggering_event_source_type"`
	TriggeringEventSourceID   *int64                                `db:"triggering_event_source_id" json:"triggering_event_source_id"`
	Severity                  NullGr33ncoreNotificationPriorityEnum `db:"severity" json:"severity"`
	SubjectRendered           *string                               `db:"subject_rendered" json:"subject_rendered"`
	MessageTextRendered       *string                               `db:"message_text_rendered" json:"message_text_rendered"`
}

// ============================================================
// Queries: gr33ncore.alerts_notifications
// ============================================================
func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Gr33ncoreAlertsNotification, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.FarmID,
		arg.RecipientUserID,
		arg.TriggeringEventSourceType,
		arg.TriggeringEventSourceID,
		arg.Severity,
		arg.SubjectRendered,
		arg.MessageTextRendered,
	)
	var i Gr33ncoreAlertsNotification
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RecipientUserID,
		&i.NotificationTemplateID,
		&i.TriggeringEventSourceType,
		&i.TriggeringEventSourceID,
		&i.Severity,
		&i.SubjectRendered,
		&i.MessageTextRendered,
		&i.MessageHtmlRendered,
		&i.DeliveryAttempts,
		&i.Status,
		&i.IsRead,
		&i.ReadAt,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.CreatedAt,
		&i.ScheduledSendAt,
	)
	return i, err
}

const createAlertForRule = `-- name: CreateAlertForRule :one
INSERT INTO gr33ncore.alerts_notifications (
  farm_id, notification_template_id,
  triggering_event_source_type, triggering_event_source_id,
  severity, subject_rendered, message_text_rendered, status
) VALUES ($1, $2, 'automation_rule', $3, $4, $5, $6, 'pending')
RETURNING id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at
`

type CreateAlertForRuleParams struct {
	FarmID                  int64                                 `db:"farm_id" json:"farm_id"`
	NotificationTemplateID  *int64                                `db:"notification_template_id" json:"notification_template_id"`
	TriggeringEventSourceID *int64                                `db:"triggering_event_source_id" json:"triggering_event_source_id"`
	Severity                NullGr33ncoreNotificationPriorityEnum `db:"severity" json:"severity"`
	SubjectRendered         *string                               `db:"subject_rendered" json:"subject_rendered"`
	MessageTextRendered     *string                               `db:"message_text_rendered" json:"message_text_rendered"`
}

// Inserts an alerts_notifications row for a Phase 20 rule-driven
// send_notification action. Distinct from CreateAlert because it
// carries notification_template_id (so the Alerts page can show which
// template rendered this notification) and sets
// triggering_event_source_type = 'automation_rule'.
func (q *Queries) CreateAlertForRule(ctx context.Context, arg CreateAlertForRuleParams) (Gr33ncoreAlertsNotification, error) {
	row := q.db.QueryRow(ctx, createAlertForRule,
		arg.FarmID,
		arg.NotificationTemplateID,
		arg.TriggeringEventSourceID,
		arg.Severity,
		arg.SubjectRendered,
		arg.MessageTextRendered,
	)
	var i Gr33ncoreAlertsNotification
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RecipientUserID,
		&i.NotificationTemplateID,
		&i.TriggeringEventSourceType,
		&i.TriggeringEventSourceID,
		&i.Severity,
		&i.SubjectRendered,
		&i.MessageTextRendered,
		&i.MessageHtmlRendered,
		&i.DeliveryAttempts,
		&i.Status,
		&i.IsRead,
		&i.ReadAt,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.CreatedAt,
		&i.ScheduledSendAt,
	)
	return i, err
}

const getAlertNotificationByID = `-- name: GetAlertNotificationByID :one
SELECT id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at FROM gr33ncore.alerts_notifications WHERE id = $1
`

func (q *Queries) GetAlertNotificationByID(ctx context.Context, id int64) (Gr33ncoreAlertsNotification, error) {
	row := q.db.QueryRow(ctx, getAlertNotificationByID, id)
	var i Gr33ncoreAlertsNotification
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RecipientUserID,
		&i.NotificationTemplateID,
		&i.TriggeringEventSourceType,
		&i.TriggeringEventSourceID,
		&i.Severity,
		&i.SubjectRendered,
		&i.MessageTextRendered,
		&i.MessageHtmlRendered,
		&i.DeliveryAttempts,
		&i.Status,
		&i.IsRead,
		&i.ReadAt,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.CreatedAt,
		&i.ScheduledSendAt,
	)
	return i, err
}

const getLatestAlertCreatedAtForSource = `-- name: GetLatestAlertCreatedAtForSource :one
SELECT created_at FROM gr33ncore.alerts_notifications
WHERE farm_id = $1
  AND triggering_event_source_type = $2
  AND triggering_event_source_id = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestAlertCreatedAtForSourceParams struct {
	FarmID                    int64   `db:"farm_id" json:"farm_id"`
	TriggeringEventSourceType *string `db:"triggering_event_source_type" json:"triggering_event_source_type"`
	TriggeringEventSourceID   *int64  `db:"triggering_event_source_id" json:"triggering_event_source_id"`
}

// Returns the created_at of the most recent alert for this (farm, source_type, source_id)
// regardless of ack status. Used by the sensor threshold evaluator to enforce per-sensor
// cooldown windows.
func (q *Queries) GetLatestAlertCreatedAtForSource(ctx context.Context, arg GetLatestAlertCreatedAtForSourceParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLatestAlertCreatedAtForSource, arg.FarmID, arg.TriggeringEventSourceType, arg.TriggeringEventSourceID)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const getNotificationTemplateByID = `-- name: GetNotificationTemplateByID :one
SELECT id, farm_id, template_key, description, subject_template, body_template_text, body_template_html, default_delivery_channels, default_priority, is_system_template, created_at, updated_at FROM gr33ncore.notification_templates WHERE id = $1
`

func (q *Queries) GetNotificationTemplateByID(ctx context.Context, id int64) (Gr33ncoreNotificationTemplate, error) {
	row := q.db.QueryRow(ctx, getNotificationTemplateByID, id)
	var i Gr33ncoreNotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TemplateKey,
		&i.Description,
		&i.SubjectTemplate,
		&i.BodyTemplateText,
		&i.BodyTemplateHtml,
		&i.DefaultDeliveryChannels,
		&i.DefaultPriority,
		&i.IsSystemTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentUnacknowledgedAlertForSource = `-- name: GetRecentUnacknowledgedAlertForSource :one
SELECT id FROM gr33ncore.alerts_notifications
WHERE farm_id = $1
  AND triggering_event_source_type = $2
  AND triggering_event_source_id = $3
  AND is_acknowledged = FALSE
  AND created_at > NOW() - INTERVAL '30 minutes'
ORDER BY created_at DESC
LIMIT 1
`

type GetRecentUnacknowledgedAlertForSourceParams struct {
	FarmID                    int64   `db:"farm_id" json:"farm_id"`
	TriggeringEventSourceType *string `db:"triggering_event_source_type" json:"triggering_event_source_type"`
	TriggeringEventSourceID   *int64  `db:"triggering_event_source_id" json:"triggering_event_source_id"`
}

func (q *Queries) GetRecentUnacknowledgedAlertForSource(ctx context.Context, arg GetRecentUnacknowledgedAlertForSourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentUnacknowledgedAlertForSource, arg.FarmID, arg.TriggeringEventSourceType, arg.TriggeringEventSourceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAlertsByFarm = `-- name: ListAlertsByFarm :many
SELECT id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at FROM gr33ncore.alerts_notifications
WHERE farm_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsByFarmParams struct {
	FarmID int64 `db:"farm_id" json:"farm_id"`
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListAlertsByFarm(ctx context.Context, arg ListAlertsByFarmParams) ([]Gr33ncoreAlertsNotification, error) {
	rows, err := q.db.Query(ctx, listAlertsByFarm, arg.FarmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreAlertsNotification{}
	for rows.Next() {
		var i Gr33ncoreAlertsNotification
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.RecipientUserID,
			&i.NotificationTemplateID,
			&i.TriggeringEventSourceType,
			&i.TriggeringEventSourceID,
			&i.Severity,
			&i.SubjectRendered,
			&i.MessageTextRendered,
			&i.MessageHtmlRendered,
			&i.DeliveryAttempts,
			&i.Status,
			&i.IsRead,
			&i.ReadAt,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.CreatedAt,
			&i.ScheduledSendAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByRecipient = `-- name: ListAlertsByRecipient :many
SELECT id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at FROM gr33ncore.alerts_notifications
WHERE recipient_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsByRecipientParams struct {
	RecipientUserID pgtype.UUID `db:"recipient_user_id" json:"recipient_user_id"`
	Limit           int32       `db:"limit" json:"limit"`
	Offset          int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListAlertsByRecipient(ctx context.Context, arg ListAlertsByRecipientParams) ([]Gr33ncoreAlertsNotification, error) {
	rows, err := q.db.Query(ctx, listAlertsByRecipient, arg.RecipientUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreAlertsNotification{}
	for rows.Next() {
		var i Gr33ncoreAlertsNotification
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.RecipientUserID,
			&i.NotificationTemplateID,
			&i.TriggeringEventSourceType,
			&i.TriggeringEventSourceID,
			&i.Severity,
			&i.SubjectRendered,
			&i.MessageTextRendered,
			&i.MessageHtmlRendered,
			&i.DeliveryAttempts,
			&i.Status,
			&i.IsRead,
			&i.ReadAt,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.CreatedAt,
			&i.ScheduledSendAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertAcknowledged = `-- name: MarkAlertAcknowledged :one
UPDATE gr33ncore.alerts_notifications
SET is_acknowledged = TRUE, acknowledged_at = NOW(),
    acknowledged_by_user_id = $2, status = 'acknowledged_by_user'
WHERE id = $1 RETURNING id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at
`

type MarkAlertAcknowledgedParams struct {
	ID                   int64       `db:"id" json:"id"`
	AcknowledgedByUserID pgtype.UUID `db:"acknowledged_by_user_id" json:"acknowledged_by_user_id"`
}

func (q *Queries) MarkAlertAcknowledged(ctx context.Context, arg MarkAlertAcknowledgedParams) (Gr33ncoreAlertsNotification, error) {
	row := q.db.QueryRow(ctx, markAlertAcknowledged, arg.ID, arg.AcknowledgedByUserID)
	var i Gr33ncoreAlertsNotification
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RecipientUserID,
		&i.NotificationTemplateID,
		&i.TriggeringEventSourceType,
		&i.TriggeringEventSourceID,
		&i.Severity,
		&i.SubjectRendered,
		&i.MessageTextRendered,
		&i.MessageHtmlRendered,
		&i.DeliveryAttempts,
		&i.Status,
		&i.IsRead,
		&i.ReadAt,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.CreatedAt,
		&i.ScheduledSendAt,
	)
	return i, err
}

const markAlertRead = `-- name: MarkAlertRead :one
UPDATE gr33ncore.alerts_notifications
SET is_read = TRUE, read_at = NOW(), status = 'read_by_user'
WHERE id = $1 RETURNING id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at
`

func (q *Queries) MarkAlertRead(ctx context.Context, id int64) (Gr33ncoreAlertsNotification, error) {
	row := q.db.QueryRow(ctx, markAlertRead, id)
	var i Gr33ncoreAlertsNotification
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RecipientUserID,
		&i.NotificationTemplateID,
		&i.TriggeringEventSourceType,
		&i.TriggeringEventSourceID,
		&i.Severity,
		&i.SubjectRendered,
		&i.MessageTextRendered,
		&i.MessageHtmlRendered,
		&i.DeliveryAttempts,
		&i.Status,
		&i.IsRead,
		&i.ReadAt,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.CreatedAt,
		&i.ScheduledSendAt,
	)
	return i, err
}
