// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadAlertsByFarm = `-- name: CountUnreadAlertsByFarm :one
SELECT COUNT(*) FROM gr33ncore.alerts_notifications
WHERE farm_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadAlertsByFarm(ctx context.Context, farmID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadAlertsByFarm, farmID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :one

INSERT INTO gr33ncore.alerts_notifications (
  farm_id, recipient_user_id, triggering_event_source_type,
  triggering_event_source_id, severity, subject_rendered,
  message_text_rendered, status
) VALUES ($1,$2,$3,$4,$5,$6,$7,'pending') RETURNING id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at
`

type CreateAlertParams struct {
	FarmID                    int64                                 `db:"farm_id" json:"farm_id"`
	RecipientUserID           pgtype.UUID                           `db:"recipient_user_id" json:"recipient_user_id"`
	TriggeringEventSourceType *string                               `db:"triggering_event_source_type" json:"triggering_event_source_type"`
	TriggeringEventSourceID   *int64                                `db:"triggering_event_source_id" json:"triggering_event_source_id"`
	Severity                  NullGr33ncoreNotificationPriorityEnum `db:"severity" json:"severity"`
	SubjectRendered           *string                               `db:"subject_rendered" json:"subject_rendered"`
	MessageTextRendered       *string                               `db:"message_text_rendered" json:"message_text_rendered"`
}

// ============================================================
// Queries: gr33ncore.alerts_notifications
// ============================================================
func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Gr33ncoreAlertsNotification, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.FarmID,
		arg.RecipientUserID,
		arg.TriggeringEventSourceType,
		arg.TriggeringEventSourceID,
		arg.Severity,
		arg.SubjectRendered,
		arg.MessageTextRendered,
	)
	var i Gr33ncoreAlertsNotification
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RecipientUserID,
		&i.NotificationTemplateID,
		&i.TriggeringEventSourceType,
		&i.TriggeringEventSourceID,
		&i.Severity,
		&i.SubjectRendered,
		&i.MessageTextRendered,
		&i.MessageHtmlRendered,
		&i.DeliveryAttempts,
		&i.Status,
		&i.IsRead,
		&i.ReadAt,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.CreatedAt,
		&i.ScheduledSendAt,
	)
	return i, err
}

const getRecentUnacknowledgedAlertForSource = `-- name: GetRecentUnacknowledgedAlertForSource :one
SELECT id FROM gr33ncore.alerts_notifications
WHERE farm_id = $1
  AND triggering_event_source_type = $2
  AND triggering_event_source_id = $3
  AND is_acknowledged = FALSE
  AND created_at > NOW() - INTERVAL '30 minutes'
ORDER BY created_at DESC
LIMIT 1
`

type GetRecentUnacknowledgedAlertForSourceParams struct {
	FarmID                    int64   `db:"farm_id" json:"farm_id"`
	TriggeringEventSourceType *string `db:"triggering_event_source_type" json:"triggering_event_source_type"`
	TriggeringEventSourceID   *int64  `db:"triggering_event_source_id" json:"triggering_event_source_id"`
}

func (q *Queries) GetRecentUnacknowledgedAlertForSource(ctx context.Context, arg GetRecentUnacknowledgedAlertForSourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentUnacknowledgedAlertForSource, arg.FarmID, arg.TriggeringEventSourceType, arg.TriggeringEventSourceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAlertsByFarm = `-- name: ListAlertsByFarm :many
SELECT id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at FROM gr33ncore.alerts_notifications
WHERE farm_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsByFarmParams struct {
	FarmID int64 `db:"farm_id" json:"farm_id"`
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListAlertsByFarm(ctx context.Context, arg ListAlertsByFarmParams) ([]Gr33ncoreAlertsNotification, error) {
	rows, err := q.db.Query(ctx, listAlertsByFarm, arg.FarmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreAlertsNotification{}
	for rows.Next() {
		var i Gr33ncoreAlertsNotification
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.RecipientUserID,
			&i.NotificationTemplateID,
			&i.TriggeringEventSourceType,
			&i.TriggeringEventSourceID,
			&i.Severity,
			&i.SubjectRendered,
			&i.MessageTextRendered,
			&i.MessageHtmlRendered,
			&i.DeliveryAttempts,
			&i.Status,
			&i.IsRead,
			&i.ReadAt,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.CreatedAt,
			&i.ScheduledSendAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByRecipient = `-- name: ListAlertsByRecipient :many
SELECT id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at FROM gr33ncore.alerts_notifications
WHERE recipient_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsByRecipientParams struct {
	RecipientUserID pgtype.UUID `db:"recipient_user_id" json:"recipient_user_id"`
	Limit           int32       `db:"limit" json:"limit"`
	Offset          int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListAlertsByRecipient(ctx context.Context, arg ListAlertsByRecipientParams) ([]Gr33ncoreAlertsNotification, error) {
	rows, err := q.db.Query(ctx, listAlertsByRecipient, arg.RecipientUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreAlertsNotification{}
	for rows.Next() {
		var i Gr33ncoreAlertsNotification
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.RecipientUserID,
			&i.NotificationTemplateID,
			&i.TriggeringEventSourceType,
			&i.TriggeringEventSourceID,
			&i.Severity,
			&i.SubjectRendered,
			&i.MessageTextRendered,
			&i.MessageHtmlRendered,
			&i.DeliveryAttempts,
			&i.Status,
			&i.IsRead,
			&i.ReadAt,
			&i.IsAcknowledged,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.CreatedAt,
			&i.ScheduledSendAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertAcknowledged = `-- name: MarkAlertAcknowledged :one
UPDATE gr33ncore.alerts_notifications
SET is_acknowledged = TRUE, acknowledged_at = NOW(),
    acknowledged_by_user_id = $2, status = 'acknowledged_by_user'
WHERE id = $1 RETURNING id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at
`

type MarkAlertAcknowledgedParams struct {
	ID                   int64       `db:"id" json:"id"`
	AcknowledgedByUserID pgtype.UUID `db:"acknowledged_by_user_id" json:"acknowledged_by_user_id"`
}

func (q *Queries) MarkAlertAcknowledged(ctx context.Context, arg MarkAlertAcknowledgedParams) (Gr33ncoreAlertsNotification, error) {
	row := q.db.QueryRow(ctx, markAlertAcknowledged, arg.ID, arg.AcknowledgedByUserID)
	var i Gr33ncoreAlertsNotification
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RecipientUserID,
		&i.NotificationTemplateID,
		&i.TriggeringEventSourceType,
		&i.TriggeringEventSourceID,
		&i.Severity,
		&i.SubjectRendered,
		&i.MessageTextRendered,
		&i.MessageHtmlRendered,
		&i.DeliveryAttempts,
		&i.Status,
		&i.IsRead,
		&i.ReadAt,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.CreatedAt,
		&i.ScheduledSendAt,
	)
	return i, err
}

const markAlertRead = `-- name: MarkAlertRead :one
UPDATE gr33ncore.alerts_notifications
SET is_read = TRUE, read_at = NOW(), status = 'read_by_user'
WHERE id = $1 RETURNING id, farm_id, recipient_user_id, notification_template_id, triggering_event_source_type, triggering_event_source_id, severity, subject_rendered, message_text_rendered, message_html_rendered, delivery_attempts, status, is_read, read_at, is_acknowledged, acknowledged_at, acknowledged_by_user_id, created_at, scheduled_send_at
`

func (q *Queries) MarkAlertRead(ctx context.Context, id int64) (Gr33ncoreAlertsNotification, error) {
	row := q.db.QueryRow(ctx, markAlertRead, id)
	var i Gr33ncoreAlertsNotification
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RecipientUserID,
		&i.NotificationTemplateID,
		&i.TriggeringEventSourceType,
		&i.TriggeringEventSourceID,
		&i.Severity,
		&i.SubjectRendered,
		&i.MessageTextRendered,
		&i.MessageHtmlRendered,
		&i.DeliveryAttempts,
		&i.Status,
		&i.IsRead,
		&i.ReadAt,
		&i.IsAcknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.CreatedAt,
		&i.ScheduledSendAt,
	)
	return i, err
}
