// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: animals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAnimalGroup = `-- name: ArchiveAnimalGroup :one
UPDATE gr33nanimals.animal_groups SET
    active          = FALSE,
    archived_at     = NOW(),
    archived_reason = $2,
    updated_at      = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, farm_id, label, species, meta, count, primary_zone_id, active, archived_at, archived_reason, created_at, updated_at, deleted_at
`

type ArchiveAnimalGroupParams struct {
	ID             int64   `db:"id" json:"id"`
	ArchivedReason *string `db:"archived_reason" json:"archived_reason"`
}

func (q *Queries) ArchiveAnimalGroup(ctx context.Context, arg ArchiveAnimalGroupParams) (Gr33nanimalsAnimalGroup, error) {
	row := q.db.QueryRow(ctx, archiveAnimalGroup, arg.ID, arg.ArchivedReason)
	var i Gr33nanimalsAnimalGroup
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Label,
		&i.Species,
		&i.Meta,
		&i.Count,
		&i.PrimaryZoneID,
		&i.Active,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAnimalGroup = `-- name: CreateAnimalGroup :one
INSERT INTO gr33nanimals.animal_groups (
    farm_id, label, species, count, primary_zone_id, meta
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6::jsonb, '{}'::jsonb)
)
RETURNING id, farm_id, label, species, meta, count, primary_zone_id, active, archived_at, archived_reason, created_at, updated_at, deleted_at
`

type CreateAnimalGroupParams struct {
	FarmID        int64   `db:"farm_id" json:"farm_id"`
	Label         string  `db:"label" json:"label"`
	Species       *string `db:"species" json:"species"`
	Count         *int32  `db:"count" json:"count"`
	PrimaryZoneID *int64  `db:"primary_zone_id" json:"primary_zone_id"`
	Meta          []byte  `db:"meta" json:"meta"`
}

func (q *Queries) CreateAnimalGroup(ctx context.Context, arg CreateAnimalGroupParams) (Gr33nanimalsAnimalGroup, error) {
	row := q.db.QueryRow(ctx, createAnimalGroup,
		arg.FarmID,
		arg.Label,
		arg.Species,
		arg.Count,
		arg.PrimaryZoneID,
		arg.Meta,
	)
	var i Gr33nanimalsAnimalGroup
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Label,
		&i.Species,
		&i.Meta,
		&i.Count,
		&i.PrimaryZoneID,
		&i.Active,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLifecycleEvent = `-- name: CreateLifecycleEvent :one
INSERT INTO gr33nanimals.animal_lifecycle_events (
    farm_id, animal_group_id, event_type, event_time,
    delta_count, notes, recorded_by, related_task_id, meta
) VALUES (
    $1,
    $2,
    $3,
    COALESCE($4::timestamptz, NOW()),
    $5,
    $6,
    $7,
    $8,
    COALESCE($9::jsonb, '{}'::jsonb)
) RETURNING id, farm_id, animal_group_id, event_type, event_time, delta_count, notes, recorded_by, related_task_id, meta, created_at
`

type CreateLifecycleEventParams struct {
	FarmID        int64              `db:"farm_id" json:"farm_id"`
	AnimalGroupID int64              `db:"animal_group_id" json:"animal_group_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	EventTime     pgtype.Timestamptz `db:"event_time" json:"event_time"`
	DeltaCount    *int32             `db:"delta_count" json:"delta_count"`
	Notes         *string            `db:"notes" json:"notes"`
	RecordedBy    pgtype.UUID        `db:"recorded_by" json:"recorded_by"`
	RelatedTaskID *int64             `db:"related_task_id" json:"related_task_id"`
	Meta          []byte             `db:"meta" json:"meta"`
}

func (q *Queries) CreateLifecycleEvent(ctx context.Context, arg CreateLifecycleEventParams) (Gr33nanimalsAnimalLifecycleEvent, error) {
	row := q.db.QueryRow(ctx, createLifecycleEvent,
		arg.FarmID,
		arg.AnimalGroupID,
		arg.EventType,
		arg.EventTime,
		arg.DeltaCount,
		arg.Notes,
		arg.RecordedBy,
		arg.RelatedTaskID,
		arg.Meta,
	)
	var i Gr33nanimalsAnimalLifecycleEvent
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.AnimalGroupID,
		&i.EventType,
		&i.EventTime,
		&i.DeltaCount,
		&i.Notes,
		&i.RecordedBy,
		&i.RelatedTaskID,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLifecycleEvent = `-- name: DeleteLifecycleEvent :exec
DELETE FROM gr33nanimals.animal_lifecycle_events
WHERE id = $1
`

func (q *Queries) DeleteLifecycleEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLifecycleEvent, id)
	return err
}

const getAnimalGroupByID = `-- name: GetAnimalGroupByID :one
SELECT id, farm_id, label, species, meta, count, primary_zone_id, active, archived_at, archived_reason, created_at, updated_at, deleted_at FROM gr33nanimals.animal_groups
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnimalGroupByID(ctx context.Context, id int64) (Gr33nanimalsAnimalGroup, error) {
	row := q.db.QueryRow(ctx, getAnimalGroupByID, id)
	var i Gr33nanimalsAnimalGroup
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Label,
		&i.Species,
		&i.Meta,
		&i.Count,
		&i.PrimaryZoneID,
		&i.Active,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLifecycleEventByID = `-- name: GetLifecycleEventByID :one
SELECT id, farm_id, animal_group_id, event_type, event_time, delta_count, notes, recorded_by, related_task_id, meta, created_at FROM gr33nanimals.animal_lifecycle_events
WHERE id = $1
`

func (q *Queries) GetLifecycleEventByID(ctx context.Context, id int64) (Gr33nanimalsAnimalLifecycleEvent, error) {
	row := q.db.QueryRow(ctx, getLifecycleEventByID, id)
	var i Gr33nanimalsAnimalLifecycleEvent
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.AnimalGroupID,
		&i.EventType,
		&i.EventTime,
		&i.DeltaCount,
		&i.Notes,
		&i.RecordedBy,
		&i.RelatedTaskID,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listAnimalGroupsByFarm = `-- name: ListAnimalGroupsByFarm :many

SELECT id, farm_id, label, species, meta, count, primary_zone_id, active, archived_at, archived_reason, created_at, updated_at, deleted_at FROM gr33nanimals.animal_groups
WHERE farm_id = $1 AND deleted_at IS NULL
ORDER BY active DESC, label ASC, id ASC
`

// ============================================================
// Phase 20.8 WS2 — animal_groups + animal_lifecycle_events queries
// ============================================================
func (q *Queries) ListAnimalGroupsByFarm(ctx context.Context, farmID int64) ([]Gr33nanimalsAnimalGroup, error) {
	rows, err := q.db.Query(ctx, listAnimalGroupsByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33nanimalsAnimalGroup{}
	for rows.Next() {
		var i Gr33nanimalsAnimalGroup
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.Label,
			&i.Species,
			&i.Meta,
			&i.Count,
			&i.PrimaryZoneID,
			&i.Active,
			&i.ArchivedAt,
			&i.ArchivedReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifecycleEventsByGroup = `-- name: ListLifecycleEventsByGroup :many
SELECT id, farm_id, animal_group_id, event_type, event_time, delta_count, notes, recorded_by, related_task_id, meta, created_at FROM gr33nanimals.animal_lifecycle_events
WHERE animal_group_id = $1
ORDER BY event_time DESC, id DESC
`

func (q *Queries) ListLifecycleEventsByGroup(ctx context.Context, animalGroupID int64) ([]Gr33nanimalsAnimalLifecycleEvent, error) {
	rows, err := q.db.Query(ctx, listLifecycleEventsByGroup, animalGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33nanimalsAnimalLifecycleEvent{}
	for rows.Next() {
		var i Gr33nanimalsAnimalLifecycleEvent
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.AnimalGroupID,
			&i.EventType,
			&i.EventTime,
			&i.DeltaCount,
			&i.Notes,
			&i.RecordedBy,
			&i.RelatedTaskID,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAnimalGroup = `-- name: SoftDeleteAnimalGroup :exec
UPDATE gr33nanimals.animal_groups
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteAnimalGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteAnimalGroup, id)
	return err
}

const sumLifecycleDeltasByGroup = `-- name: SumLifecycleDeltasByGroup :one
SELECT COALESCE(SUM(delta_count)::bigint, 0)::bigint AS delta_total
FROM gr33nanimals.animal_lifecycle_events
WHERE animal_group_id = $1
`

func (q *Queries) SumLifecycleDeltasByGroup(ctx context.Context, animalGroupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumLifecycleDeltasByGroup, animalGroupID)
	var delta_total int64
	err := row.Scan(&delta_total)
	return delta_total, err
}

const updateAnimalGroup = `-- name: UpdateAnimalGroup :one
UPDATE gr33nanimals.animal_groups SET
    label           = $1,
    species         = $2,
    count           = $3,
    primary_zone_id = $4,
    meta            = COALESCE($5::jsonb, meta),
    updated_at      = NOW()
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, farm_id, label, species, meta, count, primary_zone_id, active, archived_at, archived_reason, created_at, updated_at, deleted_at
`

type UpdateAnimalGroupParams struct {
	Label         string  `db:"label" json:"label"`
	Species       *string `db:"species" json:"species"`
	Count         *int32  `db:"count" json:"count"`
	PrimaryZoneID *int64  `db:"primary_zone_id" json:"primary_zone_id"`
	Meta          []byte  `db:"meta" json:"meta"`
	ID            int64   `db:"id" json:"id"`
}

func (q *Queries) UpdateAnimalGroup(ctx context.Context, arg UpdateAnimalGroupParams) (Gr33nanimalsAnimalGroup, error) {
	row := q.db.QueryRow(ctx, updateAnimalGroup,
		arg.Label,
		arg.Species,
		arg.Count,
		arg.PrimaryZoneID,
		arg.Meta,
		arg.ID,
	)
	var i Gr33nanimalsAnimalGroup
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Label,
		&i.Species,
		&i.Meta,
		&i.Count,
		&i.PrimaryZoneID,
		&i.Active,
		&i.ArchivedAt,
		&i.ArchivedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
