// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO auth.users (email, password_hash) VALUES ($1, $2) RETURNING id, email, password_hash, created_at
`

type CreateAuthUserParams struct {
	Email        *string `db:"email" json:"email"`
	PasswordHash []byte  `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createAuthUser, arg.Email, arg.PasswordHash)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one

SELECT id, email, password_hash, created_at FROM auth.users WHERE email = $1
`

// ============================================================
// Queries: auth.users
// ============================================================
func (q *Queries) GetAuthUserByEmail(ctx context.Context, email *string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateAuthUserPasswordHash = `-- name: UpdateAuthUserPasswordHash :exec
UPDATE auth.users SET password_hash = $2 WHERE id = $1
`

type UpdateAuthUserPasswordHashParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash []byte    `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateAuthUserPasswordHash(ctx context.Context, arg UpdateAuthUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
