// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: automation.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAutomationRun = `-- name: CreateAutomationRun :one
INSERT INTO gr33ncore.automation_runs (
    farm_id, schedule_id, rule_id, status, message, details, executed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, farm_id, schedule_id, rule_id, status, message, details, executed_at
`

type CreateAutomationRunParams struct {
	FarmID     int64     `db:"farm_id" json:"farm_id"`
	ScheduleID *int64    `db:"schedule_id" json:"schedule_id"`
	RuleID     *int64    `db:"rule_id" json:"rule_id"`
	Status     string    `db:"status" json:"status"`
	Message    *string   `db:"message" json:"message"`
	Details    []byte    `db:"details" json:"details"`
	ExecutedAt time.Time `db:"executed_at" json:"executed_at"`
}

func (q *Queries) CreateAutomationRun(ctx context.Context, arg CreateAutomationRunParams) (Gr33ncoreAutomationRun, error) {
	row := q.db.QueryRow(ctx, createAutomationRun,
		arg.FarmID,
		arg.ScheduleID,
		arg.RuleID,
		arg.Status,
		arg.Message,
		arg.Details,
		arg.ExecutedAt,
	)
	var i Gr33ncoreAutomationRun
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ScheduleID,
		&i.RuleID,
		&i.Status,
		&i.Message,
		&i.Details,
		&i.ExecutedAt,
	)
	return i, err
}

const getAutomationRunByDetails = `-- name: GetAutomationRunByDetails :one
SELECT id, farm_id, schedule_id, rule_id, status, message, details, executed_at FROM gr33ncore.automation_runs
WHERE schedule_id = $1 AND details @> $2::jsonb
LIMIT 1
`

type GetAutomationRunByDetailsParams struct {
	ScheduleID *int64 `db:"schedule_id" json:"schedule_id"`
	Column2    []byte `db:"column_2" json:"column_2"`
}

func (q *Queries) GetAutomationRunByDetails(ctx context.Context, arg GetAutomationRunByDetailsParams) (Gr33ncoreAutomationRun, error) {
	row := q.db.QueryRow(ctx, getAutomationRunByDetails, arg.ScheduleID, arg.Column2)
	var i Gr33ncoreAutomationRun
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ScheduleID,
		&i.RuleID,
		&i.Status,
		&i.Message,
		&i.Details,
		&i.ExecutedAt,
	)
	return i, err
}

const getLastSuccessfulRunBySchedule = `-- name: GetLastSuccessfulRunBySchedule :one
SELECT id, farm_id, schedule_id, rule_id, status, message, details, executed_at FROM gr33ncore.automation_runs
WHERE schedule_id = $1 AND status = 'success'
ORDER BY executed_at DESC
LIMIT 1
`

func (q *Queries) GetLastSuccessfulRunBySchedule(ctx context.Context, scheduleID *int64) (Gr33ncoreAutomationRun, error) {
	row := q.db.QueryRow(ctx, getLastSuccessfulRunBySchedule, scheduleID)
	var i Gr33ncoreAutomationRun
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ScheduleID,
		&i.RuleID,
		&i.Status,
		&i.Message,
		&i.Details,
		&i.ExecutedAt,
	)
	return i, err
}

const listActiveSchedules = `-- name: ListActiveSchedules :many
SELECT id, farm_id, name, description, schedule_type, cron_expression, timezone, is_active, last_triggered_time, next_expected_trigger_time, meta_data, created_at, updated_at FROM gr33ncore.schedules
WHERE is_active = TRUE
`

func (q *Queries) ListActiveSchedules(ctx context.Context) ([]Gr33ncoreSchedule, error) {
	rows, err := q.db.Query(ctx, listActiveSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreSchedule{}
	for rows.Next() {
		var i Gr33ncoreSchedule
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.Name,
			&i.Description,
			&i.ScheduleType,
			&i.CronExpression,
			&i.Timezone,
			&i.IsActive,
			&i.LastTriggeredTime,
			&i.NextExpectedTriggerTime,
			&i.MetaData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationRunsByFarm = `-- name: ListAutomationRunsByFarm :many
SELECT id, farm_id, schedule_id, rule_id, status, message, details, executed_at FROM gr33ncore.automation_runs
WHERE farm_id = $1
ORDER BY executed_at DESC
LIMIT $2
`

type ListAutomationRunsByFarmParams struct {
	FarmID int64 `db:"farm_id" json:"farm_id"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListAutomationRunsByFarm(ctx context.Context, arg ListAutomationRunsByFarmParams) ([]Gr33ncoreAutomationRun, error) {
	rows, err := q.db.Query(ctx, listAutomationRunsByFarm, arg.FarmID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreAutomationRun{}
	for rows.Next() {
		var i Gr33ncoreAutomationRun
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ScheduleID,
			&i.RuleID,
			&i.Status,
			&i.Message,
			&i.Details,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutableActionsBySchedule = `-- name: ListExecutableActionsBySchedule :many
SELECT id, schedule_id, rule_id, execution_order, action_type, target_actuator_id, target_automation_rule_id, target_notification_template_id, action_command, action_parameters, delay_before_execution_seconds FROM gr33ncore.executable_actions
WHERE schedule_id = $1
ORDER BY execution_order ASC, id ASC
`

func (q *Queries) ListExecutableActionsBySchedule(ctx context.Context, scheduleID *int64) ([]Gr33ncoreExecutableAction, error) {
	rows, err := q.db.Query(ctx, listExecutableActionsBySchedule, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreExecutableAction{}
	for rows.Next() {
		var i Gr33ncoreExecutableAction
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.RuleID,
			&i.ExecutionOrder,
			&i.ActionType,
			&i.TargetActuatorID,
			&i.TargetAutomationRuleID,
			&i.TargetNotificationTemplateID,
			&i.ActionCommand,
			&i.ActionParameters,
			&i.DelayBeforeExecutionSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByFarm = `-- name: ListSchedulesByFarm :many

SELECT id, farm_id, name, description, schedule_type, cron_expression, timezone, is_active, last_triggered_time, next_expected_trigger_time, meta_data, created_at, updated_at FROM gr33ncore.schedules
WHERE farm_id = $1
ORDER BY name ASC
`

// ============================================================
// Queries: schedules, executable actions, automation runs
// ============================================================
func (q *Queries) ListSchedulesByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreSchedule{}
	for rows.Next() {
		var i Gr33ncoreSchedule
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.Name,
			&i.Description,
			&i.ScheduleType,
			&i.CronExpression,
			&i.Timezone,
			&i.IsActive,
			&i.LastTriggeredTime,
			&i.NextExpectedTriggerTime,
			&i.MetaData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleTriggered = `-- name: MarkScheduleTriggered :one
UPDATE gr33ncore.schedules
SET last_triggered_time = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, farm_id, name, description, schedule_type, cron_expression, timezone, is_active, last_triggered_time, next_expected_trigger_time, meta_data, created_at, updated_at
`

type MarkScheduleTriggeredParams struct {
	ID                int64              `db:"id" json:"id"`
	LastTriggeredTime pgtype.Timestamptz `db:"last_triggered_time" json:"last_triggered_time"`
}

func (q *Queries) MarkScheduleTriggered(ctx context.Context, arg MarkScheduleTriggeredParams) (Gr33ncoreSchedule, error) {
	row := q.db.QueryRow(ctx, markScheduleTriggered, arg.ID, arg.LastTriggeredTime)
	var i Gr33ncoreSchedule
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Name,
		&i.Description,
		&i.ScheduleType,
		&i.CronExpression,
		&i.Timezone,
		&i.IsActive,
		&i.LastTriggeredTime,
		&i.NextExpectedTriggerTime,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScheduleActive = `-- name: UpdateScheduleActive :one
UPDATE gr33ncore.schedules
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, farm_id, name, description, schedule_type, cron_expression, timezone, is_active, last_triggered_time, next_expected_trigger_time, meta_data, created_at, updated_at
`

type UpdateScheduleActiveParams struct {
	ID       int64 `db:"id" json:"id"`
	IsActive bool  `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateScheduleActive(ctx context.Context, arg UpdateScheduleActiveParams) (Gr33ncoreSchedule, error) {
	row := q.db.QueryRow(ctx, updateScheduleActive, arg.ID, arg.IsActive)
	var i Gr33ncoreSchedule
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Name,
		&i.Description,
		&i.ScheduleType,
		&i.CronExpression,
		&i.Timezone,
		&i.IsActive,
		&i.LastTriggeredTime,
		&i.NextExpectedTriggerTime,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
