// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_version.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCatalogVersionBumpAlertForFarm = `-- name: GetCatalogVersionBumpAlertForFarm :one
SELECT id FROM gr33ncore.alerts_notifications
WHERE farm_id = $1
  AND triggering_event_source_type = 'catalog_version_bump'
  AND triggering_event_source_id = $2
LIMIT 1
`

type GetCatalogVersionBumpAlertForFarmParams struct {
	FarmID                  int64  `db:"farm_id" json:"farm_id"`
	TriggeringEventSourceID *int64 `db:"triggering_event_source_id" json:"triggering_event_source_id"`
}

func (q *Queries) GetCatalogVersionBumpAlertForFarm(ctx context.Context, arg GetCatalogVersionBumpAlertForFarmParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCatalogVersionBumpAlertForFarm, arg.FarmID, arg.TriggeringEventSourceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getFarmCatalogVersionSeen = `-- name: GetFarmCatalogVersionSeen :one
SELECT farm_id, catalog_version_seen, notified_at, updated_at
FROM gr33ncore.farm_catalog_version_seen
WHERE farm_id = $1
`

func (q *Queries) GetFarmCatalogVersionSeen(ctx context.Context, farmID int64) (Gr33ncoreFarmCatalogVersionSeen, error) {
	row := q.db.QueryRow(ctx, getFarmCatalogVersionSeen, farmID)
	var i Gr33ncoreFarmCatalogVersionSeen
	err := row.Scan(
		&i.FarmID,
		&i.CatalogVersionSeen,
		&i.NotifiedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxCropCatalogVersion = `-- name: GetMaxCropCatalogVersion :one

SELECT COALESCE(MAX(catalog_version), 1)::int AS max_version
FROM gr33ncrops.crop_catalog_entries
`

// Phase 109 — platform catalog version bump detection + farm admin notifications.
func (q *Queries) GetMaxCropCatalogVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxCropCatalogVersion)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const getPlatformCatalogState = `-- name: GetPlatformCatalogState :one
SELECT id, catalog_version, updated_at
FROM gr33ncore.platform_catalog_state
WHERE id = 1
`

func (q *Queries) GetPlatformCatalogState(ctx context.Context) (Gr33ncorePlatformCatalogState, error) {
	row := q.db.QueryRow(ctx, getPlatformCatalogState)
	var i Gr33ncorePlatformCatalogState
	err := row.Scan(&i.ID, &i.CatalogVersion, &i.UpdatedAt)
	return i, err
}

const listAllFarmIDs = `-- name: ListAllFarmIDs :many
SELECT id FROM gr33ncore.farms WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListAllFarmIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAllFarmIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFarmCatalogNotifyAdminUserIDs = `-- name: ListFarmCatalogNotifyAdminUserIDs :many
SELECT DISTINCT m.user_id
FROM gr33ncore.farm_memberships m
WHERE m.farm_id = $1
  AND m.role_in_farm IN ('owner', 'manager')
UNION
SELECT f.owner_user_id
FROM gr33ncore.farms f
WHERE f.id = $1 AND f.deleted_at IS NULL
`

func (q *Queries) ListFarmCatalogNotifyAdminUserIDs(ctx context.Context, farmID int64) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFarmCatalogNotifyAdminUserIDs, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFarmCatalogVersionSeen = `-- name: UpsertFarmCatalogVersionSeen :one
INSERT INTO gr33ncore.farm_catalog_version_seen (farm_id, catalog_version_seen, notified_at, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (farm_id) DO UPDATE
SET catalog_version_seen = EXCLUDED.catalog_version_seen,
    notified_at = EXCLUDED.notified_at,
    updated_at = NOW()
RETURNING farm_id, catalog_version_seen, notified_at, updated_at
`

type UpsertFarmCatalogVersionSeenParams struct {
	FarmID             int64              `db:"farm_id" json:"farm_id"`
	CatalogVersionSeen int32              `db:"catalog_version_seen" json:"catalog_version_seen"`
	NotifiedAt         pgtype.Timestamptz `db:"notified_at" json:"notified_at"`
}

func (q *Queries) UpsertFarmCatalogVersionSeen(ctx context.Context, arg UpsertFarmCatalogVersionSeenParams) (Gr33ncoreFarmCatalogVersionSeen, error) {
	row := q.db.QueryRow(ctx, upsertFarmCatalogVersionSeen, arg.FarmID, arg.CatalogVersionSeen, arg.NotifiedAt)
	var i Gr33ncoreFarmCatalogVersionSeen
	err := row.Scan(
		&i.FarmID,
		&i.CatalogVersionSeen,
		&i.NotifiedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlatformCatalogState = `-- name: UpsertPlatformCatalogState :one
INSERT INTO gr33ncore.platform_catalog_state (id, catalog_version, updated_at)
VALUES (1, $1, NOW())
ON CONFLICT (id) DO UPDATE
SET catalog_version = EXCLUDED.catalog_version,
    updated_at = NOW()
RETURNING id, catalog_version, updated_at
`

func (q *Queries) UpsertPlatformCatalogState(ctx context.Context, catalogVersion int32) (Gr33ncorePlatformCatalogState, error) {
	row := q.db.QueryRow(ctx, upsertPlatformCatalogState, catalogVersion)
	var i Gr33ncorePlatformCatalogState
	err := row.Scan(&i.ID, &i.CatalogVersion, &i.UpdatedAt)
	return i, err
}
