// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commons_catalog.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPublishedCommonsCatalogEntryBySlug = `-- name: GetPublishedCommonsCatalogEntryBySlug :one
SELECT id, slug, title, summary, body, contributor_display, contributor_uri,
       license_spdx, license_notes, tags, sort_order, created_at, updated_at
FROM gr33ncore.commons_catalog_entries
WHERE published = TRUE AND slug = $1
`

type GetPublishedCommonsCatalogEntryBySlugRow struct {
	ID                 int64     `db:"id" json:"id"`
	Slug               string    `db:"slug" json:"slug"`
	Title              string    `db:"title" json:"title"`
	Summary            string    `db:"summary" json:"summary"`
	Body               []byte    `db:"body" json:"body"`
	ContributorDisplay string    `db:"contributor_display" json:"contributor_display"`
	ContributorUri     *string   `db:"contributor_uri" json:"contributor_uri"`
	LicenseSpdx        string    `db:"license_spdx" json:"license_spdx"`
	LicenseNotes       *string   `db:"license_notes" json:"license_notes"`
	Tags               []string  `db:"tags" json:"tags"`
	SortOrder          int32     `db:"sort_order" json:"sort_order"`
	CreatedAt          time.Time `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPublishedCommonsCatalogEntryBySlug(ctx context.Context, slug string) (GetPublishedCommonsCatalogEntryBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedCommonsCatalogEntryBySlug, slug)
	var i GetPublishedCommonsCatalogEntryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.ContributorDisplay,
		&i.ContributorUri,
		&i.LicenseSpdx,
		&i.LicenseNotes,
		&i.Tags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFarmCommonsCatalogImports = `-- name: ListFarmCommonsCatalogImports :many
SELECT
    i.id,
    i.imported_at,
    i.note,
    e.id AS catalog_entry_id,
    e.slug,
    e.title,
    e.license_spdx,
    e.contributor_display
FROM gr33ncore.farm_commons_catalog_imports i
JOIN gr33ncore.commons_catalog_entries e ON e.id = i.catalog_entry_id
WHERE i.farm_id = $1
ORDER BY i.imported_at DESC
`

type ListFarmCommonsCatalogImportsRow struct {
	ID                 int64     `db:"id" json:"id"`
	ImportedAt         time.Time `db:"imported_at" json:"imported_at"`
	Note               *string   `db:"note" json:"note"`
	CatalogEntryID     int64     `db:"catalog_entry_id" json:"catalog_entry_id"`
	Slug               string    `db:"slug" json:"slug"`
	Title              string    `db:"title" json:"title"`
	LicenseSpdx        string    `db:"license_spdx" json:"license_spdx"`
	ContributorDisplay string    `db:"contributor_display" json:"contributor_display"`
}

func (q *Queries) ListFarmCommonsCatalogImports(ctx context.Context, farmID int64) ([]ListFarmCommonsCatalogImportsRow, error) {
	rows, err := q.db.Query(ctx, listFarmCommonsCatalogImports, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFarmCommonsCatalogImportsRow{}
	for rows.Next() {
		var i ListFarmCommonsCatalogImportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ImportedAt,
			&i.Note,
			&i.CatalogEntryID,
			&i.Slug,
			&i.Title,
			&i.LicenseSpdx,
			&i.ContributorDisplay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCommonsCatalogEntries = `-- name: ListPublishedCommonsCatalogEntries :many

SELECT id, slug, title, summary, contributor_display, contributor_uri,
       license_spdx, license_notes, tags, sort_order, created_at, updated_at
FROM gr33ncore.commons_catalog_entries
WHERE published = TRUE
  AND (
    $1::text = ''
    OR title ILIKE '%' || $1 || '%'
    OR summary ILIKE '%' || $1 || '%'
    OR EXISTS (
        SELECT 1 FROM unnest(tags) AS t(tag)
        WHERE t.tag ILIKE '%' || $1 || '%'
    )
  )
ORDER BY sort_order ASC, title ASC
LIMIT $2 OFFSET $3
`

type ListPublishedCommonsCatalogEntriesParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type ListPublishedCommonsCatalogEntriesRow struct {
	ID                 int64     `db:"id" json:"id"`
	Slug               string    `db:"slug" json:"slug"`
	Title              string    `db:"title" json:"title"`
	Summary            string    `db:"summary" json:"summary"`
	ContributorDisplay string    `db:"contributor_display" json:"contributor_display"`
	ContributorUri     *string   `db:"contributor_uri" json:"contributor_uri"`
	LicenseSpdx        string    `db:"license_spdx" json:"license_spdx"`
	LicenseNotes       *string   `db:"license_notes" json:"license_notes"`
	Tags               []string  `db:"tags" json:"tags"`
	SortOrder          int32     `db:"sort_order" json:"sort_order"`
	CreatedAt          time.Time `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time `db:"updated_at" json:"updated_at"`
}

// ============================================================
// Commons catalog (gr33n_inserts direction — browse / import audit)
// ============================================================
func (q *Queries) ListPublishedCommonsCatalogEntries(ctx context.Context, arg ListPublishedCommonsCatalogEntriesParams) ([]ListPublishedCommonsCatalogEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedCommonsCatalogEntries, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedCommonsCatalogEntriesRow{}
	for rows.Next() {
		var i ListPublishedCommonsCatalogEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.ContributorDisplay,
			&i.ContributorUri,
			&i.LicenseSpdx,
			&i.LicenseNotes,
			&i.Tags,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFarmCommonsCatalogImport = `-- name: UpsertFarmCommonsCatalogImport :one
INSERT INTO gr33ncore.farm_commons_catalog_imports (
    farm_id, catalog_entry_id, imported_by, note
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (farm_id, catalog_entry_id) DO UPDATE SET
    imported_at = NOW(),
    imported_by = EXCLUDED.imported_by,
    note = COALESCE(EXCLUDED.note, farm_commons_catalog_imports.note)
RETURNING id, farm_id, catalog_entry_id, imported_by, imported_at, note
`

type UpsertFarmCommonsCatalogImportParams struct {
	FarmID         int64     `db:"farm_id" json:"farm_id"`
	CatalogEntryID int64     `db:"catalog_entry_id" json:"catalog_entry_id"`
	ImportedBy     uuid.UUID `db:"imported_by" json:"imported_by"`
	Note           *string   `db:"note" json:"note"`
}

func (q *Queries) UpsertFarmCommonsCatalogImport(ctx context.Context, arg UpsertFarmCommonsCatalogImportParams) (Gr33ncoreFarmCommonsCatalogImport, error) {
	row := q.db.QueryRow(ctx, upsertFarmCommonsCatalogImport,
		arg.FarmID,
		arg.CatalogEntryID,
		arg.ImportedBy,
		arg.Note,
	)
	var i Gr33ncoreFarmCommonsCatalogImport
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.CatalogEntryID,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.Note,
	)
	return i, err
}
