// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_turns.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// ──────────────────────────────────────────────────────────────────────────
// gr33ncore.conversation_turns
// ──────────────────────────────────────────────────────────────────────────

const insertConversationTurn = `-- name: InsertConversationTurn :one
INSERT INTO gr33ncore.conversation_turns (
    session_id,
    user_id,
    farm_id,
    turn_index,
    user_message,
    assistant_message,
    llm_model,
    grounded,
    context_count,
    citations,
    prompt_tokens,
    completion_tokens
) VALUES (
    $1,
    $2,
    $3,
    COALESCE(
        (SELECT MAX(turn_index) + 1
           FROM gr33ncore.conversation_turns
          WHERE session_id = $1),
        0
    ),
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, session_id, user_id, farm_id, turn_index, created_at
`

type InsertConversationTurnParams struct {
	SessionID        uuid.UUID `db:"session_id" json:"session_id"`
	UserID           uuid.UUID `db:"user_id" json:"user_id"`
	FarmID           *int64    `db:"farm_id" json:"farm_id"`
	UserMessage      string    `db:"user_message" json:"user_message"`
	AssistantMessage string    `db:"assistant_message" json:"assistant_message"`
	LlmModel         string    `db:"llm_model" json:"llm_model"`
	Grounded         bool      `db:"grounded" json:"grounded"`
	ContextCount     int32     `db:"context_count" json:"context_count"`
	Citations        []byte    `db:"citations" json:"citations"`
	PromptTokens     int32     `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens int32     `db:"completion_tokens" json:"completion_tokens"`
}

type InsertConversationTurnRow struct {
	ID        int64     `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	FarmID    *int64    `db:"farm_id" json:"farm_id"`
	TurnIndex int32     `db:"turn_index" json:"turn_index"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// InsertConversationTurn atomically assigns the next turn_index for the session
// (0-based) and inserts the turn. The UNIQUE (session_id, turn_index) constraint
// plus COALESCE(MAX+1, 0) keeps numbering monotonic without a sequence per session.
func (q *Queries) InsertConversationTurn(ctx context.Context, arg InsertConversationTurnParams) (InsertConversationTurnRow, error) {
	row := q.db.QueryRow(ctx, insertConversationTurn,
		arg.SessionID,
		arg.UserID,
		arg.FarmID,
		arg.UserMessage,
		arg.AssistantMessage,
		arg.LlmModel,
		arg.Grounded,
		arg.ContextCount,
		arg.Citations,
		arg.PromptTokens,
		arg.CompletionTokens,
	)
	var i InsertConversationTurnRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.FarmID,
		&i.TurnIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationTurnsBySession = `-- name: ListConversationTurnsBySession :many
SELECT
    id,
    turn_index,
    farm_id,
    user_message,
    assistant_message,
    llm_model,
    grounded,
    context_count,
    citations,
    prompt_tokens,
    completion_tokens,
    created_at
FROM gr33ncore.conversation_turns
WHERE session_id = $1
  AND user_id    = $2
ORDER BY turn_index ASC
`

type ListConversationTurnsBySessionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

type ListConversationTurnsBySessionRow struct {
	ID               int64     `db:"id" json:"id"`
	TurnIndex        int32     `db:"turn_index" json:"turn_index"`
	FarmID           *int64    `db:"farm_id" json:"farm_id"`
	UserMessage      string    `db:"user_message" json:"user_message"`
	AssistantMessage string    `db:"assistant_message" json:"assistant_message"`
	LlmModel         string    `db:"llm_model" json:"llm_model"`
	Grounded         bool      `db:"grounded" json:"grounded"`
	ContextCount     int32     `db:"context_count" json:"context_count"`
	Citations        []byte    `db:"citations" json:"citations"`
	PromptTokens     int32     `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens int32     `db:"completion_tokens" json:"completion_tokens"`
	CreatedAt        time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) ListConversationTurnsBySession(ctx context.Context, arg ListConversationTurnsBySessionParams) ([]ListConversationTurnsBySessionRow, error) {
	rows, err := q.db.Query(ctx, listConversationTurnsBySession, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationTurnsBySessionRow{}
	for rows.Next() {
		var i ListConversationTurnsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.TurnIndex,
			&i.FarmID,
			&i.UserMessage,
			&i.AssistantMessage,
			&i.LlmModel,
			&i.Grounded,
			&i.ContextCount,
			&i.Citations,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentConversationSessions = `-- name: ListRecentConversationSessions :many
SELECT
    agg.session_id,
    agg.turn_count::int          AS turn_count,
    agg.last_turn_at              AS last_turn_at,
    agg.any_grounded              AS any_grounded,
    agg.total_prompt_tokens       AS total_prompt_tokens,
    agg.total_completion_tokens   AS total_completion_tokens,
    first_t.user_message          AS first_user_message,
    last_t.assistant_message      AS last_assistant_message,
    last_t.farm_id                AS last_farm_id,
    sess.title                    AS title
FROM (
    SELECT
        session_id,
        COUNT(*)                  AS turn_count,
        MAX(created_at)           AS last_turn_at,
        BOOL_OR(grounded)         AS any_grounded,
        SUM(prompt_tokens)::int   AS total_prompt_tokens,
        SUM(completion_tokens)::int AS total_completion_tokens
    FROM gr33ncore.conversation_turns
    WHERE user_id = $1
    GROUP BY session_id
) agg
JOIN LATERAL (
    SELECT user_message
    FROM gr33ncore.conversation_turns
    WHERE session_id = agg.session_id
      AND user_id    = $1
    ORDER BY turn_index ASC
    LIMIT 1
) first_t ON true
JOIN LATERAL (
    SELECT assistant_message, farm_id
    FROM gr33ncore.conversation_turns
    WHERE session_id = agg.session_id
      AND user_id    = $1
    ORDER BY turn_index DESC
    LIMIT 1
) last_t ON true
LEFT JOIN gr33ncore.conversation_sessions sess
    ON sess.id = agg.session_id AND sess.user_id = $1
ORDER BY agg.last_turn_at DESC
LIMIT $2
`

type ListRecentConversationSessionsParams struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	MatchLimit int32     `db:"match_limit" json:"match_limit"`
}

type ListRecentConversationSessionsRow struct {
	SessionID             uuid.UUID `db:"session_id" json:"session_id"`
	TurnCount             int32     `db:"turn_count" json:"turn_count"`
	LastTurnAt            time.Time `db:"last_turn_at" json:"last_turn_at"`
	AnyGrounded           bool      `db:"any_grounded" json:"any_grounded"`
	TotalPromptTokens     int32     `db:"total_prompt_tokens" json:"total_prompt_tokens"`
	TotalCompletionTokens int32     `db:"total_completion_tokens" json:"total_completion_tokens"`
	FirstUserMessage      string    `db:"first_user_message" json:"first_user_message"`
	LastAssistantMessage  string    `db:"last_assistant_message" json:"last_assistant_message"`
	LastFarmID            *int64    `db:"last_farm_id" json:"last_farm_id"`
	Title                 *string   `db:"title" json:"title"`
}

func (q *Queries) ListRecentConversationSessions(ctx context.Context, arg ListRecentConversationSessionsParams) ([]ListRecentConversationSessionsRow, error) {
	rows, err := q.db.Query(ctx, listRecentConversationSessions, arg.UserID, arg.MatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentConversationSessionsRow{}
	for rows.Next() {
		var i ListRecentConversationSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.TurnCount,
			&i.LastTurnAt,
			&i.AnyGrounded,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.FirstUserMessage,
			&i.LastAssistantMessage,
			&i.LastFarmID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ──────────────────────────────────────────────────────────────────────────
// gr33ncore.conversation_sessions
// ──────────────────────────────────────────────────────────────────────────

const upsertConversationSession = `-- name: UpsertConversationSession :exec
INSERT INTO gr33ncore.conversation_sessions (id, user_id)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
    SET updated_at = NOW()
`

type UpsertConversationSessionParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpsertConversationSession(ctx context.Context, arg UpsertConversationSessionParams) error {
	_, err := q.db.Exec(ctx, upsertConversationSession, arg.ID, arg.UserID)
	return err
}

const updateConversationSessionTitle = `-- name: UpdateConversationSessionTitle :one
UPDATE gr33ncore.conversation_sessions
SET title = $1
WHERE id = $2
  AND user_id = $3
RETURNING id, title, updated_at
`

type UpdateConversationSessionTitleParams struct {
	Title  *string   `db:"title" json:"title"`
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type UpdateConversationSessionTitleRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Title     *string   `db:"title" json:"title"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateConversationSessionTitle(ctx context.Context, arg UpdateConversationSessionTitleParams) (UpdateConversationSessionTitleRow, error) {
	row := q.db.QueryRow(ctx, updateConversationSessionTitle, arg.Title, arg.ID, arg.UserID)
	var i UpdateConversationSessionTitleRow
	err := row.Scan(&i.ID, &i.Title, &i.UpdatedAt)
	return i, err
}

const deleteConversationTurnsBySession = `-- name: DeleteConversationTurnsBySession :exec
DELETE FROM gr33ncore.conversation_turns
WHERE session_id = $1
  AND user_id    = $2
`

type DeleteConversationTurnsBySessionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteConversationTurnsBySession(ctx context.Context, arg DeleteConversationTurnsBySessionParams) error {
	_, err := q.db.Exec(ctx, deleteConversationTurnsBySession, arg.SessionID, arg.UserID)
	return err
}

const deleteConversationSession = `-- name: DeleteConversationSession :execrows
DELETE FROM gr33ncore.conversation_sessions
WHERE id = $1
  AND user_id = $2
`

type DeleteConversationSessionParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

// DeleteConversationSession returns the number of rows removed (0 when the
// session never had a metadata row — that's fine, callers still delete turns
// independently).
func (q *Queries) DeleteConversationSession(ctx context.Context, arg DeleteConversationSessionParams) (int64, error) {
	res, err := q.db.Exec(ctx, deleteConversationSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected(), nil
}

// ──────────────────────────────────────────────────────────────────────────
// TTL pruning (Phase 27 WS5 follow-up)
// ──────────────────────────────────────────────────────────────────────────

const deleteStaleConversationTurns = `-- name: DeleteStaleConversationTurns :execrows
DELETE FROM gr33ncore.conversation_turns
WHERE session_id IN (
    SELECT session_id
    FROM gr33ncore.conversation_turns
    GROUP BY session_id
    HAVING MAX(created_at) < $1
)
`

// DeleteStaleConversationTurns removes turns belonging to sessions whose
// latest activity is older than cutoff. Returns the number of rows removed.
func (q *Queries) DeleteStaleConversationTurns(ctx context.Context, cutoff time.Time) (int64, error) {
	res, err := q.db.Exec(ctx, deleteStaleConversationTurns, cutoff)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected(), nil
}

const deleteStaleConversationSessions = `-- name: DeleteStaleConversationSessions :execrows
DELETE FROM gr33ncore.conversation_sessions
WHERE updated_at < $1
`

// DeleteStaleConversationSessions drops session metadata rows whose
// updated_at is older than cutoff. Run AFTER DeleteStaleConversationTurns so
// the per-session row count flips to zero in lockstep with the turn data.
func (q *Queries) DeleteStaleConversationSessions(ctx context.Context, cutoff time.Time) (int64, error) {
	res, err := q.db.Exec(ctx, deleteStaleConversationSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected(), nil
}

// ──────────────────────────────────────────────────────────────────────────
// Cost guards (Phase 27 WS5 follow-up)
// ──────────────────────────────────────────────────────────────────────────

// ChatTokenTotals is the rolling-window token snapshot returned by the
// SumChatTokensSinceFor* queries. All three counts are clamped to >= 0.
type ChatTokenTotals struct {
	PromptTokens     int64 `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens int64 `db:"completion_tokens" json:"completion_tokens"`
	TotalTokens      int64 `db:"total_tokens" json:"total_tokens"`
}

const sumChatTokensSinceForUser = `-- name: SumChatTokensSinceForUser :one
SELECT
    COALESCE(SUM(prompt_tokens), 0)::bigint     AS prompt_tokens,
    COALESCE(SUM(completion_tokens), 0)::bigint AS completion_tokens,
    COALESCE(SUM(prompt_tokens + completion_tokens), 0)::bigint AS total_tokens
FROM gr33ncore.conversation_turns
WHERE user_id = $1
  AND created_at >= $2
`

// SumChatTokensSinceForUser returns the rolling-window token total for a
// single user across every session they own.
func (q *Queries) SumChatTokensSinceForUser(ctx context.Context, userID uuid.UUID, since time.Time) (ChatTokenTotals, error) {
	var t ChatTokenTotals
	err := q.db.QueryRow(ctx, sumChatTokensSinceForUser, userID, since).Scan(
		&t.PromptTokens, &t.CompletionTokens, &t.TotalTokens,
	)
	return t, err
}

const sumChatTokensSinceForFarm = `-- name: SumChatTokensSinceForFarm :one
SELECT
    COALESCE(SUM(prompt_tokens), 0)::bigint     AS prompt_tokens,
    COALESCE(SUM(completion_tokens), 0)::bigint AS completion_tokens,
    COALESCE(SUM(prompt_tokens + completion_tokens), 0)::bigint AS total_tokens
FROM gr33ncore.conversation_turns
WHERE farm_id = $1
  AND created_at >= $2
`

// SumChatTokensSinceForFarm returns the rolling-window token total for a
// single farm across every user who chatted with that farm's data. Plain
// (non-grounded) turns are excluded because their farm_id is NULL.
func (q *Queries) SumChatTokensSinceForFarm(ctx context.Context, farmID int64, since time.Time) (ChatTokenTotals, error) {
	var t ChatTokenTotals
	err := q.db.QueryRow(ctx, sumChatTokensSinceForFarm, farmID, since).Scan(
		&t.PromptTokens, &t.CompletionTokens, &t.TotalTokens,
	)
	return t, err
}
