// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_turns.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertConversationTurn = `-- name: InsertConversationTurn :one
INSERT INTO gr33ncore.conversation_turns (
    session_id,
    user_id,
    farm_id,
    turn_index,
    user_message,
    assistant_message,
    llm_model,
    grounded,
    context_count,
    citations
) VALUES (
    $1,
    $2,
    $3,
    COALESCE(
        (SELECT MAX(turn_index) + 1
           FROM gr33ncore.conversation_turns
          WHERE session_id = $1),
        0
    ),
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, session_id, user_id, farm_id, turn_index, created_at
`

type InsertConversationTurnParams struct {
	SessionID        uuid.UUID `db:"session_id" json:"session_id"`
	UserID           uuid.UUID `db:"user_id" json:"user_id"`
	FarmID           *int64    `db:"farm_id" json:"farm_id"`
	UserMessage      string    `db:"user_message" json:"user_message"`
	AssistantMessage string    `db:"assistant_message" json:"assistant_message"`
	LlmModel         string    `db:"llm_model" json:"llm_model"`
	Grounded         bool      `db:"grounded" json:"grounded"`
	ContextCount     int32     `db:"context_count" json:"context_count"`
	Citations        []byte    `db:"citations" json:"citations"`
}

type InsertConversationTurnRow struct {
	ID        int64     `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	FarmID    *int64    `db:"farm_id" json:"farm_id"`
	TurnIndex int32     `db:"turn_index" json:"turn_index"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// InsertConversationTurn atomically assigns the next turn_index for the session
// (0-based) and inserts the turn. The UNIQUE (session_id, turn_index) constraint
// plus COALESCE(MAX+1, 0) keeps numbering monotonic without a sequence per session.
func (q *Queries) InsertConversationTurn(ctx context.Context, arg InsertConversationTurnParams) (InsertConversationTurnRow, error) {
	row := q.db.QueryRow(ctx, insertConversationTurn,
		arg.SessionID,
		arg.UserID,
		arg.FarmID,
		arg.UserMessage,
		arg.AssistantMessage,
		arg.LlmModel,
		arg.Grounded,
		arg.ContextCount,
		arg.Citations,
	)
	var i InsertConversationTurnRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.FarmID,
		&i.TurnIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationTurnsBySession = `-- name: ListConversationTurnsBySession :many
SELECT
    id,
    turn_index,
    farm_id,
    user_message,
    assistant_message,
    llm_model,
    grounded,
    context_count,
    citations,
    created_at
FROM gr33ncore.conversation_turns
WHERE session_id = $1
  AND user_id    = $2
ORDER BY turn_index ASC
`

type ListConversationTurnsBySessionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

type ListConversationTurnsBySessionRow struct {
	ID               int64     `db:"id" json:"id"`
	TurnIndex        int32     `db:"turn_index" json:"turn_index"`
	FarmID           *int64    `db:"farm_id" json:"farm_id"`
	UserMessage      string    `db:"user_message" json:"user_message"`
	AssistantMessage string    `db:"assistant_message" json:"assistant_message"`
	LlmModel         string    `db:"llm_model" json:"llm_model"`
	Grounded         bool      `db:"grounded" json:"grounded"`
	ContextCount     int32     `db:"context_count" json:"context_count"`
	Citations        []byte    `db:"citations" json:"citations"`
	CreatedAt        time.Time `db:"created_at" json:"created_at"`
}

// ListConversationTurnsBySession returns ordered history for a session, scoped
// to the calling user so a session_id guess can't leak another operator's chat.
func (q *Queries) ListConversationTurnsBySession(ctx context.Context, arg ListConversationTurnsBySessionParams) ([]ListConversationTurnsBySessionRow, error) {
	rows, err := q.db.Query(ctx, listConversationTurnsBySession, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationTurnsBySessionRow{}
	for rows.Next() {
		var i ListConversationTurnsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.TurnIndex,
			&i.FarmID,
			&i.UserMessage,
			&i.AssistantMessage,
			&i.LlmModel,
			&i.Grounded,
			&i.ContextCount,
			&i.Citations,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentConversationSessions = `-- name: ListRecentConversationSessions :many
SELECT
    agg.session_id,
    agg.turn_count::int          AS turn_count,
    agg.last_turn_at              AS last_turn_at,
    agg.any_grounded              AS any_grounded,
    first_t.user_message          AS first_user_message,
    last_t.assistant_message      AS last_assistant_message,
    last_t.farm_id                AS last_farm_id
FROM (
    SELECT
        session_id,
        COUNT(*)        AS turn_count,
        MAX(created_at) AS last_turn_at,
        BOOL_OR(grounded) AS any_grounded
    FROM gr33ncore.conversation_turns
    WHERE user_id = $1
    GROUP BY session_id
) agg
JOIN LATERAL (
    SELECT user_message
    FROM gr33ncore.conversation_turns
    WHERE session_id = agg.session_id
      AND user_id    = $1
    ORDER BY turn_index ASC
    LIMIT 1
) first_t ON true
JOIN LATERAL (
    SELECT assistant_message, farm_id
    FROM gr33ncore.conversation_turns
    WHERE session_id = agg.session_id
      AND user_id    = $1
    ORDER BY turn_index DESC
    LIMIT 1
) last_t ON true
ORDER BY agg.last_turn_at DESC
LIMIT $2
`

type ListRecentConversationSessionsParams struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	MatchLimit int32     `db:"match_limit" json:"match_limit"`
}

type ListRecentConversationSessionsRow struct {
	SessionID            uuid.UUID `db:"session_id" json:"session_id"`
	TurnCount            int32     `db:"turn_count" json:"turn_count"`
	LastTurnAt           time.Time `db:"last_turn_at" json:"last_turn_at"`
	AnyGrounded          bool      `db:"any_grounded" json:"any_grounded"`
	FirstUserMessage     string    `db:"first_user_message" json:"first_user_message"`
	LastAssistantMessage string    `db:"last_assistant_message" json:"last_assistant_message"`
	LastFarmID           *int64    `db:"last_farm_id" json:"last_farm_id"`
}

// ListRecentConversationSessions returns one row per distinct session_id for
// the calling user, most recently active first.
// Used by the UI to populate the session picker / history view.
func (q *Queries) ListRecentConversationSessions(ctx context.Context, arg ListRecentConversationSessionsParams) ([]ListRecentConversationSessionsRow, error) {
	rows, err := q.db.Query(ctx, listRecentConversationSessions, arg.UserID, arg.MatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentConversationSessionsRow{}
	for rows.Next() {
		var i ListRecentConversationSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.TurnCount,
			&i.LastTurnAt,
			&i.AnyGrounded,
			&i.FirstUserMessage,
			&i.LastAssistantMessage,
			&i.LastFarmID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
