// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_turns.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConversationSession = `-- name: DeleteConversationSession :execrows
DELETE FROM gr33ncore.conversation_sessions
WHERE id = $1
  AND user_id = $2
`

type DeleteConversationSessionParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

// Drops the metadata row last. Caller deletes turns first so the user-facing
// session disappears cleanly even when no metadata row was ever created
// (sessions auto-created via UpsertConversationSession backfilled rows for
// pre-existing turn data).
func (q *Queries) DeleteConversationSession(ctx context.Context, arg DeleteConversationSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversationSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConversationTurnsBySession = `-- name: DeleteConversationTurnsBySession :exec
DELETE FROM gr33ncore.conversation_turns
WHERE session_id = $1
  AND user_id    = $2
`

type DeleteConversationTurnsBySessionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteConversationTurnsBySession(ctx context.Context, arg DeleteConversationTurnsBySessionParams) error {
	_, err := q.db.Exec(ctx, deleteConversationTurnsBySession, arg.SessionID, arg.UserID)
	return err
}

const deleteStaleConversationSessions = `-- name: DeleteStaleConversationSessions :execrows
DELETE FROM gr33ncore.conversation_sessions
WHERE updated_at < $1
`

// Phase 27 WS5 follow-up — TTL pruning. Drops session metadata rows whose
// last activity (updated_at) is older than the cutoff. Run AFTER
// DeleteStaleConversationTurns so the visible-to-the-API row count flips to
// zero in lockstep with the turn data.
func (q *Queries) DeleteStaleConversationSessions(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleConversationSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleConversationTurns = `-- name: DeleteStaleConversationTurns :execrows
DELETE FROM gr33ncore.conversation_turns
WHERE session_id IN (
    SELECT ct.session_id
    FROM gr33ncore.conversation_turns ct
    GROUP BY ct.session_id
    HAVING MAX(ct.created_at) < $1
)
`

// Phase 27 WS5 follow-up — TTL pruning. Removes turns belonging to sessions
// whose latest activity (MAX(created_at) per session) is older than the
// cutoff. Cutoff is computed in Go (NOW() - ttl) so the SQL is parameter-only
// and portable across timezones.
func (q *Queries) DeleteStaleConversationTurns(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleConversationTurns, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversationSessionMeta = `-- name: GetConversationSessionMeta :one
SELECT meta
FROM gr33ncore.conversation_sessions
WHERE id = $1
  AND user_id = $2
`

type GetConversationSessionMetaParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetConversationSessionMeta(ctx context.Context, arg GetConversationSessionMetaParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getConversationSessionMeta, arg.ID, arg.UserID)
	var meta json.RawMessage
	err := row.Scan(&meta)
	return meta, err
}

const insertConversationTurn = `-- name: InsertConversationTurn :one

INSERT INTO gr33ncore.conversation_turns (
    session_id,
    user_id,
    farm_id,
    turn_index,
    user_message,
    assistant_message,
    llm_model,
    grounded,
    context_count,
    citations,
    prompt_tokens,
    completion_tokens,
    accuracy_note
) VALUES (
    $1,
    $2,
    $3,
    COALESCE(
        (SELECT MAX(turn_index) + 1
           FROM gr33ncore.conversation_turns
          WHERE session_id = $1),
        0
    ),
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, session_id, user_id, farm_id, turn_index, created_at
`

type InsertConversationTurnParams struct {
	SessionID        uuid.UUID       `db:"session_id" json:"session_id"`
	UserID           uuid.UUID       `db:"user_id" json:"user_id"`
	FarmID           *int64          `db:"farm_id" json:"farm_id"`
	UserMessage      string          `db:"user_message" json:"user_message"`
	AssistantMessage string          `db:"assistant_message" json:"assistant_message"`
	LlmModel         string          `db:"llm_model" json:"llm_model"`
	Grounded         bool            `db:"grounded" json:"grounded"`
	ContextCount     int32           `db:"context_count" json:"context_count"`
	Citations        json.RawMessage `db:"citations" json:"citations"`
	PromptTokens     int32           `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens int32           `db:"completion_tokens" json:"completion_tokens"`
	AccuracyNote     *string         `db:"accuracy_note" json:"accuracy_note"`
}

type InsertConversationTurnRow struct {
	ID        int64     `db:"id" json:"id"`
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	FarmID    *int64    `db:"farm_id" json:"farm_id"`
	TurnIndex int32     `db:"turn_index" json:"turn_index"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// ============================================================
// Queries: gr33ncore.conversation_turns + gr33ncore.conversation_sessions
// ============================================================
// Atomically assigns the next turn_index for the session (0-based) and
// inserts the turn. The UNIQUE (session_id, turn_index) constraint plus
// COALESCE(MAX+1, 0) keeps numbering monotonic without a sequence per session.
func (q *Queries) InsertConversationTurn(ctx context.Context, arg InsertConversationTurnParams) (InsertConversationTurnRow, error) {
	row := q.db.QueryRow(ctx, insertConversationTurn,
		arg.SessionID,
		arg.UserID,
		arg.FarmID,
		arg.UserMessage,
		arg.AssistantMessage,
		arg.LlmModel,
		arg.Grounded,
		arg.ContextCount,
		arg.Citations,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.AccuracyNote,
	)
	var i InsertConversationTurnRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.FarmID,
		&i.TurnIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationFeedbackForFarm = `-- name: ListConversationFeedbackForFarm :many
SELECT
    session_id,
    turn_index,
    user_message,
    assistant_message,
    feedback_rating,
    feedback_reason,
    grounded,
    llm_model,
    created_at,
    feedback_at
FROM gr33ncore.conversation_turns
WHERE farm_id = $1
  AND feedback_rating IS NOT NULL
  AND COALESCE(feedback_at, created_at) >= $2
ORDER BY COALESCE(feedback_at, created_at) DESC
`

type ListConversationFeedbackForFarmParams struct {
	FarmID *int64             `db:"farm_id" json:"farm_id"`
	Since  pgtype.Timestamptz `db:"since" json:"since"`
}

type ListConversationFeedbackForFarmRow struct {
	SessionID        uuid.UUID          `db:"session_id" json:"session_id"`
	TurnIndex        int32              `db:"turn_index" json:"turn_index"`
	UserMessage      string             `db:"user_message" json:"user_message"`
	AssistantMessage string             `db:"assistant_message" json:"assistant_message"`
	FeedbackRating   *string            `db:"feedback_rating" json:"feedback_rating"`
	FeedbackReason   *string            `db:"feedback_reason" json:"feedback_reason"`
	Grounded         bool               `db:"grounded" json:"grounded"`
	LlmModel         string             `db:"llm_model" json:"llm_model"`
	CreatedAt        time.Time          `db:"created_at" json:"created_at"`
	FeedbackAt       pgtype.Timestamptz `db:"feedback_at" json:"feedback_at"`
}

func (q *Queries) ListConversationFeedbackForFarm(ctx context.Context, arg ListConversationFeedbackForFarmParams) ([]ListConversationFeedbackForFarmRow, error) {
	rows, err := q.db.Query(ctx, listConversationFeedbackForFarm, arg.FarmID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationFeedbackForFarmRow{}
	for rows.Next() {
		var i ListConversationFeedbackForFarmRow
		if err := rows.Scan(
			&i.SessionID,
			&i.TurnIndex,
			&i.UserMessage,
			&i.AssistantMessage,
			&i.FeedbackRating,
			&i.FeedbackReason,
			&i.Grounded,
			&i.LlmModel,
			&i.CreatedAt,
			&i.FeedbackAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationTurnsBySession = `-- name: ListConversationTurnsBySession :many
SELECT
    id,
    turn_index,
    farm_id,
    user_message,
    assistant_message,
    llm_model,
    grounded,
    context_count,
    citations,
    prompt_tokens,
    completion_tokens,
    created_at,
    feedback_rating,
    feedback_reason,
    feedback_at,
    accuracy_note
FROM gr33ncore.conversation_turns
WHERE session_id = $1
  AND user_id    = $2
ORDER BY turn_index ASC
`

type ListConversationTurnsBySessionParams struct {
	SessionID uuid.UUID `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

type ListConversationTurnsBySessionRow struct {
	ID               int64              `db:"id" json:"id"`
	TurnIndex        int32              `db:"turn_index" json:"turn_index"`
	FarmID           *int64             `db:"farm_id" json:"farm_id"`
	UserMessage      string             `db:"user_message" json:"user_message"`
	AssistantMessage string             `db:"assistant_message" json:"assistant_message"`
	LlmModel         string             `db:"llm_model" json:"llm_model"`
	Grounded         bool               `db:"grounded" json:"grounded"`
	ContextCount     int32              `db:"context_count" json:"context_count"`
	Citations        json.RawMessage    `db:"citations" json:"citations"`
	PromptTokens     int32              `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens int32              `db:"completion_tokens" json:"completion_tokens"`
	CreatedAt        time.Time          `db:"created_at" json:"created_at"`
	FeedbackRating   *string            `db:"feedback_rating" json:"feedback_rating"`
	FeedbackReason   *string            `db:"feedback_reason" json:"feedback_reason"`
	FeedbackAt       pgtype.Timestamptz `db:"feedback_at" json:"feedback_at"`
	AccuracyNote     *string            `db:"accuracy_note" json:"accuracy_note"`
}

func (q *Queries) ListConversationTurnsBySession(ctx context.Context, arg ListConversationTurnsBySessionParams) ([]ListConversationTurnsBySessionRow, error) {
	rows, err := q.db.Query(ctx, listConversationTurnsBySession, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationTurnsBySessionRow{}
	for rows.Next() {
		var i ListConversationTurnsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.TurnIndex,
			&i.FarmID,
			&i.UserMessage,
			&i.AssistantMessage,
			&i.LlmModel,
			&i.Grounded,
			&i.ContextCount,
			&i.Citations,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CreatedAt,
			&i.FeedbackRating,
			&i.FeedbackReason,
			&i.FeedbackAt,
			&i.AccuracyNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentConversationSessions = `-- name: ListRecentConversationSessions :many
SELECT
    agg.session_id,
    agg.turn_count::int          AS turn_count,
    agg.last_turn_at              AS last_turn_at,
    agg.any_grounded              AS any_grounded,
    agg.total_prompt_tokens       AS total_prompt_tokens,
    agg.total_completion_tokens   AS total_completion_tokens,
    first_t.user_message          AS first_user_message,
    last_t.assistant_message      AS last_assistant_message,
    last_t.farm_id                AS last_farm_id,
    sess.title                    AS title
FROM (
    SELECT
        session_id,
        COUNT(*)                             AS turn_count,
        MAX(ct.created_at)::timestamptz       AS last_turn_at,
        BOOL_OR(grounded)                    AS any_grounded,
        SUM(prompt_tokens)::int              AS total_prompt_tokens,
        SUM(completion_tokens)::int          AS total_completion_tokens
    FROM gr33ncore.conversation_turns ct
    WHERE ct.user_id = $1
    GROUP BY ct.session_id
) agg
JOIN LATERAL (
    SELECT user_message
    FROM gr33ncore.conversation_turns
    WHERE session_id = agg.session_id
      AND user_id    = $1
    ORDER BY turn_index ASC
    LIMIT 1
) first_t ON true
JOIN LATERAL (
    SELECT assistant_message, farm_id
    FROM gr33ncore.conversation_turns
    WHERE session_id = agg.session_id
      AND user_id    = $1
    ORDER BY turn_index DESC
    LIMIT 1
) last_t ON true
LEFT JOIN gr33ncore.conversation_sessions sess
    ON sess.id = agg.session_id AND sess.user_id = $1
ORDER BY agg.last_turn_at DESC
LIMIT $2
`

type ListRecentConversationSessionsParams struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	MatchLimit int32     `db:"match_limit" json:"match_limit"`
}

type ListRecentConversationSessionsRow struct {
	SessionID             uuid.UUID `db:"session_id" json:"session_id"`
	TurnCount             int32     `db:"turn_count" json:"turn_count"`
	LastTurnAt            time.Time `db:"last_turn_at" json:"last_turn_at"`
	AnyGrounded           bool      `db:"any_grounded" json:"any_grounded"`
	TotalPromptTokens     int32     `db:"total_prompt_tokens" json:"total_prompt_tokens"`
	TotalCompletionTokens int32     `db:"total_completion_tokens" json:"total_completion_tokens"`
	FirstUserMessage      string    `db:"first_user_message" json:"first_user_message"`
	LastAssistantMessage  string    `db:"last_assistant_message" json:"last_assistant_message"`
	LastFarmID            *int64    `db:"last_farm_id" json:"last_farm_id"`
	Title                 *string   `db:"title" json:"title"`
}

// LEFT JOIN gr33ncore.conversation_sessions so the title surfaces when the
// operator has renamed the session; otherwise we fall back to the first user
// message in the API layer.
func (q *Queries) ListRecentConversationSessions(ctx context.Context, arg ListRecentConversationSessionsParams) ([]ListRecentConversationSessionsRow, error) {
	rows, err := q.db.Query(ctx, listRecentConversationSessions, arg.UserID, arg.MatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentConversationSessionsRow{}
	for rows.Next() {
		var i ListRecentConversationSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.TurnCount,
			&i.LastTurnAt,
			&i.AnyGrounded,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.FirstUserMessage,
			&i.LastAssistantMessage,
			&i.LastFarmID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumChatTokensSinceForFarm = `-- name: SumChatTokensSinceForFarm :one
SELECT
    COALESCE(SUM(prompt_tokens), 0)::bigint     AS prompt_tokens,
    COALESCE(SUM(completion_tokens), 0)::bigint AS completion_tokens,
    COALESCE(SUM(prompt_tokens + completion_tokens), 0)::bigint AS total_tokens
FROM gr33ncore.conversation_turns
WHERE farm_id = $1
  AND created_at >= $2
`

type SumChatTokensSinceForFarmParams struct {
	FarmID *int64    `db:"farm_id" json:"farm_id"`
	Since  time.Time `db:"since" json:"since"`
}

type SumChatTokensSinceForFarmRow struct {
	PromptTokens     int64 `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens int64 `db:"completion_tokens" json:"completion_tokens"`
	TotalTokens      int64 `db:"total_tokens" json:"total_tokens"`
}

// Phase 27 WS5 follow-up — cost guards. Rolling-window token total for a
// single farm across every user who chatted with that farm's data. Plain
// (non-grounded) turns have farm_id IS NULL and are excluded.
func (q *Queries) SumChatTokensSinceForFarm(ctx context.Context, arg SumChatTokensSinceForFarmParams) (SumChatTokensSinceForFarmRow, error) {
	row := q.db.QueryRow(ctx, sumChatTokensSinceForFarm, arg.FarmID, arg.Since)
	var i SumChatTokensSinceForFarmRow
	err := row.Scan(&i.PromptTokens, &i.CompletionTokens, &i.TotalTokens)
	return i, err
}

const sumChatTokensSinceForUser = `-- name: SumChatTokensSinceForUser :one
SELECT
    COALESCE(SUM(prompt_tokens), 0)::bigint     AS prompt_tokens,
    COALESCE(SUM(completion_tokens), 0)::bigint AS completion_tokens,
    COALESCE(SUM(prompt_tokens + completion_tokens), 0)::bigint AS total_tokens
FROM gr33ncore.conversation_turns
WHERE user_id = $1
  AND created_at >= $2
`

type SumChatTokensSinceForUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Since  time.Time `db:"since" json:"since"`
}

type SumChatTokensSinceForUserRow struct {
	PromptTokens     int64 `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens int64 `db:"completion_tokens" json:"completion_tokens"`
	TotalTokens      int64 `db:"total_tokens" json:"total_tokens"`
}

// Phase 27 WS5 follow-up — cost guards. Rolling-window token total for a
// single user across every session they own. `since` is the window start
// computed in Go (NOW() - window) so the SQL is parameter-only and the
// caller decides on the window length.
func (q *Queries) SumChatTokensSinceForUser(ctx context.Context, arg SumChatTokensSinceForUserParams) (SumChatTokensSinceForUserRow, error) {
	row := q.db.QueryRow(ctx, sumChatTokensSinceForUser, arg.UserID, arg.Since)
	var i SumChatTokensSinceForUserRow
	err := row.Scan(&i.PromptTokens, &i.CompletionTokens, &i.TotalTokens)
	return i, err
}

const updateConversationSessionMeta = `-- name: UpdateConversationSessionMeta :exec
UPDATE gr33ncore.conversation_sessions
SET meta = $1
WHERE id = $2
  AND user_id = $3
`

type UpdateConversationSessionMetaParams struct {
	Meta   json.RawMessage `db:"meta" json:"meta"`
	ID     uuid.UUID       `db:"id" json:"id"`
	UserID uuid.UUID       `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateConversationSessionMeta(ctx context.Context, arg UpdateConversationSessionMetaParams) error {
	_, err := q.db.Exec(ctx, updateConversationSessionMeta, arg.Meta, arg.ID, arg.UserID)
	return err
}

const updateConversationSessionTitle = `-- name: UpdateConversationSessionTitle :one
UPDATE gr33ncore.conversation_sessions
SET title = $1
WHERE id = $2
  AND user_id = $3
RETURNING id, title, updated_at
`

type UpdateConversationSessionTitleParams struct {
	Title  *string   `db:"title" json:"title"`
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type UpdateConversationSessionTitleRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Title     *string   `db:"title" json:"title"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

// Operator rename. Returns the row so the API can confirm ownership in one
// query — RowsAffected = 0 means "not found / not yours" → 404.
func (q *Queries) UpdateConversationSessionTitle(ctx context.Context, arg UpdateConversationSessionTitleParams) (UpdateConversationSessionTitleRow, error) {
	row := q.db.QueryRow(ctx, updateConversationSessionTitle, arg.Title, arg.ID, arg.UserID)
	var i UpdateConversationSessionTitleRow
	err := row.Scan(&i.ID, &i.Title, &i.UpdatedAt)
	return i, err
}

const updateConversationTurnFeedback = `-- name: UpdateConversationTurnFeedback :one
UPDATE gr33ncore.conversation_turns
SET
    feedback_rating = $1,
    feedback_reason = $2,
    feedback_at = NOW()
WHERE session_id = $3
  AND user_id = $4
  AND turn_index = $5
RETURNING
    session_id,
    turn_index,
    feedback_rating,
    feedback_reason,
    feedback_at
`

type UpdateConversationTurnFeedbackParams struct {
	FeedbackRating *string   `db:"feedback_rating" json:"feedback_rating"`
	FeedbackReason *string   `db:"feedback_reason" json:"feedback_reason"`
	SessionID      uuid.UUID `db:"session_id" json:"session_id"`
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	TurnIndex      int32     `db:"turn_index" json:"turn_index"`
}

type UpdateConversationTurnFeedbackRow struct {
	SessionID      uuid.UUID          `db:"session_id" json:"session_id"`
	TurnIndex      int32              `db:"turn_index" json:"turn_index"`
	FeedbackRating *string            `db:"feedback_rating" json:"feedback_rating"`
	FeedbackReason *string            `db:"feedback_reason" json:"feedback_reason"`
	FeedbackAt     pgtype.Timestamptz `db:"feedback_at" json:"feedback_at"`
}

func (q *Queries) UpdateConversationTurnFeedback(ctx context.Context, arg UpdateConversationTurnFeedbackParams) (UpdateConversationTurnFeedbackRow, error) {
	row := q.db.QueryRow(ctx, updateConversationTurnFeedback,
		arg.FeedbackRating,
		arg.FeedbackReason,
		arg.SessionID,
		arg.UserID,
		arg.TurnIndex,
	)
	var i UpdateConversationTurnFeedbackRow
	err := row.Scan(
		&i.SessionID,
		&i.TurnIndex,
		&i.FeedbackRating,
		&i.FeedbackReason,
		&i.FeedbackAt,
	)
	return i, err
}

const upsertConversationSession = `-- name: UpsertConversationSession :exec
INSERT INTO gr33ncore.conversation_sessions (id, user_id)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
    SET updated_at = NOW()
`

type UpsertConversationSessionParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

// Called on every turn insert so the session row exists and updated_at
// tracks the latest turn for ordering. The set_updated_at trigger handles
// updated_at on the conflict branch.
func (q *Queries) UpsertConversationSession(ctx context.Context, arg UpsertConversationSessionParams) error {
	_, err := q.db.Exec(ctx, upsertConversationSession, arg.ID, arg.UserID)
	return err
}
