// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: costs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"gr33n-api/internal/platform/commontypes"
)

const createCostTransaction = `-- name: CreateCostTransaction :one

INSERT INTO gr33ncore.cost_transactions (
    farm_id, transaction_date, category, subcategory, amount, currency,
    description, is_income, created_by_user_id, receipt_file_id,
    document_type, document_reference, counterparty, crop_cycle_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, farm_id, transaction_date, category, subcategory, amount, currency, description, related_module_schema, related_table_name, related_record_id, receipt_file_id, is_income, document_type, document_reference, counterparty, created_by_user_id, created_at, updated_at, crop_cycle_id
`

type CreateCostTransactionParams struct {
	FarmID            int64                        `db:"farm_id" json:"farm_id"`
	TransactionDate   pgtype.Date                  `db:"transaction_date" json:"transaction_date"`
	Category          commontypes.CostCategoryEnum `db:"category" json:"category"`
	Subcategory       *string                      `db:"subcategory" json:"subcategory"`
	Amount            pgtype.Numeric               `db:"amount" json:"amount"`
	Currency          string                       `db:"currency" json:"currency"`
	Description       *string                      `db:"description" json:"description"`
	IsIncome          bool                         `db:"is_income" json:"is_income"`
	CreatedByUserID   pgtype.UUID                  `db:"created_by_user_id" json:"created_by_user_id"`
	ReceiptFileID     *int64                       `db:"receipt_file_id" json:"receipt_file_id"`
	DocumentType      *string                      `db:"document_type" json:"document_type"`
	DocumentReference *string                      `db:"document_reference" json:"document_reference"`
	Counterparty      *string                      `db:"counterparty" json:"counterparty"`
	CropCycleID       *int64                       `db:"crop_cycle_id" json:"crop_cycle_id"`
}

// ============================================================
// Queries: gr33ncore.cost_transactions
// ============================================================
func (q *Queries) CreateCostTransaction(ctx context.Context, arg CreateCostTransactionParams) (Gr33ncoreCostTransaction, error) {
	row := q.db.QueryRow(ctx, createCostTransaction,
		arg.FarmID,
		arg.TransactionDate,
		arg.Category,
		arg.Subcategory,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.IsIncome,
		arg.CreatedByUserID,
		arg.ReceiptFileID,
		arg.DocumentType,
		arg.DocumentReference,
		arg.Counterparty,
		arg.CropCycleID,
	)
	var i Gr33ncoreCostTransaction
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TransactionDate,
		&i.Category,
		&i.Subcategory,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.RelatedModuleSchema,
		&i.RelatedTableName,
		&i.RelatedRecordID,
		&i.ReceiptFileID,
		&i.IsIncome,
		&i.DocumentType,
		&i.DocumentReference,
		&i.Counterparty,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CropCycleID,
	)
	return i, err
}

const deleteCostTransaction = `-- name: DeleteCostTransaction :exec
DELETE FROM gr33ncore.cost_transactions WHERE id = $1
`

func (q *Queries) DeleteCostTransaction(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCostTransaction, id)
	return err
}

const getCostCategoryTotalsByFarm = `-- name: GetCostCategoryTotalsByFarm :many
SELECT
    category,
    currency,
    COALESCE(SUM(CASE WHEN is_income THEN amount ELSE 0 END), 0)::numeric AS income,
    COALESCE(SUM(CASE WHEN NOT is_income THEN amount ELSE 0 END), 0)::numeric AS expense,
    COALESCE(SUM(CASE WHEN is_income THEN amount ELSE -amount END), 0)::numeric AS net,
    COUNT(*)::bigint AS tx_count
FROM gr33ncore.cost_transactions
WHERE farm_id = $1
GROUP BY category, currency
ORDER BY category ASC, currency ASC
`

type GetCostCategoryTotalsByFarmRow struct {
	Category commontypes.CostCategoryEnum `db:"category" json:"category"`
	Currency string                       `db:"currency" json:"currency"`
	Income   pgtype.Numeric               `db:"income" json:"income"`
	Expense  pgtype.Numeric               `db:"expense" json:"expense"`
	Net      pgtype.Numeric               `db:"net" json:"net"`
	TxCount  int64                        `db:"tx_count" json:"tx_count"`
}

func (q *Queries) GetCostCategoryTotalsByFarm(ctx context.Context, farmID int64) ([]GetCostCategoryTotalsByFarmRow, error) {
	rows, err := q.db.Query(ctx, getCostCategoryTotalsByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCostCategoryTotalsByFarmRow{}
	for rows.Next() {
		var i GetCostCategoryTotalsByFarmRow
		if err := rows.Scan(
			&i.Category,
			&i.Currency,
			&i.Income,
			&i.Expense,
			&i.Net,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostCategoryTotalsByFarmForYear = `-- name: GetCostCategoryTotalsByFarmForYear :many
SELECT
    category,
    currency,
    COALESCE(SUM(CASE WHEN is_income THEN amount ELSE 0 END), 0)::numeric AS income,
    COALESCE(SUM(CASE WHEN NOT is_income THEN amount ELSE 0 END), 0)::numeric AS expense,
    COALESCE(SUM(CASE WHEN is_income THEN amount ELSE -amount END), 0)::numeric AS net,
    COUNT(*)::bigint AS tx_count
FROM gr33ncore.cost_transactions
WHERE farm_id = $1
  AND transaction_date >= $2::date
  AND transaction_date < $3::date
GROUP BY category, currency
ORDER BY category ASC, currency ASC
`

type GetCostCategoryTotalsByFarmForYearParams struct {
	FarmID  int64       `db:"farm_id" json:"farm_id"`
	Column2 pgtype.Date `db:"column_2" json:"column_2"`
	Column3 pgtype.Date `db:"column_3" json:"column_3"`
}

type GetCostCategoryTotalsByFarmForYearRow struct {
	Category commontypes.CostCategoryEnum `db:"category" json:"category"`
	Currency string                       `db:"currency" json:"currency"`
	Income   pgtype.Numeric               `db:"income" json:"income"`
	Expense  pgtype.Numeric               `db:"expense" json:"expense"`
	Net      pgtype.Numeric               `db:"net" json:"net"`
	TxCount  int64                        `db:"tx_count" json:"tx_count"`
}

func (q *Queries) GetCostCategoryTotalsByFarmForYear(ctx context.Context, arg GetCostCategoryTotalsByFarmForYearParams) ([]GetCostCategoryTotalsByFarmForYearRow, error) {
	rows, err := q.db.Query(ctx, getCostCategoryTotalsByFarmForYear, arg.FarmID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCostCategoryTotalsByFarmForYearRow{}
	for rows.Next() {
		var i GetCostCategoryTotalsByFarmForYearRow
		if err := rows.Scan(
			&i.Category,
			&i.Currency,
			&i.Income,
			&i.Expense,
			&i.Net,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostSummaryByFarm = `-- name: GetCostSummaryByFarm :one
SELECT
    COALESCE(SUM(CASE WHEN is_income THEN amount ELSE 0 END), 0)::numeric AS total_income,
    COALESCE(SUM(CASE WHEN NOT is_income THEN amount ELSE 0 END), 0)::numeric AS total_expenses,
    COALESCE(SUM(CASE WHEN is_income THEN amount ELSE -amount END), 0)::numeric AS net
FROM gr33ncore.cost_transactions
WHERE farm_id = $1
`

type GetCostSummaryByFarmRow struct {
	TotalIncome   pgtype.Numeric `db:"total_income" json:"total_income"`
	TotalExpenses pgtype.Numeric `db:"total_expenses" json:"total_expenses"`
	Net           pgtype.Numeric `db:"net" json:"net"`
}

func (q *Queries) GetCostSummaryByFarm(ctx context.Context, farmID int64) (GetCostSummaryByFarmRow, error) {
	row := q.db.QueryRow(ctx, getCostSummaryByFarm, farmID)
	var i GetCostSummaryByFarmRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpenses, &i.Net)
	return i, err
}

const getCostTransactionByID = `-- name: GetCostTransactionByID :one
SELECT id, farm_id, transaction_date, category, subcategory, amount, currency, description, related_module_schema, related_table_name, related_record_id, receipt_file_id, is_income, document_type, document_reference, counterparty, created_by_user_id, created_at, updated_at, crop_cycle_id FROM gr33ncore.cost_transactions WHERE id = $1
`

func (q *Queries) GetCostTransactionByID(ctx context.Context, id int64) (Gr33ncoreCostTransaction, error) {
	row := q.db.QueryRow(ctx, getCostTransactionByID, id)
	var i Gr33ncoreCostTransaction
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TransactionDate,
		&i.Category,
		&i.Subcategory,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.RelatedModuleSchema,
		&i.RelatedTableName,
		&i.RelatedRecordID,
		&i.ReceiptFileID,
		&i.IsIncome,
		&i.DocumentType,
		&i.DocumentReference,
		&i.Counterparty,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CropCycleID,
	)
	return i, err
}

const listCostTransactionsByFarm = `-- name: ListCostTransactionsByFarm :many
SELECT id, farm_id, transaction_date, category, subcategory, amount, currency, description, related_module_schema, related_table_name, related_record_id, receipt_file_id, is_income, document_type, document_reference, counterparty, created_by_user_id, created_at, updated_at, crop_cycle_id FROM gr33ncore.cost_transactions
WHERE farm_id = $1
ORDER BY transaction_date DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListCostTransactionsByFarmParams struct {
	FarmID int64 `db:"farm_id" json:"farm_id"`
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListCostTransactionsByFarm(ctx context.Context, arg ListCostTransactionsByFarmParams) ([]Gr33ncoreCostTransaction, error) {
	rows, err := q.db.Query(ctx, listCostTransactionsByFarm, arg.FarmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreCostTransaction{}
	for rows.Next() {
		var i Gr33ncoreCostTransaction
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.TransactionDate,
			&i.Category,
			&i.Subcategory,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.RelatedModuleSchema,
			&i.RelatedTableName,
			&i.RelatedRecordID,
			&i.ReceiptFileID,
			&i.IsIncome,
			&i.DocumentType,
			&i.DocumentReference,
			&i.Counterparty,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CropCycleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostTransactionsByFarmExport = `-- name: ListCostTransactionsByFarmExport :many
SELECT id, farm_id, transaction_date, category, subcategory, amount, currency,
 description, is_income, document_type, document_reference, counterparty
FROM gr33ncore.cost_transactions
WHERE farm_id = $1
ORDER BY transaction_date ASC, id ASC
`

type ListCostTransactionsByFarmExportRow struct {
	ID                int64                        `db:"id" json:"id"`
	FarmID            int64                        `db:"farm_id" json:"farm_id"`
	TransactionDate   pgtype.Date                  `db:"transaction_date" json:"transaction_date"`
	Category          commontypes.CostCategoryEnum `db:"category" json:"category"`
	Subcategory       *string                      `db:"subcategory" json:"subcategory"`
	Amount            pgtype.Numeric               `db:"amount" json:"amount"`
	Currency          string                       `db:"currency" json:"currency"`
	Description       *string                      `db:"description" json:"description"`
	IsIncome          bool                         `db:"is_income" json:"is_income"`
	DocumentType      *string                      `db:"document_type" json:"document_type"`
	DocumentReference *string                      `db:"document_reference" json:"document_reference"`
	Counterparty      *string                      `db:"counterparty" json:"counterparty"`
}

func (q *Queries) ListCostTransactionsByFarmExport(ctx context.Context, farmID int64) ([]ListCostTransactionsByFarmExportRow, error) {
	rows, err := q.db.Query(ctx, listCostTransactionsByFarmExport, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCostTransactionsByFarmExportRow{}
	for rows.Next() {
		var i ListCostTransactionsByFarmExportRow
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.TransactionDate,
			&i.Category,
			&i.Subcategory,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.IsIncome,
			&i.DocumentType,
			&i.DocumentReference,
			&i.Counterparty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCostTransaction = `-- name: UpdateCostTransaction :one
UPDATE gr33ncore.cost_transactions SET
    transaction_date = $2,
    category = $3,
    subcategory = $4,
    amount = $5,
    currency = $6,
    description = $7,
    is_income = $8,
    receipt_file_id = $9,
    document_type = $10,
    document_reference = $11,
    counterparty = $12,
    crop_cycle_id = $13,
    updated_at = NOW()
WHERE id = $1
RETURNING id, farm_id, transaction_date, category, subcategory, amount, currency, description, related_module_schema, related_table_name, related_record_id, receipt_file_id, is_income, document_type, document_reference, counterparty, created_by_user_id, created_at, updated_at, crop_cycle_id
`

type UpdateCostTransactionParams struct {
	ID                int64                        `db:"id" json:"id"`
	TransactionDate   pgtype.Date                  `db:"transaction_date" json:"transaction_date"`
	Category          commontypes.CostCategoryEnum `db:"category" json:"category"`
	Subcategory       *string                      `db:"subcategory" json:"subcategory"`
	Amount            pgtype.Numeric               `db:"amount" json:"amount"`
	Currency          string                       `db:"currency" json:"currency"`
	Description       *string                      `db:"description" json:"description"`
	IsIncome          bool                         `db:"is_income" json:"is_income"`
	ReceiptFileID     *int64                       `db:"receipt_file_id" json:"receipt_file_id"`
	DocumentType      *string                      `db:"document_type" json:"document_type"`
	DocumentReference *string                      `db:"document_reference" json:"document_reference"`
	Counterparty      *string                      `db:"counterparty" json:"counterparty"`
	CropCycleID       *int64                       `db:"crop_cycle_id" json:"crop_cycle_id"`
}

func (q *Queries) UpdateCostTransaction(ctx context.Context, arg UpdateCostTransactionParams) (Gr33ncoreCostTransaction, error) {
	row := q.db.QueryRow(ctx, updateCostTransaction,
		arg.ID,
		arg.TransactionDate,
		arg.Category,
		arg.Subcategory,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.IsIncome,
		arg.ReceiptFileID,
		arg.DocumentType,
		arg.DocumentReference,
		arg.Counterparty,
		arg.CropCycleID,
	)
	var i Gr33ncoreCostTransaction
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TransactionDate,
		&i.Category,
		&i.Subcategory,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.RelatedModuleSchema,
		&i.RelatedTableName,
		&i.RelatedRecordID,
		&i.ReceiptFileID,
		&i.IsIncome,
		&i.DocumentType,
		&i.DocumentReference,
		&i.Counterparty,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CropCycleID,
	)
	return i, err
}
