// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crop_recipe_attribution.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHarvestedCyclesForRecipeOutcomes = `-- name: ListHarvestedCyclesForRecipeOutcomes :many

SELECT
    cc.id,
    cc.farm_id,
    cc.zone_id,
    cc.name,
    cc.started_at,
    cc.harvested_at,
    cc.yield_grams,
    p.crop_key,
    p.display_name AS plant_display_name
FROM gr33nfertigation.crop_cycles cc
INNER JOIN gr33ncrops.plants p ON p.id = cc.plant_id AND p.deleted_at IS NULL
WHERE cc.farm_id = $1
  AND cc.is_active = FALSE
  AND cc.harvested_at IS NOT NULL
  AND cc.yield_grams IS NOT NULL
  AND cc.yield_grams > 0
  AND p.crop_key IS NOT NULL
  AND TRIM(p.crop_key) <> ''
  AND ($2::text IS NULL OR p.crop_key = $2::text)
ORDER BY cc.harvested_at DESC, cc.id DESC
`

type ListHarvestedCyclesForRecipeOutcomesParams struct {
	FarmID  int64   `db:"farm_id" json:"farm_id"`
	CropKey *string `db:"crop_key" json:"crop_key"`
}

type ListHarvestedCyclesForRecipeOutcomesRow struct {
	ID               int64          `db:"id" json:"id"`
	FarmID           int64          `db:"farm_id" json:"farm_id"`
	ZoneID           int64          `db:"zone_id" json:"zone_id"`
	Name             string         `db:"name" json:"name"`
	StartedAt        pgtype.Date    `db:"started_at" json:"started_at"`
	HarvestedAt      pgtype.Date    `db:"harvested_at" json:"harvested_at"`
	YieldGrams       pgtype.Numeric `db:"yield_grams" json:"yield_grams"`
	CropKey          *string        `db:"crop_key" json:"crop_key"`
	PlantDisplayName string         `db:"plant_display_name" json:"plant_display_name"`
}

// Phase 211.05 — recipe attribution for harvested crop cycles
func (q *Queries) ListHarvestedCyclesForRecipeOutcomes(ctx context.Context, arg ListHarvestedCyclesForRecipeOutcomesParams) ([]ListHarvestedCyclesForRecipeOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listHarvestedCyclesForRecipeOutcomes, arg.FarmID, arg.CropKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHarvestedCyclesForRecipeOutcomesRow{}
	for rows.Next() {
		var i ListHarvestedCyclesForRecipeOutcomesRow
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ZoneID,
			&i.Name,
			&i.StartedAt,
			&i.HarvestedAt,
			&i.YieldGrams,
			&i.CropKey,
			&i.PlantDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeAttributionHitsForCycle = `-- name: ListRecipeAttributionHitsForCycle :many
SELECT
    'mix'::text AS source_kind,
    me.id AS source_id,
    me.mixed_at AS occurred_at,
    NULLIF(me.metadata->>'application_recipe_id', '')::bigint AS application_recipe_id,
    NULLIF(me.metadata->>'application_recipe_revision_id', '')::bigint AS application_recipe_revision_id
FROM gr33nfertigation.mixing_events me
LEFT JOIN gr33nfertigation.programs p ON p.id = me.program_id AND p.deleted_at IS NULL
LEFT JOIN gr33nfertigation.reservoirs r ON r.id = me.reservoir_id AND r.deleted_at IS NULL
WHERE me.farm_id = $1
  AND me.mixed_at >= $2::timestamptz
  AND me.mixed_at <= $3::timestamptz
  AND NULLIF(me.metadata->>'application_recipe_id', '') IS NOT NULL
  AND (
    p.target_zone_id = $4
    OR r.zone_id = $4
  )

UNION ALL

SELECT
    'program_run'::text AS source_kind,
    ar.id AS source_id,
    ar.executed_at AS occurred_at,
    NULLIF(ar.details->>'application_recipe_id', '')::bigint AS application_recipe_id,
    NULLIF(ar.details->>'application_recipe_revision_id', '')::bigint AS application_recipe_revision_id
FROM gr33ncore.automation_runs ar
INNER JOIN gr33nfertigation.programs p ON p.id = ar.program_id AND p.deleted_at IS NULL
WHERE ar.farm_id = $1
  AND ar.program_id IS NOT NULL
  AND ar.executed_at >= $2::timestamptz
  AND ar.executed_at <= $3::timestamptz
  AND p.target_zone_id = $4
  AND NULLIF(ar.details->>'application_recipe_id', '') IS NOT NULL

ORDER BY occurred_at ASC, source_id ASC
`

type ListRecipeAttributionHitsForCycleParams struct {
	FarmID int64     `db:"farm_id" json:"farm_id"`
	FromTs time.Time `db:"from_ts" json:"from_ts"`
	ToTs   time.Time `db:"to_ts" json:"to_ts"`
	ZoneID *int64    `db:"zone_id" json:"zone_id"`
}

type ListRecipeAttributionHitsForCycleRow struct {
	SourceKind                  string    `db:"source_kind" json:"source_kind"`
	SourceID                    int64     `db:"source_id" json:"source_id"`
	OccurredAt                  time.Time `db:"occurred_at" json:"occurred_at"`
	ApplicationRecipeID         int64     `db:"application_recipe_id" json:"application_recipe_id"`
	ApplicationRecipeRevisionID int64     `db:"application_recipe_revision_id" json:"application_recipe_revision_id"`
}

func (q *Queries) ListRecipeAttributionHitsForCycle(ctx context.Context, arg ListRecipeAttributionHitsForCycleParams) ([]ListRecipeAttributionHitsForCycleRow, error) {
	rows, err := q.db.Query(ctx, listRecipeAttributionHitsForCycle,
		arg.FarmID,
		arg.FromTs,
		arg.ToTs,
		arg.ZoneID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipeAttributionHitsForCycleRow{}
	for rows.Next() {
		var i ListRecipeAttributionHitsForCycleRow
		if err := rows.Scan(
			&i.SourceKind,
			&i.SourceID,
			&i.OccurredAt,
			&i.ApplicationRecipeID,
			&i.ApplicationRecipeRevisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
