// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crop_cycles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCropCycle = `-- name: CreateCropCycle :one

INSERT INTO gr33nfertigation.crop_cycles (
    farm_id, zone_id, name, strain_or_variety, current_stage,
    is_active, started_at, cycle_notes, primary_program_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, farm_id, zone_id, name, strain_or_variety, current_stage, is_active, started_at, harvested_at, yield_grams, yield_notes, cycle_notes, created_at, updated_at, primary_program_id
`

type CreateCropCycleParams struct {
	FarmID           int64                               `db:"farm_id" json:"farm_id"`
	ZoneID           int64                               `db:"zone_id" json:"zone_id"`
	Name             string                              `db:"name" json:"name"`
	StrainOrVariety  *string                             `db:"strain_or_variety" json:"strain_or_variety"`
	CurrentStage     NullGr33nfertigationGrowthStageEnum `db:"current_stage" json:"current_stage"`
	IsActive         bool                                `db:"is_active" json:"is_active"`
	StartedAt        pgtype.Date                         `db:"started_at" json:"started_at"`
	CycleNotes       *string                             `db:"cycle_notes" json:"cycle_notes"`
	PrimaryProgramID *int64                              `db:"primary_program_id" json:"primary_program_id"`
}

// ============================================================
// Queries: gr33nfertigation.crop_cycles
// ============================================================
func (q *Queries) CreateCropCycle(ctx context.Context, arg CreateCropCycleParams) (Gr33nfertigationCropCycle, error) {
	row := q.db.QueryRow(ctx, createCropCycle,
		arg.FarmID,
		arg.ZoneID,
		arg.Name,
		arg.StrainOrVariety,
		arg.CurrentStage,
		arg.IsActive,
		arg.StartedAt,
		arg.CycleNotes,
		arg.PrimaryProgramID,
	)
	var i Gr33nfertigationCropCycle
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.StrainOrVariety,
		&i.CurrentStage,
		&i.IsActive,
		&i.StartedAt,
		&i.HarvestedAt,
		&i.YieldGrams,
		&i.YieldNotes,
		&i.CycleNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryProgramID,
	)
	return i, err
}

const getCropCycleByID = `-- name: GetCropCycleByID :one
SELECT id, farm_id, zone_id, name, strain_or_variety, current_stage, is_active, started_at, harvested_at, yield_grams, yield_notes, cycle_notes, created_at, updated_at, primary_program_id FROM gr33nfertigation.crop_cycles WHERE id = $1
`

func (q *Queries) GetCropCycleByID(ctx context.Context, id int64) (Gr33nfertigationCropCycle, error) {
	row := q.db.QueryRow(ctx, getCropCycleByID, id)
	var i Gr33nfertigationCropCycle
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.StrainOrVariety,
		&i.CurrentStage,
		&i.IsActive,
		&i.StartedAt,
		&i.HarvestedAt,
		&i.YieldGrams,
		&i.YieldNotes,
		&i.CycleNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryProgramID,
	)
	return i, err
}

const listCropCyclesByFarm = `-- name: ListCropCyclesByFarm :many
SELECT id, farm_id, zone_id, name, strain_or_variety, current_stage, is_active, started_at, harvested_at, yield_grams, yield_notes, cycle_notes, created_at, updated_at, primary_program_id FROM gr33nfertigation.crop_cycles
WHERE farm_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListCropCyclesByFarm(ctx context.Context, farmID int64) ([]Gr33nfertigationCropCycle, error) {
	rows, err := q.db.Query(ctx, listCropCyclesByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33nfertigationCropCycle{}
	for rows.Next() {
		var i Gr33nfertigationCropCycle
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ZoneID,
			&i.Name,
			&i.StrainOrVariety,
			&i.CurrentStage,
			&i.IsActive,
			&i.StartedAt,
			&i.HarvestedAt,
			&i.YieldGrams,
			&i.YieldNotes,
			&i.CycleNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryProgramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCropCycle = `-- name: SoftDeleteCropCycle :exec
UPDATE gr33nfertigation.crop_cycles SET is_active = FALSE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteCropCycle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteCropCycle, id)
	return err
}

const updateCropCycle = `-- name: UpdateCropCycle :one
UPDATE gr33nfertigation.crop_cycles SET
    name = $2,
    strain_or_variety = $3,
    zone_id = $4,
    is_active = $5,
    cycle_notes = $6,
    harvested_at = $7,
    yield_grams = $8,
    yield_notes = $9,
    primary_program_id = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, farm_id, zone_id, name, strain_or_variety, current_stage, is_active, started_at, harvested_at, yield_grams, yield_notes, cycle_notes, created_at, updated_at, primary_program_id
`

type UpdateCropCycleParams struct {
	ID               int64          `db:"id" json:"id"`
	Name             string         `db:"name" json:"name"`
	StrainOrVariety  *string        `db:"strain_or_variety" json:"strain_or_variety"`
	ZoneID           int64          `db:"zone_id" json:"zone_id"`
	IsActive         bool           `db:"is_active" json:"is_active"`
	CycleNotes       *string        `db:"cycle_notes" json:"cycle_notes"`
	HarvestedAt      pgtype.Date    `db:"harvested_at" json:"harvested_at"`
	YieldGrams       pgtype.Numeric `db:"yield_grams" json:"yield_grams"`
	YieldNotes       *string        `db:"yield_notes" json:"yield_notes"`
	PrimaryProgramID *int64         `db:"primary_program_id" json:"primary_program_id"`
}

func (q *Queries) UpdateCropCycle(ctx context.Context, arg UpdateCropCycleParams) (Gr33nfertigationCropCycle, error) {
	row := q.db.QueryRow(ctx, updateCropCycle,
		arg.ID,
		arg.Name,
		arg.StrainOrVariety,
		arg.ZoneID,
		arg.IsActive,
		arg.CycleNotes,
		arg.HarvestedAt,
		arg.YieldGrams,
		arg.YieldNotes,
		arg.PrimaryProgramID,
	)
	var i Gr33nfertigationCropCycle
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.StrainOrVariety,
		&i.CurrentStage,
		&i.IsActive,
		&i.StartedAt,
		&i.HarvestedAt,
		&i.YieldGrams,
		&i.YieldNotes,
		&i.CycleNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryProgramID,
	)
	return i, err
}

const updateCropCycleStage = `-- name: UpdateCropCycleStage :one
UPDATE gr33nfertigation.crop_cycles SET
    current_stage = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, farm_id, zone_id, name, strain_or_variety, current_stage, is_active, started_at, harvested_at, yield_grams, yield_notes, cycle_notes, created_at, updated_at, primary_program_id
`

type UpdateCropCycleStageParams struct {
	ID           int64                               `db:"id" json:"id"`
	CurrentStage NullGr33nfertigationGrowthStageEnum `db:"current_stage" json:"current_stage"`
}

func (q *Queries) UpdateCropCycleStage(ctx context.Context, arg UpdateCropCycleStageParams) (Gr33nfertigationCropCycle, error) {
	row := q.db.QueryRow(ctx, updateCropCycleStage, arg.ID, arg.CurrentStage)
	var i Gr33nfertigationCropCycle
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.StrainOrVariety,
		&i.CurrentStage,
		&i.IsActive,
		&i.StartedAt,
		&i.HarvestedAt,
		&i.YieldGrams,
		&i.YieldNotes,
		&i.CycleNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryProgramID,
	)
	return i, err
}
