// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crop_profiles.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCropProfile = `-- name: CreateCropProfile :one
INSERT INTO gr33ncrops.crop_profiles (
    farm_id, crop_key, display_name, category, source, version, is_builtin, meta
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, farm_id, crop_key, display_name, category, source, version, is_builtin, meta, created_at, updated_at
`

type CreateCropProfileParams struct {
	FarmID      *int64          `db:"farm_id" json:"farm_id"`
	CropKey     string          `db:"crop_key" json:"crop_key"`
	DisplayName string          `db:"display_name" json:"display_name"`
	Category    *string         `db:"category" json:"category"`
	Source      *string         `db:"source" json:"source"`
	Version     int32           `db:"version" json:"version"`
	IsBuiltin   bool            `db:"is_builtin" json:"is_builtin"`
	Meta        json.RawMessage `db:"meta" json:"meta"`
}

func (q *Queries) CreateCropProfile(ctx context.Context, arg CreateCropProfileParams) (Gr33ncropsCropProfile, error) {
	row := q.db.QueryRow(ctx, createCropProfile,
		arg.FarmID,
		arg.CropKey,
		arg.DisplayName,
		arg.Category,
		arg.Source,
		arg.Version,
		arg.IsBuiltin,
		arg.Meta,
	)
	var i Gr33ncropsCropProfile
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.CropKey,
		&i.DisplayName,
		&i.Category,
		&i.Source,
		&i.Version,
		&i.IsBuiltin,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCropProfileStage = `-- name: CreateCropProfileStage :one
INSERT INTO gr33ncrops.crop_profile_stages (
    crop_profile_id, stage, ec_min, ec_target, ec_max, ph_min, ph_max,
    vpd_min_kpa, vpd_max_kpa, temp_min_c, temp_max_c, rh_min_pct, rh_max_pct,
    dli_target, photoperiod_hrs, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, crop_profile_id, stage, ec_min, ec_target, ec_max, ph_min, ph_max, vpd_min_kpa, vpd_max_kpa, temp_min_c, temp_max_c, rh_min_pct, rh_max_pct, dli_target, photoperiod_hrs, notes
`

type CreateCropProfileStageParams struct {
	CropProfileID  int64                           `db:"crop_profile_id" json:"crop_profile_id"`
	Stage          Gr33nfertigationGrowthStageEnum `db:"stage" json:"stage"`
	EcMin          pgtype.Numeric                  `db:"ec_min" json:"ec_min"`
	EcTarget       pgtype.Numeric                  `db:"ec_target" json:"ec_target"`
	EcMax          pgtype.Numeric                  `db:"ec_max" json:"ec_max"`
	PhMin          pgtype.Numeric                  `db:"ph_min" json:"ph_min"`
	PhMax          pgtype.Numeric                  `db:"ph_max" json:"ph_max"`
	VpdMinKpa      pgtype.Numeric                  `db:"vpd_min_kpa" json:"vpd_min_kpa"`
	VpdMaxKpa      pgtype.Numeric                  `db:"vpd_max_kpa" json:"vpd_max_kpa"`
	TempMinC       pgtype.Numeric                  `db:"temp_min_c" json:"temp_min_c"`
	TempMaxC       pgtype.Numeric                  `db:"temp_max_c" json:"temp_max_c"`
	RhMinPct       pgtype.Numeric                  `db:"rh_min_pct" json:"rh_min_pct"`
	RhMaxPct       pgtype.Numeric                  `db:"rh_max_pct" json:"rh_max_pct"`
	DliTarget      pgtype.Numeric                  `db:"dli_target" json:"dli_target"`
	PhotoperiodHrs pgtype.Numeric                  `db:"photoperiod_hrs" json:"photoperiod_hrs"`
	Notes          *string                         `db:"notes" json:"notes"`
}

func (q *Queries) CreateCropProfileStage(ctx context.Context, arg CreateCropProfileStageParams) (Gr33ncropsCropProfileStage, error) {
	row := q.db.QueryRow(ctx, createCropProfileStage,
		arg.CropProfileID,
		arg.Stage,
		arg.EcMin,
		arg.EcTarget,
		arg.EcMax,
		arg.PhMin,
		arg.PhMax,
		arg.VpdMinKpa,
		arg.VpdMaxKpa,
		arg.TempMinC,
		arg.TempMaxC,
		arg.RhMinPct,
		arg.RhMaxPct,
		arg.DliTarget,
		arg.PhotoperiodHrs,
		arg.Notes,
	)
	var i Gr33ncropsCropProfileStage
	err := row.Scan(
		&i.ID,
		&i.CropProfileID,
		&i.Stage,
		&i.EcMin,
		&i.EcTarget,
		&i.EcMax,
		&i.PhMin,
		&i.PhMax,
		&i.VpdMinKpa,
		&i.VpdMaxKpa,
		&i.TempMinC,
		&i.TempMaxC,
		&i.RhMinPct,
		&i.RhMaxPct,
		&i.DliTarget,
		&i.PhotoperiodHrs,
		&i.Notes,
	)
	return i, err
}

const getCropProfile = `-- name: GetCropProfile :one
SELECT id, farm_id, crop_key, display_name, category, source, version, is_builtin, meta, created_at, updated_at FROM gr33ncrops.crop_profiles WHERE id = $1
`

func (q *Queries) GetCropProfile(ctx context.Context, id int64) (Gr33ncropsCropProfile, error) {
	row := q.db.QueryRow(ctx, getCropProfile, id)
	var i Gr33ncropsCropProfile
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.CropKey,
		&i.DisplayName,
		&i.Category,
		&i.Source,
		&i.Version,
		&i.IsBuiltin,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCropProfileByKey = `-- name: GetCropProfileByKey :one
SELECT id, farm_id, crop_key, display_name, category, source, version, is_builtin, meta, created_at, updated_at
FROM gr33ncrops.crop_profiles
WHERE crop_key = $1
  AND (farm_id IS NULL AND is_builtin = TRUE OR farm_id = $2)
ORDER BY is_builtin DESC
LIMIT 1
`

type GetCropProfileByKeyParams struct {
	CropKey string `db:"crop_key" json:"crop_key"`
	FarmID  *int64 `db:"farm_id" json:"farm_id"`
}

func (q *Queries) GetCropProfileByKey(ctx context.Context, arg GetCropProfileByKeyParams) (Gr33ncropsCropProfile, error) {
	row := q.db.QueryRow(ctx, getCropProfileByKey, arg.CropKey, arg.FarmID)
	var i Gr33ncropsCropProfile
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.CropKey,
		&i.DisplayName,
		&i.Category,
		&i.Source,
		&i.Version,
		&i.IsBuiltin,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCropProfileStage = `-- name: GetCropProfileStage :one
SELECT s.id, s.crop_profile_id, s.stage, s.ec_min, s.ec_target, s.ec_max, s.ph_min, s.ph_max, s.vpd_min_kpa, s.vpd_max_kpa, s.temp_min_c, s.temp_max_c, s.rh_min_pct, s.rh_max_pct, s.dli_target, s.photoperiod_hrs, s.notes
FROM gr33ncrops.crop_profile_stages s
JOIN gr33ncrops.crop_profiles p ON p.id = s.crop_profile_id
WHERE s.crop_profile_id = $1 AND s.stage = $2
`

type GetCropProfileStageParams struct {
	CropProfileID int64                           `db:"crop_profile_id" json:"crop_profile_id"`
	Stage         Gr33nfertigationGrowthStageEnum `db:"stage" json:"stage"`
}

func (q *Queries) GetCropProfileStage(ctx context.Context, arg GetCropProfileStageParams) (Gr33ncropsCropProfileStage, error) {
	row := q.db.QueryRow(ctx, getCropProfileStage, arg.CropProfileID, arg.Stage)
	var i Gr33ncropsCropProfileStage
	err := row.Scan(
		&i.ID,
		&i.CropProfileID,
		&i.Stage,
		&i.EcMin,
		&i.EcTarget,
		&i.EcMax,
		&i.PhMin,
		&i.PhMax,
		&i.VpdMinKpa,
		&i.VpdMaxKpa,
		&i.TempMinC,
		&i.TempMaxC,
		&i.RhMinPct,
		&i.RhMaxPct,
		&i.DliTarget,
		&i.PhotoperiodHrs,
		&i.Notes,
	)
	return i, err
}

const listCropProfileStages = `-- name: ListCropProfileStages :many
SELECT id, crop_profile_id, stage, ec_min, ec_target, ec_max, ph_min, ph_max, vpd_min_kpa, vpd_max_kpa, temp_min_c, temp_max_c, rh_min_pct, rh_max_pct, dli_target, photoperiod_hrs, notes
FROM gr33ncrops.crop_profile_stages
WHERE crop_profile_id = $1
ORDER BY stage
`

func (q *Queries) ListCropProfileStages(ctx context.Context, cropProfileID int64) ([]Gr33ncropsCropProfileStage, error) {
	rows, err := q.db.Query(ctx, listCropProfileStages, cropProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncropsCropProfileStage{}
	for rows.Next() {
		var i Gr33ncropsCropProfileStage
		if err := rows.Scan(
			&i.ID,
			&i.CropProfileID,
			&i.Stage,
			&i.EcMin,
			&i.EcTarget,
			&i.EcMax,
			&i.PhMin,
			&i.PhMax,
			&i.VpdMinKpa,
			&i.VpdMaxKpa,
			&i.TempMinC,
			&i.TempMaxC,
			&i.RhMinPct,
			&i.RhMaxPct,
			&i.DliTarget,
			&i.PhotoperiodHrs,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCropProfilesForFarm = `-- name: ListCropProfilesForFarm :many
SELECT id, farm_id, crop_key, display_name, category, source, version, is_builtin, meta, created_at, updated_at
FROM gr33ncrops.crop_profiles
WHERE farm_id IS NULL AND is_builtin = TRUE
   OR farm_id = $1
ORDER BY is_builtin DESC, display_name
`

func (q *Queries) ListCropProfilesForFarm(ctx context.Context, farmID *int64) ([]Gr33ncropsCropProfile, error) {
	rows, err := q.db.Query(ctx, listCropProfilesForFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncropsCropProfile{}
	for rows.Next() {
		var i Gr33ncropsCropProfile
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.CropKey,
			&i.DisplayName,
			&i.Category,
			&i.Source,
			&i.Version,
			&i.IsBuiltin,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
