// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crop_cycle_stage_events.sql

package db

import (
	"context"
	"time"
)

const insertCropCycleStageEvent = `-- name: InsertCropCycleStageEvent :one

INSERT INTO gr33nfertigation.crop_cycle_stage_events (
    crop_cycle_id, growth_stage, entered_at
) VALUES ($1, $2, $3)
RETURNING id, crop_cycle_id, growth_stage, entered_at, created_at
`

type InsertCropCycleStageEventParams struct {
	CropCycleID int64                           `db:"crop_cycle_id" json:"crop_cycle_id"`
	GrowthStage Gr33nfertigationGrowthStageEnum `db:"growth_stage" json:"growth_stage"`
	EnteredAt   time.Time                       `db:"entered_at" json:"entered_at"`
}

// ============================================================
// Queries: gr33nfertigation.crop_cycle_stage_events (Phase 56 WS2)
// ============================================================
func (q *Queries) InsertCropCycleStageEvent(ctx context.Context, arg InsertCropCycleStageEventParams) (Gr33nfertigationCropCycleStageEvent, error) {
	row := q.db.QueryRow(ctx, insertCropCycleStageEvent, arg.CropCycleID, arg.GrowthStage, arg.EnteredAt)
	var i Gr33nfertigationCropCycleStageEvent
	err := row.Scan(
		&i.ID,
		&i.CropCycleID,
		&i.GrowthStage,
		&i.EnteredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCropCycleStageEventsByCycle = `-- name: ListCropCycleStageEventsByCycle :many
SELECT id, crop_cycle_id, growth_stage, entered_at, created_at FROM gr33nfertigation.crop_cycle_stage_events
WHERE crop_cycle_id = $1
ORDER BY entered_at ASC, id ASC
`

func (q *Queries) ListCropCycleStageEventsByCycle(ctx context.Context, cropCycleID int64) ([]Gr33nfertigationCropCycleStageEvent, error) {
	rows, err := q.db.Query(ctx, listCropCycleStageEventsByCycle, cropCycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33nfertigationCropCycleStageEvent{}
	for rows.Next() {
		var i Gr33nfertigationCropCycleStageEvent
		if err := rows.Scan(
			&i.ID,
			&i.CropCycleID,
			&i.GrowthStage,
			&i.EnteredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
