// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crop_catalog.sql

package db

import (
	"context"
)

const countAgronomyFieldGuides = `-- name: CountAgronomyFieldGuides :one
SELECT COUNT(*)::bigint AS count FROM gr33ncrops.agronomy_field_guides WHERE published = TRUE
`

func (q *Queries) CountAgronomyFieldGuides(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAgronomyFieldGuides)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBuiltinCropProfiles = `-- name: CountBuiltinCropProfiles :one
SELECT COUNT(*)::bigint AS count FROM gr33ncrops.crop_profiles
WHERE farm_id IS NULL AND is_builtin = TRUE
`

func (q *Queries) CountBuiltinCropProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBuiltinCropProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCropCatalogEntries = `-- name: CountCropCatalogEntries :one
SELECT COUNT(*)::bigint AS count FROM gr33ncrops.crop_catalog_entries
`

func (q *Queries) CountCropCatalogEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCropCatalogEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSupportedCropCatalogEntries = `-- name: CountSupportedCropCatalogEntries :one
SELECT COUNT(*)::bigint AS count FROM gr33ncrops.crop_catalog_entries WHERE supported = TRUE
`

func (q *Queries) CountSupportedCropCatalogEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSupportedCropCatalogEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnsupportedCropCatalogEntries = `-- name: CountUnsupportedCropCatalogEntries :one
SELECT COUNT(*)::bigint AS count FROM gr33ncrops.crop_catalog_entries WHERE supported = FALSE
`

func (q *Queries) CountUnsupportedCropCatalogEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsupportedCropCatalogEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAgronomyFieldGuideBySlug = `-- name: GetAgronomyFieldGuideBySlug :one
SELECT id, slug, title, crop_key, guide_kind, domain, safety_tier, body_md, catalog_version, published, sort_order, created_at, updated_at
FROM gr33ncrops.agronomy_field_guides
WHERE slug = $1
`

func (q *Queries) GetAgronomyFieldGuideBySlug(ctx context.Context, slug string) (Gr33ncropsAgronomyFieldGuide, error) {
	row := q.db.QueryRow(ctx, getAgronomyFieldGuideBySlug, slug)
	var i Gr33ncropsAgronomyFieldGuide
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.CropKey,
		&i.GuideKind,
		&i.Domain,
		&i.SafetyTier,
		&i.BodyMd,
		&i.CatalogVersion,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuiltinCropProfileIDByCropKey = `-- name: GetBuiltinCropProfileIDByCropKey :one
SELECT id
FROM gr33ncrops.crop_profiles
WHERE farm_id IS NULL AND is_builtin = TRUE AND crop_key = $1
`

func (q *Queries) GetBuiltinCropProfileIDByCropKey(ctx context.Context, cropKey string) (int64, error) {
	row := q.db.QueryRow(ctx, getBuiltinCropProfileIDByCropKey, cropKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCropCatalogEntry = `-- name: GetCropCatalogEntry :one
SELECT crop_key, display_name, supported, category, source, substrate, watering_style, runoff_pct_target, moisture_guidance, cousin_of, unsupported_reason, catalog_version, image_url, meta, created_at, updated_at
FROM gr33ncrops.crop_catalog_entries
WHERE crop_key = $1
`

func (q *Queries) GetCropCatalogEntry(ctx context.Context, cropKey string) (Gr33ncropsCropCatalogEntry, error) {
	row := q.db.QueryRow(ctx, getCropCatalogEntry, cropKey)
	var i Gr33ncropsCropCatalogEntry
	err := row.Scan(
		&i.CropKey,
		&i.DisplayName,
		&i.Supported,
		&i.Category,
		&i.Source,
		&i.Substrate,
		&i.WateringStyle,
		&i.RunoffPctTarget,
		&i.MoistureGuidance,
		&i.CousinOf,
		&i.UnsupportedReason,
		&i.CatalogVersion,
		&i.ImageUrl,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedAgronomyFieldGuideBySlug = `-- name: GetPublishedAgronomyFieldGuideBySlug :one
SELECT id, slug, title, crop_key, guide_kind, domain, safety_tier, body_md, catalog_version, published, sort_order, created_at, updated_at
FROM gr33ncrops.agronomy_field_guides
WHERE slug = $1 AND published = TRUE
`

func (q *Queries) GetPublishedAgronomyFieldGuideBySlug(ctx context.Context, slug string) (Gr33ncropsAgronomyFieldGuide, error) {
	row := q.db.QueryRow(ctx, getPublishedAgronomyFieldGuideBySlug, slug)
	var i Gr33ncropsAgronomyFieldGuide
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.CropKey,
		&i.GuideKind,
		&i.Domain,
		&i.SafetyTier,
		&i.BodyMd,
		&i.CatalogVersion,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgronomyFieldGuides = `-- name: ListAgronomyFieldGuides :many
SELECT id, slug, title, crop_key, guide_kind, domain, safety_tier, body_md, catalog_version, published, sort_order, created_at, updated_at
FROM gr33ncrops.agronomy_field_guides
WHERE published = TRUE
ORDER BY sort_order, slug
`

func (q *Queries) ListAgronomyFieldGuides(ctx context.Context) ([]Gr33ncropsAgronomyFieldGuide, error) {
	rows, err := q.db.Query(ctx, listAgronomyFieldGuides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncropsAgronomyFieldGuide{}
	for rows.Next() {
		var i Gr33ncropsAgronomyFieldGuide
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.CropKey,
			&i.GuideKind,
			&i.Domain,
			&i.SafetyTier,
			&i.BodyMd,
			&i.CatalogVersion,
			&i.Published,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCropCatalogAliases = `-- name: ListCropCatalogAliases :many
SELECT alias, crop_key
FROM gr33ncrops.crop_catalog_aliases
ORDER BY alias
`

func (q *Queries) ListCropCatalogAliases(ctx context.Context) ([]Gr33ncropsCropCatalogAlias, error) {
	rows, err := q.db.Query(ctx, listCropCatalogAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncropsCropCatalogAlias{}
	for rows.Next() {
		var i Gr33ncropsCropCatalogAlias
		if err := rows.Scan(&i.Alias, &i.CropKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCropCatalogEntries = `-- name: ListCropCatalogEntries :many
SELECT crop_key, display_name, supported, category, source, substrate, watering_style, runoff_pct_target, moisture_guidance, cousin_of, unsupported_reason, catalog_version, image_url, meta, created_at, updated_at
FROM gr33ncrops.crop_catalog_entries
ORDER BY supported DESC, display_name
`

func (q *Queries) ListCropCatalogEntries(ctx context.Context) ([]Gr33ncropsCropCatalogEntry, error) {
	rows, err := q.db.Query(ctx, listCropCatalogEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncropsCropCatalogEntry{}
	for rows.Next() {
		var i Gr33ncropsCropCatalogEntry
		if err := rows.Scan(
			&i.CropKey,
			&i.DisplayName,
			&i.Supported,
			&i.Category,
			&i.Source,
			&i.Substrate,
			&i.WateringStyle,
			&i.RunoffPctTarget,
			&i.MoistureGuidance,
			&i.CousinOf,
			&i.UnsupportedReason,
			&i.CatalogVersion,
			&i.ImageUrl,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
