// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
	"encoding/json"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"gr33n-api/internal/platform/commontypes"
)

const clearDevicePendingCommand = `-- name: ClearDevicePendingCommand :exec
UPDATE gr33ncore.devices
SET config = config - 'pending_command', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearDevicePendingCommand(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearDevicePendingCommand, id)
	return err
}

const countDevicesByStatusForFarm = `-- name: CountDevicesByStatusForFarm :many
SELECT status, COUNT(*)::bigint AS cnt
FROM gr33ncore.devices
WHERE farm_id = $1 AND deleted_at IS NULL
GROUP BY status
ORDER BY status ASC
`

type CountDevicesByStatusForFarmRow struct {
	Status commontypes.DeviceStatusEnum `db:"status" json:"status"`
	Cnt    int64                        `db:"cnt" json:"cnt"`
}

func (q *Queries) CountDevicesByStatusForFarm(ctx context.Context, farmID int64) ([]CountDevicesByStatusForFarmRow, error) {
	rows, err := q.db.Query(ctx, countDevicesByStatusForFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDevicesByStatusForFarmRow{}
	for rows.Next() {
		var i CountDevicesByStatusForFarmRow
		if err := rows.Scan(&i.Status, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDevice = `-- name: CreateDevice :one

INSERT INTO gr33ncore.devices (
    farm_id, zone_id, name, device_uid, device_type,
    ip_address, firmware_version, status, config, meta_data, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
RETURNING id, farm_id, zone_id, name, device_uid, device_type, ip_address, firmware_version, status, last_heartbeat, api_key, config, meta_data, config_version, created_at, updated_at, updated_by_user_id, deleted_at
`

type CreateDeviceParams struct {
	FarmID          int64                        `db:"farm_id" json:"farm_id"`
	ZoneID          *int64                       `db:"zone_id" json:"zone_id"`
	Name            string                       `db:"name" json:"name"`
	DeviceUid       *string                      `db:"device_uid" json:"device_uid"`
	DeviceType      string                       `db:"device_type" json:"device_type"`
	IpAddress       *netip.Addr                  `db:"ip_address" json:"ip_address"`
	FirmwareVersion *string                      `db:"firmware_version" json:"firmware_version"`
	Status          commontypes.DeviceStatusEnum `db:"status" json:"status"`
	Config          json.RawMessage              `db:"config" json:"config"`
	MetaData        json.RawMessage              `db:"meta_data" json:"meta_data"`
}

// ============================================================
// Queries: gr33ncore.devices
// ============================================================
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Gr33ncoreDevice, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.FarmID,
		arg.ZoneID,
		arg.Name,
		arg.DeviceUid,
		arg.DeviceType,
		arg.IpAddress,
		arg.FirmwareVersion,
		arg.Status,
		arg.Config,
		arg.MetaData,
	)
	var i Gr33ncoreDevice
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.DeviceUid,
		&i.DeviceType,
		&i.IpAddress,
		&i.FirmwareVersion,
		&i.Status,
		&i.LastHeartbeat,
		&i.ApiKey,
		&i.Config,
		&i.MetaData,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, farm_id, zone_id, name, device_uid, device_type, ip_address, firmware_version, status, last_heartbeat, api_key, config, meta_data, config_version, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.devices
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDeviceByID(ctx context.Context, id int64) (Gr33ncoreDevice, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Gr33ncoreDevice
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.DeviceUid,
		&i.DeviceType,
		&i.IpAddress,
		&i.FirmwareVersion,
		&i.Status,
		&i.LastHeartbeat,
		&i.ApiKey,
		&i.Config,
		&i.MetaData,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByUID = `-- name: GetDeviceByUID :one
SELECT id, farm_id, zone_id, name, device_uid, device_type, ip_address, firmware_version, status, last_heartbeat, api_key, config, meta_data, config_version, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.devices
WHERE device_uid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDeviceByUID(ctx context.Context, deviceUid *string) (Gr33ncoreDevice, error) {
	row := q.db.QueryRow(ctx, getDeviceByUID, deviceUid)
	var i Gr33ncoreDevice
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.DeviceUid,
		&i.DeviceType,
		&i.IpAddress,
		&i.FirmwareVersion,
		&i.Status,
		&i.LastHeartbeat,
		&i.ApiKey,
		&i.Config,
		&i.MetaData,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const listDevicesByFarm = `-- name: ListDevicesByFarm :many
SELECT id, farm_id, zone_id, name, device_uid, device_type, ip_address, firmware_version, status, last_heartbeat, api_key, config, meta_data, config_version, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.devices
WHERE farm_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListDevicesByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreDevice, error) {
	rows, err := q.db.Query(ctx, listDevicesByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreDevice{}
	for rows.Next() {
		var i Gr33ncoreDevice
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ZoneID,
			&i.Name,
			&i.DeviceUid,
			&i.DeviceType,
			&i.IpAddress,
			&i.FirmwareVersion,
			&i.Status,
			&i.LastHeartbeat,
			&i.ApiKey,
			&i.Config,
			&i.MetaData,
			&i.ConfigVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByZone = `-- name: ListDevicesByZone :many
SELECT id, farm_id, zone_id, name, device_uid, device_type, ip_address, firmware_version, status, last_heartbeat, api_key, config, meta_data, config_version, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.devices
WHERE zone_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListDevicesByZone(ctx context.Context, zoneID *int64) ([]Gr33ncoreDevice, error) {
	rows, err := q.db.Query(ctx, listDevicesByZone, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreDevice{}
	for rows.Next() {
		var i Gr33ncoreDevice
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ZoneID,
			&i.Name,
			&i.DeviceUid,
			&i.DeviceType,
			&i.IpAddress,
			&i.FirmwareVersion,
			&i.Status,
			&i.LastHeartbeat,
			&i.ApiKey,
			&i.Config,
			&i.MetaData,
			&i.ConfigVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleDevicesOffline = `-- name: MarkStaleDevicesOffline :many
UPDATE gr33ncore.devices
SET status = 'offline', updated_at = NOW()
WHERE status = 'online'
  AND deleted_at IS NULL
  AND (
    last_heartbeat IS NULL
    OR last_heartbeat < NOW() - ($1::bigint * INTERVAL '1 second')
  )
RETURNING id, farm_id, name, device_uid
`

type MarkStaleDevicesOfflineRow struct {
	ID        int64   `db:"id" json:"id"`
	FarmID    int64   `db:"farm_id" json:"farm_id"`
	Name      string  `db:"name" json:"name"`
	DeviceUid *string `db:"device_uid" json:"device_uid"`
}

func (q *Queries) MarkStaleDevicesOffline(ctx context.Context, dollar_1 int64) ([]MarkStaleDevicesOfflineRow, error) {
	rows, err := q.db.Query(ctx, markStaleDevicesOffline, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkStaleDevicesOfflineRow{}
	for rows.Next() {
		var i MarkStaleDevicesOfflineRow
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.Name,
			&i.DeviceUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDevicePendingCommand = `-- name: SetDevicePendingCommand :exec
UPDATE gr33ncore.devices
SET config = jsonb_set(
      coalesce(config, '{}'),
      '{pending_command}', $2::jsonb
    ), updated_at = NOW()
WHERE id = $1
`

type SetDevicePendingCommandParams struct {
	ID      int64           `db:"id" json:"id"`
	Column2 json.RawMessage `db:"column_2" json:"column_2"`
}

func (q *Queries) SetDevicePendingCommand(ctx context.Context, arg SetDevicePendingCommandParams) error {
	_, err := q.db.Exec(ctx, setDevicePendingCommand, arg.ID, arg.Column2)
	return err
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE gr33ncore.devices
SET deleted_at = NOW(), updated_at = NOW(), updated_by_user_id = $2
WHERE id = $1
`

type SoftDeleteDeviceParams struct {
	ID              int64       `db:"id" json:"id"`
	UpdatedByUserID pgtype.UUID `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) SoftDeleteDevice(ctx context.Context, arg SoftDeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, softDeleteDevice, arg.ID, arg.UpdatedByUserID)
	return err
}

const updateDeviceStatus = `-- name: UpdateDeviceStatus :one
UPDATE gr33ncore.devices
SET status = $2,
    last_heartbeat = NOW(),
    updated_at = NOW(),
    config = coalesce(config, '{}'::jsonb)
      || CASE WHEN $3::text IS NOT NULL AND $3::text <> ''
         THEN jsonb_build_object('last_config_fetch_at', $3::text) ELSE '{}'::jsonb END
      || CASE WHEN $4::text IS NOT NULL AND $4::text <> ''
         THEN jsonb_build_object('config_sha256', $4::text) ELSE '{}'::jsonb END
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, farm_id, zone_id, name, device_uid, device_type, ip_address, firmware_version, status, last_heartbeat, api_key, config, meta_data, config_version, created_at, updated_at, updated_by_user_id, deleted_at
`

type UpdateDeviceStatusParams struct {
	ID      int64                        `db:"id" json:"id"`
	Status  commontypes.DeviceStatusEnum `db:"status" json:"status"`
	Column3 string                       `db:"column_3" json:"column_3"`
	Column4 string                       `db:"column_4" json:"column_4"`
}

func (q *Queries) UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) (Gr33ncoreDevice, error) {
	row := q.db.QueryRow(ctx, updateDeviceStatus,
		arg.ID,
		arg.Status,
		arg.Column3,
		arg.Column4,
	)
	var i Gr33ncoreDevice
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.DeviceUid,
		&i.DeviceType,
		&i.IpAddress,
		&i.FirmwareVersion,
		&i.Status,
		&i.LastHeartbeat,
		&i.ApiKey,
		&i.Config,
		&i.MetaData,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const updateDeviceStatusTelemetry = `-- name: UpdateDeviceStatusTelemetry :one
UPDATE gr33ncore.devices
SET status = $2,
    last_heartbeat = NOW(),
    updated_at = NOW(),
    firmware_version = COALESCE(NULLIF($4::text, ''), firmware_version),
    config = coalesce(config, '{}'::jsonb)
      || CASE WHEN $3::text IS NOT NULL AND $3::text <> ''
         THEN jsonb_build_object('last_config_fetch_at', $3::text) ELSE '{}'::jsonb END
      || CASE WHEN $5::text IS NOT NULL AND $5::text <> ''
         THEN jsonb_build_object('client_version', $5::text) ELSE '{}'::jsonb END
      || CASE WHEN $6::bigint >= 0
         THEN jsonb_build_object('client_uptime_seconds', $6::bigint) ELSE '{}'::jsonb END
      || CASE WHEN $7::text IS NOT NULL AND $7::text <> ''
         THEN jsonb_build_object('config_sha256', $7::text) ELSE '{}'::jsonb END
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, farm_id, zone_id, name, device_uid, device_type, ip_address, firmware_version, status, last_heartbeat, api_key, config, meta_data, config_version, created_at, updated_at, updated_by_user_id, deleted_at
`

type UpdateDeviceStatusTelemetryParams struct {
	ID      int64                        `db:"id" json:"id"`
	Status  commontypes.DeviceStatusEnum `db:"status" json:"status"`
	Column3 string                       `db:"column_3" json:"column_3"`
	Column4 string                       `db:"column_4" json:"column_4"`
	Column5 string                       `db:"column_5" json:"column_5"`
	Column6 int64                        `db:"column_6" json:"column_6"`
	Column7 string                       `db:"column_7" json:"column_7"`
}

// Pi-key heartbeat: status + optional config fetch timestamp, firmware/client version, uptime.
func (q *Queries) UpdateDeviceStatusTelemetry(ctx context.Context, arg UpdateDeviceStatusTelemetryParams) (Gr33ncoreDevice, error) {
	row := q.db.QueryRow(ctx, updateDeviceStatusTelemetry,
		arg.ID,
		arg.Status,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var i Gr33ncoreDevice
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.DeviceUid,
		&i.DeviceType,
		&i.IpAddress,
		&i.FirmwareVersion,
		&i.Status,
		&i.LastHeartbeat,
		&i.ApiKey,
		&i.Config,
		&i.MetaData,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}
