// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: farms.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"gr33n-api/internal/platform/commontypes"
)

const createFarm = `-- name: CreateFarm :one

INSERT INTO gr33ncore.farms (
    name, description, location_text, size_hectares, farm_type,
    scale_tier, owner_user_id, timezone, currency, operational_status,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
RETURNING id, name, description, location_text, location_gis, size_hectares, farm_type, scale_tier, owner_user_id, timezone, currency, operational_status, created_at, updated_at, updated_by_user_id, deleted_at
`

type CreateFarmParams struct {
	Name              string                            `db:"name" json:"name"`
	Description       *string                           `db:"description" json:"description"`
	LocationText      *string                           `db:"location_text" json:"location_text"`
	SizeHectares      pgtype.Numeric                    `db:"size_hectares" json:"size_hectares"`
	FarmType          *string                           `db:"farm_type" json:"farm_type"`
	ScaleTier         commontypes.FarmScaleTierEnum     `db:"scale_tier" json:"scale_tier"`
	OwnerUserID       uuid.UUID                         `db:"owner_user_id" json:"owner_user_id"`
	Timezone          string                            `db:"timezone" json:"timezone"`
	Currency          string                            `db:"currency" json:"currency"`
	OperationalStatus commontypes.OperationalStatusEnum `db:"operational_status" json:"operational_status"`
}

// ============================================================
// Queries: gr33ncore.farms
// ============================================================
func (q *Queries) CreateFarm(ctx context.Context, arg CreateFarmParams) (Gr33ncoreFarm, error) {
	row := q.db.QueryRow(ctx, createFarm,
		arg.Name,
		arg.Description,
		arg.LocationText,
		arg.SizeHectares,
		arg.FarmType,
		arg.ScaleTier,
		arg.OwnerUserID,
		arg.Timezone,
		arg.Currency,
		arg.OperationalStatus,
	)
	var i Gr33ncoreFarm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LocationText,
		&i.LocationGis,
		&i.SizeHectares,
		&i.FarmType,
		&i.ScaleTier,
		&i.OwnerUserID,
		&i.Timezone,
		&i.Currency,
		&i.OperationalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const getFarmByID = `-- name: GetFarmByID :one
SELECT id, name, description, location_text, location_gis, size_hectares, farm_type, scale_tier, owner_user_id, timezone, currency, operational_status, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.farms
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFarmByID(ctx context.Context, id int64) (Gr33ncoreFarm, error) {
	row := q.db.QueryRow(ctx, getFarmByID, id)
	var i Gr33ncoreFarm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LocationText,
		&i.LocationGis,
		&i.SizeHectares,
		&i.FarmType,
		&i.ScaleTier,
		&i.OwnerUserID,
		&i.Timezone,
		&i.Currency,
		&i.OperationalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const listAllFarms = `-- name: ListAllFarms :many
SELECT id, name, description, location_text, location_gis, size_hectares, farm_type, scale_tier, owner_user_id, timezone, currency, operational_status, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.farms
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListAllFarms(ctx context.Context) ([]Gr33ncoreFarm, error) {
	rows, err := q.db.Query(ctx, listAllFarms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreFarm{}
	for rows.Next() {
		var i Gr33ncoreFarm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LocationText,
			&i.LocationGis,
			&i.SizeHectares,
			&i.FarmType,
			&i.ScaleTier,
			&i.OwnerUserID,
			&i.Timezone,
			&i.Currency,
			&i.OperationalStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFarmsByOwner = `-- name: ListFarmsByOwner :many
SELECT id, name, description, location_text, location_gis, size_hectares, farm_type, scale_tier, owner_user_id, timezone, currency, operational_status, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.farms
WHERE owner_user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListFarmsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Gr33ncoreFarm, error) {
	rows, err := q.db.Query(ctx, listFarmsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreFarm{}
	for rows.Next() {
		var i Gr33ncoreFarm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LocationText,
			&i.LocationGis,
			&i.SizeHectares,
			&i.FarmType,
			&i.ScaleTier,
			&i.OwnerUserID,
			&i.Timezone,
			&i.Currency,
			&i.OperationalStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFarmsForUser = `-- name: ListFarmsForUser :many
SELECT f.id, f.name, f.description, f.location_text, f.location_gis, f.size_hectares, f.farm_type, f.scale_tier, f.owner_user_id, f.timezone, f.currency, f.operational_status, f.created_at, f.updated_at, f.updated_by_user_id, f.deleted_at
FROM gr33ncore.farms f
JOIN gr33ncore.farm_memberships m ON m.farm_id = f.id
WHERE m.user_id = $1 AND f.deleted_at IS NULL
ORDER BY f.name ASC
`

func (q *Queries) ListFarmsForUser(ctx context.Context, userID uuid.UUID) ([]Gr33ncoreFarm, error) {
	rows, err := q.db.Query(ctx, listFarmsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreFarm{}
	for rows.Next() {
		var i Gr33ncoreFarm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LocationText,
			&i.LocationGis,
			&i.SizeHectares,
			&i.FarmType,
			&i.ScaleTier,
			&i.OwnerUserID,
			&i.Timezone,
			&i.Currency,
			&i.OperationalStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFarm = `-- name: SoftDeleteFarm :exec
UPDATE gr33ncore.farms
SET deleted_at = NOW(), updated_at = NOW(), updated_by_user_id = $2
WHERE id = $1
`

type SoftDeleteFarmParams struct {
	ID              int64       `db:"id" json:"id"`
	UpdatedByUserID pgtype.UUID `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) SoftDeleteFarm(ctx context.Context, arg SoftDeleteFarmParams) error {
	_, err := q.db.Exec(ctx, softDeleteFarm, arg.ID, arg.UpdatedByUserID)
	return err
}

const updateFarm = `-- name: UpdateFarm :one
UPDATE gr33ncore.farms
SET name = $2, description = $3, location_text = $4, size_hectares = $5,
    farm_type = $6, scale_tier = $7, timezone = $8, currency = $9,
    operational_status = $10, updated_by_user_id = $11, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, location_text, location_gis, size_hectares, farm_type, scale_tier, owner_user_id, timezone, currency, operational_status, created_at, updated_at, updated_by_user_id, deleted_at
`

type UpdateFarmParams struct {
	ID                int64                             `db:"id" json:"id"`
	Name              string                            `db:"name" json:"name"`
	Description       *string                           `db:"description" json:"description"`
	LocationText      *string                           `db:"location_text" json:"location_text"`
	SizeHectares      pgtype.Numeric                    `db:"size_hectares" json:"size_hectares"`
	FarmType          *string                           `db:"farm_type" json:"farm_type"`
	ScaleTier         commontypes.FarmScaleTierEnum     `db:"scale_tier" json:"scale_tier"`
	Timezone          string                            `db:"timezone" json:"timezone"`
	Currency          string                            `db:"currency" json:"currency"`
	OperationalStatus commontypes.OperationalStatusEnum `db:"operational_status" json:"operational_status"`
	UpdatedByUserID   pgtype.UUID                       `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) UpdateFarm(ctx context.Context, arg UpdateFarmParams) (Gr33ncoreFarm, error) {
	row := q.db.QueryRow(ctx, updateFarm,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LocationText,
		arg.SizeHectares,
		arg.FarmType,
		arg.ScaleTier,
		arg.Timezone,
		arg.Currency,
		arg.OperationalStatus,
		arg.UpdatedByUserID,
	)
	var i Gr33ncoreFarm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LocationText,
		&i.LocationGis,
		&i.SizeHectares,
		&i.FarmType,
		&i.ScaleTier,
		&i.OwnerUserID,
		&i.Timezone,
		&i.Currency,
		&i.OperationalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}
