// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: farm_active_modules.sql

package db

import (
	"context"
	"encoding/json"
)

const farmModuleIsEnabled = `-- name: FarmModuleIsEnabled :one
SELECT COALESCE(
  (SELECT is_enabled FROM gr33ncore.farm_active_modules
   WHERE farm_id = $1 AND module_schema_name = $2),
  FALSE
)::boolean AS is_enabled
`

type FarmModuleIsEnabledParams struct {
	FarmID           int64  `db:"farm_id" json:"farm_id"`
	ModuleSchemaName string `db:"module_schema_name" json:"module_schema_name"`
}

func (q *Queries) FarmModuleIsEnabled(ctx context.Context, arg FarmModuleIsEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, farmModuleIsEnabled, arg.FarmID, arg.ModuleSchemaName)
	var is_enabled bool
	err := row.Scan(&is_enabled)
	return is_enabled, err
}

const listFarmActiveModules = `-- name: ListFarmActiveModules :many

SELECT farm_id, module_schema_name, is_enabled, configuration, activated_at FROM gr33ncore.farm_active_modules
WHERE farm_id = $1
ORDER BY module_schema_name ASC
`

// ============================================================
// Queries: gr33ncore.farm_active_modules (Phase 115 WS1)
// ============================================================
func (q *Queries) ListFarmActiveModules(ctx context.Context, farmID int64) ([]Gr33ncoreFarmActiveModule, error) {
	rows, err := q.db.Query(ctx, listFarmActiveModules, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreFarmActiveModule{}
	for rows.Next() {
		var i Gr33ncoreFarmActiveModule
		if err := rows.Scan(
			&i.FarmID,
			&i.ModuleSchemaName,
			&i.IsEnabled,
			&i.Configuration,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedFarmActiveModule = `-- name: SeedFarmActiveModule :exec
INSERT INTO gr33ncore.farm_active_modules (farm_id, module_schema_name, is_enabled, configuration)
VALUES ($1, $2, $3, '{}'::jsonb)
ON CONFLICT (farm_id, module_schema_name) DO NOTHING
`

type SeedFarmActiveModuleParams struct {
	FarmID           int64  `db:"farm_id" json:"farm_id"`
	ModuleSchemaName string `db:"module_schema_name" json:"module_schema_name"`
	IsEnabled        bool   `db:"is_enabled" json:"is_enabled"`
}

func (q *Queries) SeedFarmActiveModule(ctx context.Context, arg SeedFarmActiveModuleParams) error {
	_, err := q.db.Exec(ctx, seedFarmActiveModule, arg.FarmID, arg.ModuleSchemaName, arg.IsEnabled)
	return err
}

const upsertFarmActiveModule = `-- name: UpsertFarmActiveModule :one
INSERT INTO gr33ncore.farm_active_modules (farm_id, module_schema_name, is_enabled, configuration)
VALUES ($1, $2, $3, coalesce($4::jsonb, '{}'::jsonb))
ON CONFLICT (farm_id, module_schema_name) DO UPDATE SET
  is_enabled = EXCLUDED.is_enabled,
  configuration = EXCLUDED.configuration,
  activated_at = CASE
    WHEN gr33ncore.farm_active_modules.is_enabled = FALSE AND EXCLUDED.is_enabled THEN NOW()
    ELSE gr33ncore.farm_active_modules.activated_at
  END
RETURNING farm_id, module_schema_name, is_enabled, configuration, activated_at
`

type UpsertFarmActiveModuleParams struct {
	FarmID           int64           `db:"farm_id" json:"farm_id"`
	ModuleSchemaName string          `db:"module_schema_name" json:"module_schema_name"`
	IsEnabled        bool            `db:"is_enabled" json:"is_enabled"`
	Column4          json.RawMessage `db:"column_4" json:"column_4"`
}

func (q *Queries) UpsertFarmActiveModule(ctx context.Context, arg UpsertFarmActiveModuleParams) (Gr33ncoreFarmActiveModule, error) {
	row := q.db.QueryRow(ctx, upsertFarmActiveModule,
		arg.FarmID,
		arg.ModuleSchemaName,
		arg.IsEnabled,
		arg.Column4,
	)
	var i Gr33ncoreFarmActiveModule
	err := row.Scan(
		&i.FarmID,
		&i.ModuleSchemaName,
		&i.IsEnabled,
		&i.Configuration,
		&i.ActivatedAt,
	)
	return i, err
}
