// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: farm_energy_prices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFarmEnergyPrice = `-- name: CreateFarmEnergyPrice :one
INSERT INTO gr33ncore.farm_energy_prices (
    farm_id, effective_from, effective_to, price_per_kwh, currency, notes
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, farm_id, effective_from, effective_to, price_per_kwh, currency, notes, created_at, updated_at
`

type CreateFarmEnergyPriceParams struct {
	FarmID        int64          `db:"farm_id" json:"farm_id"`
	EffectiveFrom pgtype.Date    `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Date    `db:"effective_to" json:"effective_to"`
	PricePerKwh   pgtype.Numeric `db:"price_per_kwh" json:"price_per_kwh"`
	Currency      string         `db:"currency" json:"currency"`
	Notes         *string        `db:"notes" json:"notes"`
}

func (q *Queries) CreateFarmEnergyPrice(ctx context.Context, arg CreateFarmEnergyPriceParams) (Gr33ncoreFarmEnergyPrice, error) {
	row := q.db.QueryRow(ctx, createFarmEnergyPrice,
		arg.FarmID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.PricePerKwh,
		arg.Currency,
		arg.Notes,
	)
	var i Gr33ncoreFarmEnergyPrice
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.PricePerKwh,
		&i.Currency,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFarmEnergyPrice = `-- name: DeleteFarmEnergyPrice :exec
DELETE FROM gr33ncore.farm_energy_prices WHERE id = $1
`

func (q *Queries) DeleteFarmEnergyPrice(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFarmEnergyPrice, id)
	return err
}

const getFarmEnergyPriceByID = `-- name: GetFarmEnergyPriceByID :one
SELECT id, farm_id, effective_from, effective_to, price_per_kwh, currency, notes, created_at, updated_at FROM gr33ncore.farm_energy_prices
WHERE id = $1
`

func (q *Queries) GetFarmEnergyPriceByID(ctx context.Context, id int64) (Gr33ncoreFarmEnergyPrice, error) {
	row := q.db.QueryRow(ctx, getFarmEnergyPriceByID, id)
	var i Gr33ncoreFarmEnergyPrice
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.PricePerKwh,
		&i.Currency,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFarmEnergyPrices = `-- name: ListFarmEnergyPrices :many

SELECT id, farm_id, effective_from, effective_to, price_per_kwh, currency, notes, created_at, updated_at FROM gr33ncore.farm_energy_prices
WHERE farm_id = $1
ORDER BY effective_from DESC, id DESC
`

// ============================================================
// Queries: gr33ncore.farm_energy_prices (Phase 20.95 WS2)
// ============================================================
func (q *Queries) ListFarmEnergyPrices(ctx context.Context, farmID int64) ([]Gr33ncoreFarmEnergyPrice, error) {
	rows, err := q.db.Query(ctx, listFarmEnergyPrices, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreFarmEnergyPrice{}
	for rows.Next() {
		var i Gr33ncoreFarmEnergyPrice
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.PricePerKwh,
			&i.Currency,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFarmEnergyPrice = `-- name: UpdateFarmEnergyPrice :one
UPDATE gr33ncore.farm_energy_prices
SET effective_from = $2,
    effective_to   = $3,
    price_per_kwh  = $4,
    currency       = $5,
    notes          = $6
WHERE id = $1
RETURNING id, farm_id, effective_from, effective_to, price_per_kwh, currency, notes, created_at, updated_at
`

type UpdateFarmEnergyPriceParams struct {
	ID            int64          `db:"id" json:"id"`
	EffectiveFrom pgtype.Date    `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Date    `db:"effective_to" json:"effective_to"`
	PricePerKwh   pgtype.Numeric `db:"price_per_kwh" json:"price_per_kwh"`
	Currency      string         `db:"currency" json:"currency"`
	Notes         *string        `db:"notes" json:"notes"`
}

func (q *Queries) UpdateFarmEnergyPrice(ctx context.Context, arg UpdateFarmEnergyPriceParams) (Gr33ncoreFarmEnergyPrice, error) {
	row := q.db.QueryRow(ctx, updateFarmEnergyPrice,
		arg.ID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.PricePerKwh,
		arg.Currency,
		arg.Notes,
	)
	var i Gr33ncoreFarmEnergyPrice
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.PricePerKwh,
		&i.Currency,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
