// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFileAttachment = `-- name: CreateFileAttachment :one

INSERT INTO gr33ncore.file_attachments (
    farm_id, related_module_schema, related_table_name, related_record_id,
    file_name, file_type, file_size_bytes, storage_path, mime_type, uploaded_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, farm_id, related_module_schema, related_table_name, related_record_id, file_name, file_type, file_size_bytes, storage_path, mime_type, description, uploaded_by_user_id, created_at, updated_at
`

type CreateFileAttachmentParams struct {
	FarmID              int64       `db:"farm_id" json:"farm_id"`
	RelatedModuleSchema string      `db:"related_module_schema" json:"related_module_schema"`
	RelatedTableName    string      `db:"related_table_name" json:"related_table_name"`
	RelatedRecordID     string      `db:"related_record_id" json:"related_record_id"`
	FileName            string      `db:"file_name" json:"file_name"`
	FileType            string      `db:"file_type" json:"file_type"`
	FileSizeBytes       *int64      `db:"file_size_bytes" json:"file_size_bytes"`
	StoragePath         string      `db:"storage_path" json:"storage_path"`
	MimeType            *string     `db:"mime_type" json:"mime_type"`
	UploadedByUserID    pgtype.UUID `db:"uploaded_by_user_id" json:"uploaded_by_user_id"`
}

// ============================================================
// Queries: gr33ncore.file_attachments
// ============================================================
func (q *Queries) CreateFileAttachment(ctx context.Context, arg CreateFileAttachmentParams) (Gr33ncoreFileAttachment, error) {
	row := q.db.QueryRow(ctx, createFileAttachment,
		arg.FarmID,
		arg.RelatedModuleSchema,
		arg.RelatedTableName,
		arg.RelatedRecordID,
		arg.FileName,
		arg.FileType,
		arg.FileSizeBytes,
		arg.StoragePath,
		arg.MimeType,
		arg.UploadedByUserID,
	)
	var i Gr33ncoreFileAttachment
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RelatedModuleSchema,
		&i.RelatedTableName,
		&i.RelatedRecordID,
		&i.FileName,
		&i.FileType,
		&i.FileSizeBytes,
		&i.StoragePath,
		&i.MimeType,
		&i.Description,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileAttachmentByID = `-- name: GetFileAttachmentByID :one
SELECT id, farm_id, related_module_schema, related_table_name, related_record_id, file_name, file_type, file_size_bytes, storage_path, mime_type, description, uploaded_by_user_id, created_at, updated_at FROM gr33ncore.file_attachments WHERE id = $1
`

func (q *Queries) GetFileAttachmentByID(ctx context.Context, id int64) (Gr33ncoreFileAttachment, error) {
	row := q.db.QueryRow(ctx, getFileAttachmentByID, id)
	var i Gr33ncoreFileAttachment
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.RelatedModuleSchema,
		&i.RelatedTableName,
		&i.RelatedRecordID,
		&i.FileName,
		&i.FileType,
		&i.FileSizeBytes,
		&i.StoragePath,
		&i.MimeType,
		&i.Description,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
