// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: genetics_profiles.sql

package db

import (
	"context"
)

const deleteCropProfileByID = `-- name: DeleteCropProfileByID :exec
DELETE FROM gr33ncrops.crop_profiles WHERE id = $1
`

func (q *Queries) DeleteCropProfileByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCropProfileByID, id)
	return err
}

const deleteGeneticsProfileLink = `-- name: DeleteGeneticsProfileLink :exec
DELETE FROM gr33ncrops.plant_genetics_profiles
WHERE farm_id = $1 AND crop_key = $2 AND variety_slug = $3
`

type DeleteGeneticsProfileLinkParams struct {
	FarmID      int64  `db:"farm_id" json:"farm_id"`
	CropKey     string `db:"crop_key" json:"crop_key"`
	VarietySlug string `db:"variety_slug" json:"variety_slug"`
}

func (q *Queries) DeleteGeneticsProfileLink(ctx context.Context, arg DeleteGeneticsProfileLinkParams) error {
	_, err := q.db.Exec(ctx, deleteGeneticsProfileLink, arg.FarmID, arg.CropKey, arg.VarietySlug)
	return err
}

const getGeneticsProfileLink = `-- name: GetGeneticsProfileLink :one
SELECT farm_id, crop_key, variety_slug, variety_label, crop_profile_id, created_at, updated_at
FROM gr33ncrops.plant_genetics_profiles
WHERE farm_id = $1 AND crop_key = $2 AND variety_slug = $3
`

type GetGeneticsProfileLinkParams struct {
	FarmID      int64  `db:"farm_id" json:"farm_id"`
	CropKey     string `db:"crop_key" json:"crop_key"`
	VarietySlug string `db:"variety_slug" json:"variety_slug"`
}

func (q *Queries) GetGeneticsProfileLink(ctx context.Context, arg GetGeneticsProfileLinkParams) (Gr33ncropsPlantGeneticsProfile, error) {
	row := q.db.QueryRow(ctx, getGeneticsProfileLink, arg.FarmID, arg.CropKey, arg.VarietySlug)
	var i Gr33ncropsPlantGeneticsProfile
	err := row.Scan(
		&i.FarmID,
		&i.CropKey,
		&i.VarietySlug,
		&i.VarietyLabel,
		&i.CropProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGeneticsProfileLink = `-- name: InsertGeneticsProfileLink :one
INSERT INTO gr33ncrops.plant_genetics_profiles (
    farm_id, crop_key, variety_slug, variety_label, crop_profile_id
) VALUES ($1, $2, $3, $4, $5)
RETURNING farm_id, crop_key, variety_slug, variety_label, crop_profile_id, created_at, updated_at
`

type InsertGeneticsProfileLinkParams struct {
	FarmID        int64  `db:"farm_id" json:"farm_id"`
	CropKey       string `db:"crop_key" json:"crop_key"`
	VarietySlug   string `db:"variety_slug" json:"variety_slug"`
	VarietyLabel  string `db:"variety_label" json:"variety_label"`
	CropProfileID int64  `db:"crop_profile_id" json:"crop_profile_id"`
}

func (q *Queries) InsertGeneticsProfileLink(ctx context.Context, arg InsertGeneticsProfileLinkParams) (Gr33ncropsPlantGeneticsProfile, error) {
	row := q.db.QueryRow(ctx, insertGeneticsProfileLink,
		arg.FarmID,
		arg.CropKey,
		arg.VarietySlug,
		arg.VarietyLabel,
		arg.CropProfileID,
	)
	var i Gr33ncropsPlantGeneticsProfile
	err := row.Scan(
		&i.FarmID,
		&i.CropKey,
		&i.VarietySlug,
		&i.VarietyLabel,
		&i.CropProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
