// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lighting_programs.sql

package db

import (
	"context"
	"encoding/json"
)

const createLightingProgram = `-- name: CreateLightingProgram :one
INSERT INTO gr33ncore.lighting_programs (
    farm_id, zone_id, actuator_id, name, description,
    on_hours, off_hours, lights_on_at, timezone,
    schedule_on_id, schedule_off_id, crop_cycle_id,
    is_active, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, farm_id, zone_id, actuator_id, name, description, on_hours, off_hours, lights_on_at, timezone, schedule_on_id, schedule_off_id, crop_cycle_id, is_active, metadata, created_at, updated_at
`

type CreateLightingProgramParams struct {
	FarmID        int64           `db:"farm_id" json:"farm_id"`
	ZoneID        int64           `db:"zone_id" json:"zone_id"`
	ActuatorID    int64           `db:"actuator_id" json:"actuator_id"`
	Name          string          `db:"name" json:"name"`
	Description   *string         `db:"description" json:"description"`
	OnHours       int32           `db:"on_hours" json:"on_hours"`
	OffHours      int32           `db:"off_hours" json:"off_hours"`
	LightsOnAt    string          `db:"lights_on_at" json:"lights_on_at"`
	Timezone      string          `db:"timezone" json:"timezone"`
	ScheduleOnID  *int64          `db:"schedule_on_id" json:"schedule_on_id"`
	ScheduleOffID *int64          `db:"schedule_off_id" json:"schedule_off_id"`
	CropCycleID   *int64          `db:"crop_cycle_id" json:"crop_cycle_id"`
	IsActive      bool            `db:"is_active" json:"is_active"`
	Metadata      json.RawMessage `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateLightingProgram(ctx context.Context, arg CreateLightingProgramParams) (Gr33ncoreLightingProgram, error) {
	row := q.db.QueryRow(ctx, createLightingProgram,
		arg.FarmID,
		arg.ZoneID,
		arg.ActuatorID,
		arg.Name,
		arg.Description,
		arg.OnHours,
		arg.OffHours,
		arg.LightsOnAt,
		arg.Timezone,
		arg.ScheduleOnID,
		arg.ScheduleOffID,
		arg.CropCycleID,
		arg.IsActive,
		arg.Metadata,
	)
	var i Gr33ncoreLightingProgram
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.ActuatorID,
		&i.Name,
		&i.Description,
		&i.OnHours,
		&i.OffHours,
		&i.LightsOnAt,
		&i.Timezone,
		&i.ScheduleOnID,
		&i.ScheduleOffID,
		&i.CropCycleID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLightingProgram = `-- name: DeleteLightingProgram :exec
DELETE FROM gr33ncore.lighting_programs WHERE id = $1
`

func (q *Queries) DeleteLightingProgram(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLightingProgram, id)
	return err
}

const getLightingProgramByID = `-- name: GetLightingProgramByID :one
SELECT id, farm_id, zone_id, actuator_id, name, description, on_hours, off_hours, lights_on_at, timezone, schedule_on_id, schedule_off_id, crop_cycle_id, is_active, metadata, created_at, updated_at FROM gr33ncore.lighting_programs
WHERE id = $1
`

func (q *Queries) GetLightingProgramByID(ctx context.Context, id int64) (Gr33ncoreLightingProgram, error) {
	row := q.db.QueryRow(ctx, getLightingProgramByID, id)
	var i Gr33ncoreLightingProgram
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.ActuatorID,
		&i.Name,
		&i.Description,
		&i.OnHours,
		&i.OffHours,
		&i.LightsOnAt,
		&i.Timezone,
		&i.ScheduleOnID,
		&i.ScheduleOffID,
		&i.CropCycleID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLightingProgramZoneBySchedule = `-- name: GetLightingProgramZoneBySchedule :one
SELECT zone_id
FROM gr33ncore.lighting_programs
WHERE farm_id = $1
  AND (schedule_on_id = $2 OR schedule_off_id = $2)
  AND zone_id IS NOT NULL
ORDER BY is_active DESC, id ASC
LIMIT 1
`

type GetLightingProgramZoneByScheduleParams struct {
	FarmID     int64  `db:"farm_id" json:"farm_id"`
	ScheduleID *int64 `db:"schedule_id" json:"schedule_id"`
}

// Phase 159 WS1 follow-up — schedule citation via lighting_program ON/OFF pair.
func (q *Queries) GetLightingProgramZoneBySchedule(ctx context.Context, arg GetLightingProgramZoneByScheduleParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLightingProgramZoneBySchedule, arg.FarmID, arg.ScheduleID)
	var zone_id int64
	err := row.Scan(&zone_id)
	return zone_id, err
}

const listLightingProgramsByFarm = `-- name: ListLightingProgramsByFarm :many

SELECT id, farm_id, zone_id, actuator_id, name, description, on_hours, off_hours, lights_on_at, timezone, schedule_on_id, schedule_off_id, crop_cycle_id, is_active, metadata, created_at, updated_at FROM gr33ncore.lighting_programs
WHERE farm_id = $1
ORDER BY name ASC
`

// ============================================================
// Queries: gr33ncore.lighting_programs (Phase 35)
// ============================================================
func (q *Queries) ListLightingProgramsByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreLightingProgram, error) {
	rows, err := q.db.Query(ctx, listLightingProgramsByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreLightingProgram{}
	for rows.Next() {
		var i Gr33ncoreLightingProgram
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ZoneID,
			&i.ActuatorID,
			&i.Name,
			&i.Description,
			&i.OnHours,
			&i.OffHours,
			&i.LightsOnAt,
			&i.Timezone,
			&i.ScheduleOnID,
			&i.ScheduleOffID,
			&i.CropCycleID,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLightingProgram = `-- name: UpdateLightingProgram :one
UPDATE gr33ncore.lighting_programs
SET name = $2, description = $3,
    on_hours = $4, off_hours = $5,
    lights_on_at = $6, timezone = $7,
    schedule_on_id = $8, schedule_off_id = $9,
    crop_cycle_id = $10, is_active = $11,
    metadata = $12, updated_at = NOW()
WHERE id = $1
RETURNING id, farm_id, zone_id, actuator_id, name, description, on_hours, off_hours, lights_on_at, timezone, schedule_on_id, schedule_off_id, crop_cycle_id, is_active, metadata, created_at, updated_at
`

type UpdateLightingProgramParams struct {
	ID            int64           `db:"id" json:"id"`
	Name          string          `db:"name" json:"name"`
	Description   *string         `db:"description" json:"description"`
	OnHours       int32           `db:"on_hours" json:"on_hours"`
	OffHours      int32           `db:"off_hours" json:"off_hours"`
	LightsOnAt    string          `db:"lights_on_at" json:"lights_on_at"`
	Timezone      string          `db:"timezone" json:"timezone"`
	ScheduleOnID  *int64          `db:"schedule_on_id" json:"schedule_on_id"`
	ScheduleOffID *int64          `db:"schedule_off_id" json:"schedule_off_id"`
	CropCycleID   *int64          `db:"crop_cycle_id" json:"crop_cycle_id"`
	IsActive      bool            `db:"is_active" json:"is_active"`
	Metadata      json.RawMessage `db:"metadata" json:"metadata"`
}

func (q *Queries) UpdateLightingProgram(ctx context.Context, arg UpdateLightingProgramParams) (Gr33ncoreLightingProgram, error) {
	row := q.db.QueryRow(ctx, updateLightingProgram,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OnHours,
		arg.OffHours,
		arg.LightsOnAt,
		arg.Timezone,
		arg.ScheduleOnID,
		arg.ScheduleOffID,
		arg.CropCycleID,
		arg.IsActive,
		arg.Metadata,
	)
	var i Gr33ncoreLightingProgram
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.ActuatorID,
		&i.Name,
		&i.Description,
		&i.OnHours,
		&i.OffHours,
		&i.LightsOnAt,
		&i.Timezone,
		&i.ScheduleOnID,
		&i.ScheduleOffID,
		&i.CropCycleID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLightingProgramActive = `-- name: UpdateLightingProgramActive :one
UPDATE gr33ncore.lighting_programs
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, farm_id, zone_id, actuator_id, name, description, on_hours, off_hours, lights_on_at, timezone, schedule_on_id, schedule_off_id, crop_cycle_id, is_active, metadata, created_at, updated_at
`

type UpdateLightingProgramActiveParams struct {
	ID       int64 `db:"id" json:"id"`
	IsActive bool  `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateLightingProgramActive(ctx context.Context, arg UpdateLightingProgramActiveParams) (Gr33ncoreLightingProgram, error) {
	row := q.db.QueryRow(ctx, updateLightingProgramActive, arg.ID, arg.IsActive)
	var i Gr33ncoreLightingProgram
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.ActuatorID,
		&i.Name,
		&i.Description,
		&i.OnHours,
		&i.OffHours,
		&i.LightsOnAt,
		&i.Timezone,
		&i.ScheduleOnID,
		&i.ScheduleOffID,
		&i.CropCycleID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLightingProgramSchedules = `-- name: UpdateLightingProgramSchedules :one
UPDATE gr33ncore.lighting_programs
SET schedule_on_id = $2, schedule_off_id = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, farm_id, zone_id, actuator_id, name, description, on_hours, off_hours, lights_on_at, timezone, schedule_on_id, schedule_off_id, crop_cycle_id, is_active, metadata, created_at, updated_at
`

type UpdateLightingProgramSchedulesParams struct {
	ID            int64  `db:"id" json:"id"`
	ScheduleOnID  *int64 `db:"schedule_on_id" json:"schedule_on_id"`
	ScheduleOffID *int64 `db:"schedule_off_id" json:"schedule_off_id"`
}

func (q *Queries) UpdateLightingProgramSchedules(ctx context.Context, arg UpdateLightingProgramSchedulesParams) (Gr33ncoreLightingProgram, error) {
	row := q.db.QueryRow(ctx, updateLightingProgramSchedules, arg.ID, arg.ScheduleOnID, arg.ScheduleOffID)
	var i Gr33ncoreLightingProgram
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.ActuatorID,
		&i.Name,
		&i.Description,
		&i.OnHours,
		&i.OffHours,
		&i.LightsOnAt,
		&i.Timezone,
		&i.ScheduleOnID,
		&i.ScheduleOffID,
		&i.CropCycleID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
