// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_templates.sql

package db

import (
	"context"
)

const createNotificationTemplate = `-- name: CreateNotificationTemplate :one
INSERT INTO gr33ncore.notification_templates (
  farm_id, template_key, description, subject_template, body_template_text,
  body_template_html, default_delivery_channels, default_priority, is_system_template
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, FALSE)
RETURNING id, farm_id, template_key, description, subject_template, body_template_text, body_template_html, default_delivery_channels, default_priority, is_system_template, created_at, updated_at
`

type CreateNotificationTemplateParams struct {
	FarmID                  *int64                             `db:"farm_id" json:"farm_id"`
	TemplateKey             string                             `db:"template_key" json:"template_key"`
	Description             *string                            `db:"description" json:"description"`
	SubjectTemplate         *string                            `db:"subject_template" json:"subject_template"`
	BodyTemplateText        *string                            `db:"body_template_text" json:"body_template_text"`
	BodyTemplateHtml        *string                            `db:"body_template_html" json:"body_template_html"`
	DefaultDeliveryChannels []string                           `db:"default_delivery_channels" json:"default_delivery_channels"`
	DefaultPriority         *Gr33ncoreNotificationPriorityEnum `db:"default_priority" json:"default_priority"`
}

func (q *Queries) CreateNotificationTemplate(ctx context.Context, arg CreateNotificationTemplateParams) (Gr33ncoreNotificationTemplate, error) {
	row := q.db.QueryRow(ctx, createNotificationTemplate,
		arg.FarmID,
		arg.TemplateKey,
		arg.Description,
		arg.SubjectTemplate,
		arg.BodyTemplateText,
		arg.BodyTemplateHtml,
		arg.DefaultDeliveryChannels,
		arg.DefaultPriority,
	)
	var i Gr33ncoreNotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TemplateKey,
		&i.Description,
		&i.SubjectTemplate,
		&i.BodyTemplateText,
		&i.BodyTemplateHtml,
		&i.DefaultDeliveryChannels,
		&i.DefaultPriority,
		&i.IsSystemTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationTemplatesByFarm = `-- name: ListNotificationTemplatesByFarm :many

SELECT id, farm_id, template_key, description, subject_template, body_template_text, body_template_html, default_delivery_channels, default_priority, is_system_template, created_at, updated_at FROM gr33ncore.notification_templates
WHERE farm_id = $1 OR farm_id IS NULL
ORDER BY farm_id NULLS FIRST, template_key ASC
`

// ============================================================
// Queries: gr33ncore.notification_templates (Phase 115 WS2)
// ============================================================
func (q *Queries) ListNotificationTemplatesByFarm(ctx context.Context, farmID *int64) ([]Gr33ncoreNotificationTemplate, error) {
	rows, err := q.db.Query(ctx, listNotificationTemplatesByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreNotificationTemplate{}
	for rows.Next() {
		var i Gr33ncoreNotificationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.TemplateKey,
			&i.Description,
			&i.SubjectTemplate,
			&i.BodyTemplateText,
			&i.BodyTemplateHtml,
			&i.DefaultDeliveryChannels,
			&i.DefaultPriority,
			&i.IsSystemTemplate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationTemplate = `-- name: UpdateNotificationTemplate :one
UPDATE gr33ncore.notification_templates
SET template_key = COALESCE(NULLIF($2::text, ''), template_key),
    description = COALESCE($3, description),
    subject_template = COALESCE($4, subject_template),
    body_template_text = COALESCE($5, body_template_text),
    body_template_html = COALESCE($6, body_template_html),
    default_delivery_channels = COALESCE($7, default_delivery_channels),
    default_priority = COALESCE($8, default_priority),
    updated_at = NOW()
WHERE id = $1 AND farm_id = $9 AND is_system_template = FALSE
RETURNING id, farm_id, template_key, description, subject_template, body_template_text, body_template_html, default_delivery_channels, default_priority, is_system_template, created_at, updated_at
`

type UpdateNotificationTemplateParams struct {
	ID                      int64                              `db:"id" json:"id"`
	Column2                 string                             `db:"column_2" json:"column_2"`
	Description             *string                            `db:"description" json:"description"`
	SubjectTemplate         *string                            `db:"subject_template" json:"subject_template"`
	BodyTemplateText        *string                            `db:"body_template_text" json:"body_template_text"`
	BodyTemplateHtml        *string                            `db:"body_template_html" json:"body_template_html"`
	DefaultDeliveryChannels []string                           `db:"default_delivery_channels" json:"default_delivery_channels"`
	DefaultPriority         *Gr33ncoreNotificationPriorityEnum `db:"default_priority" json:"default_priority"`
	FarmID                  *int64                             `db:"farm_id" json:"farm_id"`
}

func (q *Queries) UpdateNotificationTemplate(ctx context.Context, arg UpdateNotificationTemplateParams) (Gr33ncoreNotificationTemplate, error) {
	row := q.db.QueryRow(ctx, updateNotificationTemplate,
		arg.ID,
		arg.Column2,
		arg.Description,
		arg.SubjectTemplate,
		arg.BodyTemplateText,
		arg.BodyTemplateHtml,
		arg.DefaultDeliveryChannels,
		arg.DefaultPriority,
		arg.FarmID,
	)
	var i Gr33ncoreNotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TemplateKey,
		&i.Description,
		&i.SubjectTemplate,
		&i.BodyTemplateText,
		&i.BodyTemplateHtml,
		&i.DefaultDeliveryChannels,
		&i.DefaultPriority,
		&i.IsSystemTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
