// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plants.sql

package db

import (
	"context"
)

const createPlant = `-- name: CreatePlant :one
INSERT INTO gr33ncrops.plants (farm_id, display_name, variety_or_cultivar, meta)
VALUES ($1, $2, $3, $4) RETURNING id, farm_id, display_name, variety_or_cultivar, meta, created_at, updated_at, deleted_at
`

type CreatePlantParams struct {
	FarmID            int64   `db:"farm_id" json:"farm_id"`
	DisplayName       string  `db:"display_name" json:"display_name"`
	VarietyOrCultivar *string `db:"variety_or_cultivar" json:"variety_or_cultivar"`
	Meta              []byte  `db:"meta" json:"meta"`
}

func (q *Queries) CreatePlant(ctx context.Context, arg CreatePlantParams) (Gr33ncropsPlant, error) {
	row := q.db.QueryRow(ctx, createPlant,
		arg.FarmID,
		arg.DisplayName,
		arg.VarietyOrCultivar,
		arg.Meta,
	)
	var i Gr33ncropsPlant
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.DisplayName,
		&i.VarietyOrCultivar,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlant = `-- name: GetPlant :one
SELECT id, farm_id, display_name, variety_or_cultivar, meta, created_at, updated_at, deleted_at FROM gr33ncrops.plants WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPlant(ctx context.Context, id int64) (Gr33ncropsPlant, error) {
	row := q.db.QueryRow(ctx, getPlant, id)
	var i Gr33ncropsPlant
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.DisplayName,
		&i.VarietyOrCultivar,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPlantsByFarm = `-- name: ListPlantsByFarm :many
SELECT id, farm_id, display_name, variety_or_cultivar, meta, created_at, updated_at, deleted_at FROM gr33ncrops.plants
WHERE farm_id = $1 AND deleted_at IS NULL
ORDER BY display_name
`

func (q *Queries) ListPlantsByFarm(ctx context.Context, farmID int64) ([]Gr33ncropsPlant, error) {
	rows, err := q.db.Query(ctx, listPlantsByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncropsPlant{}
	for rows.Next() {
		var i Gr33ncropsPlant
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.DisplayName,
			&i.VarietyOrCultivar,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlant = `-- name: SoftDeletePlant :exec
UPDATE gr33ncrops.plants SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeletePlant(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeletePlant, id)
	return err
}

const updatePlant = `-- name: UpdatePlant :one
UPDATE gr33ncrops.plants
SET display_name = $2, variety_or_cultivar = $3, meta = $4, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL RETURNING id, farm_id, display_name, variety_or_cultivar, meta, created_at, updated_at, deleted_at
`

type UpdatePlantParams struct {
	ID                int64   `db:"id" json:"id"`
	DisplayName       string  `db:"display_name" json:"display_name"`
	VarietyOrCultivar *string `db:"variety_or_cultivar" json:"variety_or_cultivar"`
	Meta              []byte  `db:"meta" json:"meta"`
}

func (q *Queries) UpdatePlant(ctx context.Context, arg UpdatePlantParams) (Gr33ncropsPlant, error) {
	row := q.db.QueryRow(ctx, updatePlant,
		arg.ID,
		arg.DisplayName,
		arg.VarietyOrCultivar,
		arg.Meta,
	)
	var i Gr33ncropsPlant
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.DisplayName,
		&i.VarietyOrCultivar,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
