// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"gr33n-api/internal/platform/commontypes"
)

const addFarmMember = `-- name: AddFarmMember :one
INSERT INTO gr33ncore.farm_memberships (farm_id, user_id, role_in_farm, permissions, joined_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING farm_id, user_id, role_in_farm, permissions, joined_at
`

type AddFarmMemberParams struct {
	FarmID      int64                          `db:"farm_id" json:"farm_id"`
	UserID      uuid.UUID                      `db:"user_id" json:"user_id"`
	RoleInFarm  commontypes.FarmMemberRoleEnum `db:"role_in_farm" json:"role_in_farm"`
	Permissions []byte                         `db:"permissions" json:"permissions"`
}

func (q *Queries) AddFarmMember(ctx context.Context, arg AddFarmMemberParams) (Gr33ncoreFarmMembership, error) {
	row := q.db.QueryRow(ctx, addFarmMember,
		arg.FarmID,
		arg.UserID,
		arg.RoleInFarm,
		arg.Permissions,
	)
	var i Gr33ncoreFarmMembership
	err := row.Scan(
		&i.FarmID,
		&i.UserID,
		&i.RoleInFarm,
		&i.Permissions,
		&i.JoinedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO gr33ncore.profiles (user_id, full_name, email, avatar_url, role, preferences, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING user_id, full_name, email, avatar_url, role, preferences, created_at, updated_at
`

type CreateProfileParams struct {
	UserID      uuid.UUID                `db:"user_id" json:"user_id"`
	FullName    *string                  `db:"full_name" json:"full_name"`
	Email       string                   `db:"email" json:"email"`
	AvatarUrl   *string                  `db:"avatar_url" json:"avatar_url"`
	Role        commontypes.UserRoleEnum `db:"role" json:"role"`
	Preferences []byte                   `db:"preferences" json:"preferences"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Gr33ncoreProfile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.FullName,
		arg.Email,
		arg.AvatarUrl,
		arg.Role,
		arg.Preferences,
	)
	var i Gr33ncoreProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFarmMembers = `-- name: GetFarmMembers :many
SELECT p.user_id, p.full_name, p.email, p.avatar_url, m.role_in_farm, m.permissions, m.joined_at
FROM gr33ncore.farm_memberships m
JOIN gr33ncore.profiles p ON p.user_id = m.user_id
WHERE m.farm_id = $1
ORDER BY m.joined_at ASC
`

type GetFarmMembersRow struct {
	UserID      uuid.UUID                      `db:"user_id" json:"user_id"`
	FullName    *string                        `db:"full_name" json:"full_name"`
	Email       string                         `db:"email" json:"email"`
	AvatarUrl   *string                        `db:"avatar_url" json:"avatar_url"`
	RoleInFarm  commontypes.FarmMemberRoleEnum `db:"role_in_farm" json:"role_in_farm"`
	Permissions []byte                         `db:"permissions" json:"permissions"`
	JoinedAt    time.Time                      `db:"joined_at" json:"joined_at"`
}

func (q *Queries) GetFarmMembers(ctx context.Context, farmID int64) ([]GetFarmMembersRow, error) {
	rows, err := q.db.Query(ctx, getFarmMembers, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFarmMembersRow{}
	for rows.Next() {
		var i GetFarmMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.AvatarUrl,
			&i.RoleInFarm,
			&i.Permissions,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFarmMembership = `-- name: GetFarmMembership :one
SELECT farm_id, user_id, role_in_farm, permissions, joined_at
FROM gr33ncore.farm_memberships
WHERE farm_id = $1 AND user_id = $2
`

type GetFarmMembershipParams struct {
	FarmID int64     `db:"farm_id" json:"farm_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetFarmMembership(ctx context.Context, arg GetFarmMembershipParams) (Gr33ncoreFarmMembership, error) {
	row := q.db.QueryRow(ctx, getFarmMembership, arg.FarmID, arg.UserID)
	var i Gr33ncoreFarmMembership
	err := row.Scan(
		&i.FarmID,
		&i.UserID,
		&i.RoleInFarm,
		&i.Permissions,
		&i.JoinedAt,
	)
	return i, err
}

const getProfileByEmail = `-- name: GetProfileByEmail :one
SELECT user_id, full_name, email, avatar_url, role, preferences, created_at, updated_at
FROM gr33ncore.profiles
WHERE email = $1
`

func (q *Queries) GetProfileByEmail(ctx context.Context, email string) (Gr33ncoreProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByEmail, email)
	var i Gr33ncoreProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one

SELECT user_id, full_name, email, avatar_url, role, preferences, created_at, updated_at
FROM gr33ncore.profiles
WHERE user_id = $1
`

// ============================================================
// Queries: gr33ncore.profiles
// ============================================================
func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Gr33ncoreProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Gr33ncoreProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeFarmMember = `-- name: RemoveFarmMember :exec
DELETE FROM gr33ncore.farm_memberships
WHERE farm_id = $1 AND user_id = $2
`

type RemoveFarmMemberParams struct {
	FarmID int64     `db:"farm_id" json:"farm_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveFarmMember(ctx context.Context, arg RemoveFarmMemberParams) error {
	_, err := q.db.Exec(ctx, removeFarmMember, arg.FarmID, arg.UserID)
	return err
}

const updateFarmMemberRole = `-- name: UpdateFarmMemberRole :one
UPDATE gr33ncore.farm_memberships
SET role_in_farm = $3
WHERE farm_id = $1 AND user_id = $2
RETURNING farm_id, user_id, role_in_farm, permissions, joined_at
`

type UpdateFarmMemberRoleParams struct {
	FarmID     int64                          `db:"farm_id" json:"farm_id"`
	UserID     uuid.UUID                      `db:"user_id" json:"user_id"`
	RoleInFarm commontypes.FarmMemberRoleEnum `db:"role_in_farm" json:"role_in_farm"`
}

func (q *Queries) UpdateFarmMemberRole(ctx context.Context, arg UpdateFarmMemberRoleParams) (Gr33ncoreFarmMembership, error) {
	row := q.db.QueryRow(ctx, updateFarmMemberRole, arg.FarmID, arg.UserID, arg.RoleInFarm)
	var i Gr33ncoreFarmMembership
	err := row.Scan(
		&i.FarmID,
		&i.UserID,
		&i.RoleInFarm,
		&i.Permissions,
		&i.JoinedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE gr33ncore.profiles
SET full_name = $2, avatar_url = $3, role = $4, preferences = $5, updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, full_name, email, avatar_url, role, preferences, created_at, updated_at
`

type UpdateProfileParams struct {
	UserID      uuid.UUID                `db:"user_id" json:"user_id"`
	FullName    *string                  `db:"full_name" json:"full_name"`
	AvatarUrl   *string                  `db:"avatar_url" json:"avatar_url"`
	Role        commontypes.UserRoleEnum `db:"role" json:"role"`
	Preferences []byte                   `db:"preferences" json:"preferences"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Gr33ncoreProfile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.UserID,
		arg.FullName,
		arg.AvatarUrl,
		arg.Role,
		arg.Preferences,
	)
	var i Gr33ncoreProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
