// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddFarmMember(ctx context.Context, arg AddFarmMemberParams) (Gr33ncoreFarmMembership, error)
	AddRecipeComponent(ctx context.Context, arg AddRecipeComponentParams) error
	ClearDevicePendingCommand(ctx context.Context, id int64) error
	CountUnreadAlertsByFarm(ctx context.Context, farmID int64) (int64, error)
	// ============================================================
	// Queries: gr33ncore.actuators + actuator_events
	// ============================================================
	CreateActuator(ctx context.Context, arg CreateActuatorParams) (Gr33ncoreActuator, error)
	// ============================================================
	// Queries: gr33ncore.alerts_notifications
	// ============================================================
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Gr33ncoreAlertsNotification, error)
	CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error)
	CreateAutomationRun(ctx context.Context, arg CreateAutomationRunParams) (Gr33ncoreAutomationRun, error)
	// ============================================================
	// Queries: gr33ncore.cost_transactions
	// ============================================================
	CreateCostTransaction(ctx context.Context, arg CreateCostTransactionParams) (Gr33ncoreCostTransaction, error)
	// ============================================================
	// Queries: gr33nfertigation.crop_cycles
	// ============================================================
	CreateCropCycle(ctx context.Context, arg CreateCropCycleParams) (Gr33nfertigationCropCycle, error)
	// ============================================================
	// Queries: gr33ncore.devices
	// ============================================================
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Gr33ncoreDevice, error)
	CreateEcTarget(ctx context.Context, arg CreateEcTargetParams) (Gr33nfertigationEcTarget, error)
	// ============================================================
	// Queries: gr33ncore.farms
	// ============================================================
	CreateFarm(ctx context.Context, arg CreateFarmParams) (Gr33ncoreFarm, error)
	CreateFertigationEvent(ctx context.Context, arg CreateFertigationEventParams) (Gr33nfertigationFertigationEvent, error)
	// ============================================================
	// Queries: gr33ncore.file_attachments
	// ============================================================
	CreateFileAttachment(ctx context.Context, arg CreateFileAttachmentParams) (Gr33ncoreFileAttachment, error)
	CreateInputBatch(ctx context.Context, arg CreateInputBatchParams) (Gr33nnaturalfarmingInputBatch, error)
	CreateInputDefinition(ctx context.Context, arg CreateInputDefinitionParams) (Gr33nnaturalfarmingInputDefinition, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Gr33ncoreProfile, error)
	CreateProgram(ctx context.Context, arg CreateProgramParams) (Gr33nfertigationProgram, error)
	// ============================================================
	// Queries: gr33nnaturalfarming.application_recipes & recipe_input_components
	// ============================================================
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Gr33nnaturalfarmingApplicationRecipe, error)
	CreateReservoir(ctx context.Context, arg CreateReservoirParams) (Gr33nfertigationReservoir, error)
	// ============================================================
	// Queries: gr33ncore.sensors
	// ============================================================
	CreateSensor(ctx context.Context, arg CreateSensorParams) (Gr33ncoreSensor, error)
	// ============================================================
	// Queries: gr33ncore.tasks
	// ============================================================
	CreateTask(ctx context.Context, arg CreateTaskParams) (Gr33ncoreTask, error)
	// ============================================================
	// Queries: gr33ncore.zones
	// ============================================================
	CreateZone(ctx context.Context, arg CreateZoneParams) (Gr33ncoreZone, error)
	DeleteCostTransaction(ctx context.Context, id int64) error
	DeleteProgram(ctx context.Context, id int64) error
	DeleteReservoir(ctx context.Context, id int64) error
	GetActuatorByID(ctx context.Context, id int64) (Gr33ncoreActuator, error)
	GetAlertNotificationByID(ctx context.Context, id int64) (Gr33ncoreAlertsNotification, error)
	// ============================================================
	// Queries: auth.users
	// ============================================================
	GetAuthUserByEmail(ctx context.Context, email *string) (AuthUser, error)
	GetAutomationRunByDetails(ctx context.Context, arg GetAutomationRunByDetailsParams) (Gr33ncoreAutomationRun, error)
	GetBaseUnitForType(ctx context.Context, unitType string) (Gr33ncoreUnit, error)
	GetCostSummaryByFarm(ctx context.Context, farmID int64) (GetCostSummaryByFarmRow, error)
	GetCostTransactionByID(ctx context.Context, id int64) (Gr33ncoreCostTransaction, error)
	GetCropCycleByID(ctx context.Context, id int64) (Gr33nfertigationCropCycle, error)
	GetDeviceByID(ctx context.Context, id int64) (Gr33ncoreDevice, error)
	GetDeviceByUID(ctx context.Context, deviceUid *string) (Gr33ncoreDevice, error)
	GetFarmByID(ctx context.Context, id int64) (Gr33ncoreFarm, error)
	GetFarmMembers(ctx context.Context, farmID int64) ([]GetFarmMembersRow, error)
	GetFarmMembership(ctx context.Context, arg GetFarmMembershipParams) (Gr33ncoreFarmMembership, error)
	GetFertigationProgramByID(ctx context.Context, id int64) (Gr33nfertigationProgram, error)
	GetFertigationReservoirByID(ctx context.Context, id int64) (Gr33nfertigationReservoir, error)
	GetFileAttachmentByID(ctx context.Context, id int64) (Gr33ncoreFileAttachment, error)
	GetInputBatchByID(ctx context.Context, id int64) (Gr33nnaturalfarmingInputBatch, error)
	// ============================================================
	// Queries: gr33nnaturalfarming
	// ============================================================
	GetInputDefinitionByID(ctx context.Context, id int64) (Gr33nnaturalfarmingInputDefinition, error)
	GetLastSuccessfulRunBySchedule(ctx context.Context, scheduleID *int64) (Gr33ncoreAutomationRun, error)
	GetLatestReadingBySensor(ctx context.Context, sensorID int64) (Gr33ncoreSensorReading, error)
	GetProfileByEmail(ctx context.Context, email string) (Gr33ncoreProfile, error)
	// ============================================================
	// Queries: gr33ncore.profiles
	// ============================================================
	GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Gr33ncoreProfile, error)
	GetRecentUnacknowledgedAlertForSource(ctx context.Context, arg GetRecentUnacknowledgedAlertForSourceParams) (int64, error)
	GetRecipeByID(ctx context.Context, id int64) (Gr33nnaturalfarmingApplicationRecipe, error)
	GetScheduleByID(ctx context.Context, id int64) (Gr33ncoreSchedule, error)
	GetSensorByID(ctx context.Context, id int64) (Gr33ncoreSensor, error)
	GetSensorReadingStats(ctx context.Context, arg GetSensorReadingStatsParams) (GetSensorReadingStatsRow, error)
	GetTaskByID(ctx context.Context, id int64) (Gr33ncoreTask, error)
	// ============================================================
	// Queries: gr33ncore.units
	// ============================================================
	GetUnitByID(ctx context.Context, id int64) (Gr33ncoreUnit, error)
	GetUnitByName(ctx context.Context, name string) (Gr33ncoreUnit, error)
	GetZoneByID(ctx context.Context, id int64) (Gr33ncoreZone, error)
	InsertActuatorEvent(ctx context.Context, arg InsertActuatorEventParams) (Gr33ncoreActuatorEvent, error)
	// ============================================================
	// Queries: gr33ncore.sensor_readings (TimescaleDB hypertable)
	// ============================================================
	InsertSensorReading(ctx context.Context, arg InsertSensorReadingParams) (Gr33ncoreSensorReading, error)
	ListActiveSchedules(ctx context.Context) ([]Gr33ncoreSchedule, error)
	ListActuatorEventsByActuator(ctx context.Context, arg ListActuatorEventsByActuatorParams) ([]Gr33ncoreActuatorEvent, error)
	ListActuatorEventsBySchedule(ctx context.Context, arg ListActuatorEventsByScheduleParams) ([]Gr33ncoreActuatorEvent, error)
	ListActuatorsByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreActuator, error)
	ListAlertsByFarm(ctx context.Context, arg ListAlertsByFarmParams) ([]Gr33ncoreAlertsNotification, error)
	ListAlertsByRecipient(ctx context.Context, arg ListAlertsByRecipientParams) ([]Gr33ncoreAlertsNotification, error)
	ListAllFarms(ctx context.Context) ([]Gr33ncoreFarm, error)
	ListAllUnits(ctx context.Context) ([]Gr33ncoreUnit, error)
	ListAutomationRunsByFarm(ctx context.Context, arg ListAutomationRunsByFarmParams) ([]Gr33ncoreAutomationRun, error)
	ListCostTransactionsByFarm(ctx context.Context, arg ListCostTransactionsByFarmParams) ([]Gr33ncoreCostTransaction, error)
	ListCostTransactionsByFarmExport(ctx context.Context, farmID int64) ([]ListCostTransactionsByFarmExportRow, error)
	ListCropCyclesByFarm(ctx context.Context, farmID int64) ([]Gr33nfertigationCropCycle, error)
	ListDevicesByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreDevice, error)
	ListDevicesByZone(ctx context.Context, zoneID *int64) ([]Gr33ncoreDevice, error)
	ListEcTargetsByFarm(ctx context.Context, farmID int64) ([]Gr33nfertigationEcTarget, error)
	ListExecutableActionsBySchedule(ctx context.Context, scheduleID *int64) ([]Gr33ncoreExecutableAction, error)
	ListFarmsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Gr33ncoreFarm, error)
	ListFarmsForUser(ctx context.Context, userID uuid.UUID) ([]Gr33ncoreFarm, error)
	ListFertigationEventsByFarm(ctx context.Context, farmID int64) ([]Gr33nfertigationFertigationEvent, error)
	ListFertigationEventsByFarmAndCropCycle(ctx context.Context, arg ListFertigationEventsByFarmAndCropCycleParams) ([]Gr33nfertigationFertigationEvent, error)
	ListInputBatchesByFarm(ctx context.Context, farmID int64) ([]Gr33nnaturalfarmingInputBatch, error)
	ListInputDefinitionsByFarm(ctx context.Context, farmID int64) ([]Gr33nnaturalfarmingInputDefinition, error)
	ListLatestReadingsByFarm(ctx context.Context, farmID int64) ([]ListLatestReadingsByFarmRow, error)
	ListProgramsByFarm(ctx context.Context, farmID int64) ([]Gr33nfertigationProgram, error)
	ListReadingsBySensorAndTimeRange(ctx context.Context, arg ListReadingsBySensorAndTimeRangeParams) ([]Gr33ncoreSensorReading, error)
	ListRecipeComponents(ctx context.Context, applicationRecipeID int64) ([]ListRecipeComponentsRow, error)
	ListRecipesByFarm(ctx context.Context, farmID int64) ([]Gr33nnaturalfarmingApplicationRecipe, error)
	// ============================================================
	// Queries: gr33nfertigation core resources
	// ============================================================
	ListReservoirsByFarm(ctx context.Context, farmID int64) ([]Gr33nfertigationReservoir, error)
	// ============================================================
	// Queries: schedules, executable actions, automation runs
	// ============================================================
	ListSchedulesByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreSchedule, error)
	ListSensorsByDevice(ctx context.Context, deviceID *int64) ([]Gr33ncoreSensor, error)
	ListSensorsByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreSensor, error)
	ListSensorsByZone(ctx context.Context, zoneID *int64) ([]Gr33ncoreSensor, error)
	ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]Gr33ncoreTask, error)
	ListTasksByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreTask, error)
	ListUnitsByType(ctx context.Context, unitType string) ([]Gr33ncoreUnit, error)
	ListZonesByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreZone, error)
	ListZonesByParent(ctx context.Context, parentZoneID *int64) ([]Gr33ncoreZone, error)
	MarkAlertAcknowledged(ctx context.Context, arg MarkAlertAcknowledgedParams) (Gr33ncoreAlertsNotification, error)
	MarkAlertRead(ctx context.Context, id int64) (Gr33ncoreAlertsNotification, error)
	MarkScheduleTriggered(ctx context.Context, arg MarkScheduleTriggeredParams) (Gr33ncoreSchedule, error)
	RemoveFarmMember(ctx context.Context, arg RemoveFarmMemberParams) error
	RemoveRecipeComponent(ctx context.Context, arg RemoveRecipeComponentParams) error
	SetDevicePendingCommand(ctx context.Context, arg SetDevicePendingCommandParams) error
	SetFarmInsertCommonsOptIn(ctx context.Context, arg SetFarmInsertCommonsOptInParams) (Gr33ncoreFarm, error)
	SoftDeleteCropCycle(ctx context.Context, id int64) error
	SoftDeleteDevice(ctx context.Context, arg SoftDeleteDeviceParams) error
	SoftDeleteFarm(ctx context.Context, arg SoftDeleteFarmParams) error
	SoftDeleteInputBatch(ctx context.Context, arg SoftDeleteInputBatchParams) error
	SoftDeleteInputDefinition(ctx context.Context, arg SoftDeleteInputDefinitionParams) error
	SoftDeleteRecipe(ctx context.Context, id int64) error
	SoftDeleteSensor(ctx context.Context, arg SoftDeleteSensorParams) error
	SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error
	SoftDeleteZone(ctx context.Context, arg SoftDeleteZoneParams) error
	TouchFarmInsertCommonsSync(ctx context.Context, id int64) (Gr33ncoreFarm, error)
	UpdateActuatorState(ctx context.Context, arg UpdateActuatorStateParams) (Gr33ncoreActuator, error)
	UpdateAuthUserPasswordHash(ctx context.Context, arg UpdateAuthUserPasswordHashParams) error
	UpdateCostTransaction(ctx context.Context, arg UpdateCostTransactionParams) (Gr33ncoreCostTransaction, error)
	UpdateCropCycle(ctx context.Context, arg UpdateCropCycleParams) (Gr33nfertigationCropCycle, error)
	UpdateCropCycleStage(ctx context.Context, arg UpdateCropCycleStageParams) (Gr33nfertigationCropCycle, error)
	UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) (Gr33ncoreDevice, error)
	UpdateFarm(ctx context.Context, arg UpdateFarmParams) (Gr33ncoreFarm, error)
	UpdateFarmMemberRole(ctx context.Context, arg UpdateFarmMemberRoleParams) (Gr33ncoreFarmMembership, error)
	UpdateInputBatch(ctx context.Context, arg UpdateInputBatchParams) (Gr33nnaturalfarmingInputBatch, error)
	UpdateInputDefinition(ctx context.Context, arg UpdateInputDefinitionParams) (Gr33nnaturalfarmingInputDefinition, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Gr33ncoreProfile, error)
	UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Gr33nfertigationProgram, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Gr33nnaturalfarmingApplicationRecipe, error)
	UpdateReservoir(ctx context.Context, arg UpdateReservoirParams) (Gr33nfertigationReservoir, error)
	UpdateScheduleActive(ctx context.Context, arg UpdateScheduleActiveParams) (Gr33ncoreSchedule, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Gr33ncoreTask, error)
	UpdateZone(ctx context.Context, arg UpdateZoneParams) (Gr33ncoreZone, error)
	UserHasFarmAccess(ctx context.Context, arg UserHasFarmAccessParams) (*bool, error)
}

var _ Querier = (*Queries)(nil)
