// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRecipeComponent = `-- name: AddRecipeComponent :exec
INSERT INTO gr33nnaturalfarming.recipe_input_components (
    application_recipe_id, input_definition_id, part_value, part_unit_id, notes
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (application_recipe_id, input_definition_id) DO UPDATE SET
    part_value = EXCLUDED.part_value,
    part_unit_id = EXCLUDED.part_unit_id,
    notes = EXCLUDED.notes
`

type AddRecipeComponentParams struct {
	ApplicationRecipeID int64          `db:"application_recipe_id" json:"application_recipe_id"`
	InputDefinitionID   int64          `db:"input_definition_id" json:"input_definition_id"`
	PartValue           pgtype.Numeric `db:"part_value" json:"part_value"`
	PartUnitID          *int64         `db:"part_unit_id" json:"part_unit_id"`
	Notes               *string        `db:"notes" json:"notes"`
}

func (q *Queries) AddRecipeComponent(ctx context.Context, arg AddRecipeComponentParams) error {
	_, err := q.db.Exec(ctx, addRecipeComponent,
		arg.ApplicationRecipeID,
		arg.InputDefinitionID,
		arg.PartValue,
		arg.PartUnitID,
		arg.Notes,
	)
	return err
}

const createRecipe = `-- name: CreateRecipe :one

INSERT INTO gr33nnaturalfarming.application_recipes (
    farm_id, name, input_definition_id, description,
    target_application_type, dilution_ratio, instructions,
    frequency_guidelines, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, farm_id, name, input_definition_id, description, target_application_type, dilution_ratio, components, instructions, frequency_guidelines, target_crop_categories, target_growth_stages, notes, created_at, updated_at, updated_by_user_id, deleted_at
`

type CreateRecipeParams struct {
	FarmID                int64                                    `db:"farm_id" json:"farm_id"`
	Name                  string                                   `db:"name" json:"name"`
	InputDefinitionID     *int64                                   `db:"input_definition_id" json:"input_definition_id"`
	Description           *string                                  `db:"description" json:"description"`
	TargetApplicationType Gr33nnaturalfarmingApplicationTargetEnum `db:"target_application_type" json:"target_application_type"`
	DilutionRatio         *string                                  `db:"dilution_ratio" json:"dilution_ratio"`
	Instructions          *string                                  `db:"instructions" json:"instructions"`
	FrequencyGuidelines   *string                                  `db:"frequency_guidelines" json:"frequency_guidelines"`
	Notes                 *string                                  `db:"notes" json:"notes"`
}

// ============================================================
// Queries: gr33nnaturalfarming.application_recipes & recipe_input_components
// ============================================================
func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Gr33nnaturalfarmingApplicationRecipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.FarmID,
		arg.Name,
		arg.InputDefinitionID,
		arg.Description,
		arg.TargetApplicationType,
		arg.DilutionRatio,
		arg.Instructions,
		arg.FrequencyGuidelines,
		arg.Notes,
	)
	var i Gr33nnaturalfarmingApplicationRecipe
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Name,
		&i.InputDefinitionID,
		&i.Description,
		&i.TargetApplicationType,
		&i.DilutionRatio,
		&i.Components,
		&i.Instructions,
		&i.FrequencyGuidelines,
		&i.TargetCropCategories,
		&i.TargetGrowthStages,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, farm_id, name, input_definition_id, description, target_application_type, dilution_ratio, components, instructions, frequency_guidelines, target_crop_categories, target_growth_stages, notes, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33nnaturalfarming.application_recipes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRecipeByID(ctx context.Context, id int64) (Gr33nnaturalfarmingApplicationRecipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, id)
	var i Gr33nnaturalfarmingApplicationRecipe
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Name,
		&i.InputDefinitionID,
		&i.Description,
		&i.TargetApplicationType,
		&i.DilutionRatio,
		&i.Components,
		&i.Instructions,
		&i.FrequencyGuidelines,
		&i.TargetCropCategories,
		&i.TargetGrowthStages,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const listRecipeComponents = `-- name: ListRecipeComponents :many
SELECT
    c.application_recipe_id,
    c.input_definition_id,
    c.part_value,
    c.part_unit_id,
    c.notes,
    d.name AS input_name
FROM gr33nnaturalfarming.recipe_input_components c
JOIN gr33nnaturalfarming.input_definitions d ON d.id = c.input_definition_id
WHERE c.application_recipe_id = $1
ORDER BY d.name ASC
`

type ListRecipeComponentsRow struct {
	ApplicationRecipeID int64          `db:"application_recipe_id" json:"application_recipe_id"`
	InputDefinitionID   int64          `db:"input_definition_id" json:"input_definition_id"`
	PartValue           pgtype.Numeric `db:"part_value" json:"part_value"`
	PartUnitID          *int64         `db:"part_unit_id" json:"part_unit_id"`
	Notes               *string        `db:"notes" json:"notes"`
	InputName           string         `db:"input_name" json:"input_name"`
}

func (q *Queries) ListRecipeComponents(ctx context.Context, applicationRecipeID int64) ([]ListRecipeComponentsRow, error) {
	rows, err := q.db.Query(ctx, listRecipeComponents, applicationRecipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipeComponentsRow{}
	for rows.Next() {
		var i ListRecipeComponentsRow
		if err := rows.Scan(
			&i.ApplicationRecipeID,
			&i.InputDefinitionID,
			&i.PartValue,
			&i.PartUnitID,
			&i.Notes,
			&i.InputName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByFarm = `-- name: ListRecipesByFarm :many
SELECT id, farm_id, name, input_definition_id, description, target_application_type, dilution_ratio, components, instructions, frequency_guidelines, target_crop_categories, target_growth_stages, notes, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33nnaturalfarming.application_recipes
WHERE farm_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListRecipesByFarm(ctx context.Context, farmID int64) ([]Gr33nnaturalfarmingApplicationRecipe, error) {
	rows, err := q.db.Query(ctx, listRecipesByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33nnaturalfarmingApplicationRecipe{}
	for rows.Next() {
		var i Gr33nnaturalfarmingApplicationRecipe
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.Name,
			&i.InputDefinitionID,
			&i.Description,
			&i.TargetApplicationType,
			&i.DilutionRatio,
			&i.Components,
			&i.Instructions,
			&i.FrequencyGuidelines,
			&i.TargetCropCategories,
			&i.TargetGrowthStages,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRecipeComponent = `-- name: RemoveRecipeComponent :exec
DELETE FROM gr33nnaturalfarming.recipe_input_components
WHERE application_recipe_id = $1 AND input_definition_id = $2
`

type RemoveRecipeComponentParams struct {
	ApplicationRecipeID int64 `db:"application_recipe_id" json:"application_recipe_id"`
	InputDefinitionID   int64 `db:"input_definition_id" json:"input_definition_id"`
}

func (q *Queries) RemoveRecipeComponent(ctx context.Context, arg RemoveRecipeComponentParams) error {
	_, err := q.db.Exec(ctx, removeRecipeComponent, arg.ApplicationRecipeID, arg.InputDefinitionID)
	return err
}

const softDeleteRecipe = `-- name: SoftDeleteRecipe :exec
UPDATE gr33nnaturalfarming.application_recipes
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteRecipe(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteRecipe, id)
	return err
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE gr33nnaturalfarming.application_recipes SET
    name = $2,
    input_definition_id = $3,
    description = $4,
    target_application_type = $5,
    dilution_ratio = $6,
    instructions = $7,
    frequency_guidelines = $8,
    notes = $9,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, farm_id, name, input_definition_id, description, target_application_type, dilution_ratio, components, instructions, frequency_guidelines, target_crop_categories, target_growth_stages, notes, created_at, updated_at, updated_by_user_id, deleted_at
`

type UpdateRecipeParams struct {
	ID                    int64                                    `db:"id" json:"id"`
	Name                  string                                   `db:"name" json:"name"`
	InputDefinitionID     *int64                                   `db:"input_definition_id" json:"input_definition_id"`
	Description           *string                                  `db:"description" json:"description"`
	TargetApplicationType Gr33nnaturalfarmingApplicationTargetEnum `db:"target_application_type" json:"target_application_type"`
	DilutionRatio         *string                                  `db:"dilution_ratio" json:"dilution_ratio"`
	Instructions          *string                                  `db:"instructions" json:"instructions"`
	FrequencyGuidelines   *string                                  `db:"frequency_guidelines" json:"frequency_guidelines"`
	Notes                 *string                                  `db:"notes" json:"notes"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Gr33nnaturalfarmingApplicationRecipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.ID,
		arg.Name,
		arg.InputDefinitionID,
		arg.Description,
		arg.TargetApplicationType,
		arg.DilutionRatio,
		arg.Instructions,
		arg.FrequencyGuidelines,
		arg.Notes,
	)
	var i Gr33nnaturalfarmingApplicationRecipe
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.Name,
		&i.InputDefinitionID,
		&i.Description,
		&i.TargetApplicationType,
		&i.DilutionRatio,
		&i.Components,
		&i.Instructions,
		&i.FrequencyGuidelines,
		&i.TargetCropCategories,
		&i.TargetGrowthStages,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}
