// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sensors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSensor = `-- name: CreateSensor :one

INSERT INTO gr33ncore.sensors (
    device_id, farm_id, zone_id, name, sensor_type, unit_id,
    hardware_identifier, value_min_expected, value_max_expected,
    alert_threshold_low, alert_threshold_high, reading_interval_seconds,
    config, meta_data, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW(), NOW())
RETURNING id, device_id, farm_id, zone_id, name, sensor_type, unit_id, hardware_identifier, value_min_expected, value_max_expected, alert_threshold_low, alert_threshold_high, reading_interval_seconds, is_calibrated, last_calibration_date, calibration_data, config, meta_data, created_at, updated_at, updated_by_user_id, deleted_at
`

type CreateSensorParams struct {
	DeviceID               *int64         `db:"device_id" json:"device_id"`
	FarmID                 int64          `db:"farm_id" json:"farm_id"`
	ZoneID                 *int64         `db:"zone_id" json:"zone_id"`
	Name                   string         `db:"name" json:"name"`
	SensorType             string         `db:"sensor_type" json:"sensor_type"`
	UnitID                 int64          `db:"unit_id" json:"unit_id"`
	HardwareIdentifier     *string        `db:"hardware_identifier" json:"hardware_identifier"`
	ValueMinExpected       pgtype.Numeric `db:"value_min_expected" json:"value_min_expected"`
	ValueMaxExpected       pgtype.Numeric `db:"value_max_expected" json:"value_max_expected"`
	AlertThresholdLow      pgtype.Numeric `db:"alert_threshold_low" json:"alert_threshold_low"`
	AlertThresholdHigh     pgtype.Numeric `db:"alert_threshold_high" json:"alert_threshold_high"`
	ReadingIntervalSeconds *int32         `db:"reading_interval_seconds" json:"reading_interval_seconds"`
	Config                 []byte         `db:"config" json:"config"`
	MetaData               []byte         `db:"meta_data" json:"meta_data"`
}

// ============================================================
// Queries: gr33ncore.sensors
// ============================================================
func (q *Queries) CreateSensor(ctx context.Context, arg CreateSensorParams) (Gr33ncoreSensor, error) {
	row := q.db.QueryRow(ctx, createSensor,
		arg.DeviceID,
		arg.FarmID,
		arg.ZoneID,
		arg.Name,
		arg.SensorType,
		arg.UnitID,
		arg.HardwareIdentifier,
		arg.ValueMinExpected,
		arg.ValueMaxExpected,
		arg.AlertThresholdLow,
		arg.AlertThresholdHigh,
		arg.ReadingIntervalSeconds,
		arg.Config,
		arg.MetaData,
	)
	var i Gr33ncoreSensor
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.SensorType,
		&i.UnitID,
		&i.HardwareIdentifier,
		&i.ValueMinExpected,
		&i.ValueMaxExpected,
		&i.AlertThresholdLow,
		&i.AlertThresholdHigh,
		&i.ReadingIntervalSeconds,
		&i.IsCalibrated,
		&i.LastCalibrationDate,
		&i.CalibrationData,
		&i.Config,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const getSensorByID = `-- name: GetSensorByID :one
SELECT id, device_id, farm_id, zone_id, name, sensor_type, unit_id, hardware_identifier, value_min_expected, value_max_expected, alert_threshold_low, alert_threshold_high, reading_interval_seconds, is_calibrated, last_calibration_date, calibration_data, config, meta_data, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.sensors
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSensorByID(ctx context.Context, id int64) (Gr33ncoreSensor, error) {
	row := q.db.QueryRow(ctx, getSensorByID, id)
	var i Gr33ncoreSensor
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FarmID,
		&i.ZoneID,
		&i.Name,
		&i.SensorType,
		&i.UnitID,
		&i.HardwareIdentifier,
		&i.ValueMinExpected,
		&i.ValueMaxExpected,
		&i.AlertThresholdLow,
		&i.AlertThresholdHigh,
		&i.ReadingIntervalSeconds,
		&i.IsCalibrated,
		&i.LastCalibrationDate,
		&i.CalibrationData,
		&i.Config,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const listSensorsByDevice = `-- name: ListSensorsByDevice :many
SELECT id, device_id, farm_id, zone_id, name, sensor_type, unit_id, hardware_identifier, value_min_expected, value_max_expected, alert_threshold_low, alert_threshold_high, reading_interval_seconds, is_calibrated, last_calibration_date, calibration_data, config, meta_data, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.sensors
WHERE device_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListSensorsByDevice(ctx context.Context, deviceID *int64) ([]Gr33ncoreSensor, error) {
	rows, err := q.db.Query(ctx, listSensorsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreSensor{}
	for rows.Next() {
		var i Gr33ncoreSensor
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.FarmID,
			&i.ZoneID,
			&i.Name,
			&i.SensorType,
			&i.UnitID,
			&i.HardwareIdentifier,
			&i.ValueMinExpected,
			&i.ValueMaxExpected,
			&i.AlertThresholdLow,
			&i.AlertThresholdHigh,
			&i.ReadingIntervalSeconds,
			&i.IsCalibrated,
			&i.LastCalibrationDate,
			&i.CalibrationData,
			&i.Config,
			&i.MetaData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSensorsByFarm = `-- name: ListSensorsByFarm :many
SELECT id, device_id, farm_id, zone_id, name, sensor_type, unit_id, hardware_identifier, value_min_expected, value_max_expected, alert_threshold_low, alert_threshold_high, reading_interval_seconds, is_calibrated, last_calibration_date, calibration_data, config, meta_data, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.sensors
WHERE farm_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListSensorsByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreSensor, error) {
	rows, err := q.db.Query(ctx, listSensorsByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreSensor{}
	for rows.Next() {
		var i Gr33ncoreSensor
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.FarmID,
			&i.ZoneID,
			&i.Name,
			&i.SensorType,
			&i.UnitID,
			&i.HardwareIdentifier,
			&i.ValueMinExpected,
			&i.ValueMaxExpected,
			&i.AlertThresholdLow,
			&i.AlertThresholdHigh,
			&i.ReadingIntervalSeconds,
			&i.IsCalibrated,
			&i.LastCalibrationDate,
			&i.CalibrationData,
			&i.Config,
			&i.MetaData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSensorsByZone = `-- name: ListSensorsByZone :many
SELECT id, device_id, farm_id, zone_id, name, sensor_type, unit_id, hardware_identifier, value_min_expected, value_max_expected, alert_threshold_low, alert_threshold_high, reading_interval_seconds, is_calibrated, last_calibration_date, calibration_data, config, meta_data, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.sensors
WHERE zone_id = $1 AND deleted_at IS NULL
ORDER BY sensor_type, name ASC
`

func (q *Queries) ListSensorsByZone(ctx context.Context, zoneID *int64) ([]Gr33ncoreSensor, error) {
	rows, err := q.db.Query(ctx, listSensorsByZone, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreSensor{}
	for rows.Next() {
		var i Gr33ncoreSensor
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.FarmID,
			&i.ZoneID,
			&i.Name,
			&i.SensorType,
			&i.UnitID,
			&i.HardwareIdentifier,
			&i.ValueMinExpected,
			&i.ValueMaxExpected,
			&i.AlertThresholdLow,
			&i.AlertThresholdHigh,
			&i.ReadingIntervalSeconds,
			&i.IsCalibrated,
			&i.LastCalibrationDate,
			&i.CalibrationData,
			&i.Config,
			&i.MetaData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSensor = `-- name: SoftDeleteSensor :exec
UPDATE gr33ncore.sensors
SET deleted_at = NOW(), updated_at = NOW(), updated_by_user_id = $2
WHERE id = $1
`

type SoftDeleteSensorParams struct {
	ID              int64       `db:"id" json:"id"`
	UpdatedByUserID pgtype.UUID `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) SoftDeleteSensor(ctx context.Context, arg SoftDeleteSensorParams) error {
	_, err := q.db.Exec(ctx, softDeleteSensor, arg.ID, arg.UpdatedByUserID)
	return err
}
