// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sensor_readings.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestReadingBySensor = `-- name: GetLatestReadingBySensor :one
SELECT reading_time, sensor_id, value_raw, value_normalized, normalized_unit_id, value_text, value_json, battery_level_percent, signal_strength_dbm, is_valid, meta_data FROM gr33ncore.sensor_readings
WHERE sensor_id = $1
ORDER BY reading_time DESC
LIMIT 1
`

func (q *Queries) GetLatestReadingBySensor(ctx context.Context, sensorID int64) (Gr33ncoreSensorReading, error) {
	row := q.db.QueryRow(ctx, getLatestReadingBySensor, sensorID)
	var i Gr33ncoreSensorReading
	err := row.Scan(
		&i.ReadingTime,
		&i.SensorID,
		&i.ValueRaw,
		&i.ValueNormalized,
		&i.NormalizedUnitID,
		&i.ValueText,
		&i.ValueJson,
		&i.BatteryLevelPercent,
		&i.SignalStrengthDbm,
		&i.IsValid,
		&i.MetaData,
	)
	return i, err
}

const getSensorReadingStats = `-- name: GetSensorReadingStats :one
SELECT
    COUNT(*)           AS total_readings,
    AVG(value_raw)     AS avg_value,
    MIN(value_raw)     AS min_value,
    MAX(value_raw)     AS max_value,
    MIN(reading_time)  AS first_reading,
    MAX(reading_time)  AS last_reading
FROM gr33ncore.sensor_readings
WHERE sensor_id = $1
  AND reading_time >= $2
  AND reading_time <= $3
`

type GetSensorReadingStatsParams struct {
	SensorID      int64     `db:"sensor_id" json:"sensor_id"`
	ReadingTime   time.Time `db:"reading_time" json:"reading_time"`
	ReadingTime_2 time.Time `db:"reading_time_2" json:"reading_time_2"`
}

type GetSensorReadingStatsRow struct {
	TotalReadings int64       `db:"total_readings" json:"total_readings"`
	AvgValue      float64     `db:"avg_value" json:"avg_value"`
	MinValue      interface{} `db:"min_value" json:"min_value"`
	MaxValue      interface{} `db:"max_value" json:"max_value"`
	FirstReading  interface{} `db:"first_reading" json:"first_reading"`
	LastReading   interface{} `db:"last_reading" json:"last_reading"`
}

func (q *Queries) GetSensorReadingStats(ctx context.Context, arg GetSensorReadingStatsParams) (GetSensorReadingStatsRow, error) {
	row := q.db.QueryRow(ctx, getSensorReadingStats, arg.SensorID, arg.ReadingTime, arg.ReadingTime_2)
	var i GetSensorReadingStatsRow
	err := row.Scan(
		&i.TotalReadings,
		&i.AvgValue,
		&i.MinValue,
		&i.MaxValue,
		&i.FirstReading,
		&i.LastReading,
	)
	return i, err
}

const insertSensorReading = `-- name: InsertSensorReading :one

INSERT INTO gr33ncore.sensor_readings (
    reading_time, sensor_id, value_raw, value_text, value_json,
    battery_level_percent, signal_strength_dbm, is_valid, meta_data
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING reading_time, sensor_id, value_raw, value_normalized, normalized_unit_id, value_text, value_json, battery_level_percent, signal_strength_dbm, is_valid, meta_data
`

type InsertSensorReadingParams struct {
	ReadingTime         time.Time      `db:"reading_time" json:"reading_time"`
	SensorID            int64          `db:"sensor_id" json:"sensor_id"`
	ValueRaw            pgtype.Numeric `db:"value_raw" json:"value_raw"`
	ValueText           *string        `db:"value_text" json:"value_text"`
	ValueJson           []byte         `db:"value_json" json:"value_json"`
	BatteryLevelPercent pgtype.Numeric `db:"battery_level_percent" json:"battery_level_percent"`
	SignalStrengthDbm   *int32         `db:"signal_strength_dbm" json:"signal_strength_dbm"`
	IsValid             *bool          `db:"is_valid" json:"is_valid"`
	MetaData            []byte         `db:"meta_data" json:"meta_data"`
}

// ============================================================
// Queries: gr33ncore.sensor_readings (TimescaleDB hypertable)
// ============================================================
func (q *Queries) InsertSensorReading(ctx context.Context, arg InsertSensorReadingParams) (Gr33ncoreSensorReading, error) {
	row := q.db.QueryRow(ctx, insertSensorReading,
		arg.ReadingTime,
		arg.SensorID,
		arg.ValueRaw,
		arg.ValueText,
		arg.ValueJson,
		arg.BatteryLevelPercent,
		arg.SignalStrengthDbm,
		arg.IsValid,
		arg.MetaData,
	)
	var i Gr33ncoreSensorReading
	err := row.Scan(
		&i.ReadingTime,
		&i.SensorID,
		&i.ValueRaw,
		&i.ValueNormalized,
		&i.NormalizedUnitID,
		&i.ValueText,
		&i.ValueJson,
		&i.BatteryLevelPercent,
		&i.SignalStrengthDbm,
		&i.IsValid,
		&i.MetaData,
	)
	return i, err
}

const listLatestReadingsByFarm = `-- name: ListLatestReadingsByFarm :many
SELECT DISTINCT ON (s.id)
    sr.reading_time, sr.sensor_id, sr.value_raw, sr.value_normalized,
    sr.normalized_unit_id, sr.is_valid, s.name as sensor_name,
    s.sensor_type, s.zone_id
FROM gr33ncore.sensor_readings sr
JOIN gr33ncore.sensors s ON s.id = sr.sensor_id
WHERE s.farm_id = $1 AND s.deleted_at IS NULL
ORDER BY s.id, sr.reading_time DESC
`

type ListLatestReadingsByFarmRow struct {
	ReadingTime      time.Time      `db:"reading_time" json:"reading_time"`
	SensorID         int64          `db:"sensor_id" json:"sensor_id"`
	ValueRaw         pgtype.Numeric `db:"value_raw" json:"value_raw"`
	ValueNormalized  pgtype.Numeric `db:"value_normalized" json:"value_normalized"`
	NormalizedUnitID *int64         `db:"normalized_unit_id" json:"normalized_unit_id"`
	IsValid          *bool          `db:"is_valid" json:"is_valid"`
	SensorName       string         `db:"sensor_name" json:"sensor_name"`
	SensorType       string         `db:"sensor_type" json:"sensor_type"`
	ZoneID           *int64         `db:"zone_id" json:"zone_id"`
}

func (q *Queries) ListLatestReadingsByFarm(ctx context.Context, farmID int64) ([]ListLatestReadingsByFarmRow, error) {
	rows, err := q.db.Query(ctx, listLatestReadingsByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestReadingsByFarmRow{}
	for rows.Next() {
		var i ListLatestReadingsByFarmRow
		if err := rows.Scan(
			&i.ReadingTime,
			&i.SensorID,
			&i.ValueRaw,
			&i.ValueNormalized,
			&i.NormalizedUnitID,
			&i.IsValid,
			&i.SensorName,
			&i.SensorType,
			&i.ZoneID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingsBySensorAndTimeRange = `-- name: ListReadingsBySensorAndTimeRange :many
SELECT reading_time, sensor_id, value_raw, value_normalized, normalized_unit_id, value_text, value_json, battery_level_percent, signal_strength_dbm, is_valid, meta_data FROM gr33ncore.sensor_readings
WHERE sensor_id = $1
  AND reading_time >= $2
  AND reading_time <= $3
ORDER BY reading_time DESC
`

type ListReadingsBySensorAndTimeRangeParams struct {
	SensorID      int64     `db:"sensor_id" json:"sensor_id"`
	ReadingTime   time.Time `db:"reading_time" json:"reading_time"`
	ReadingTime_2 time.Time `db:"reading_time_2" json:"reading_time_2"`
}

func (q *Queries) ListReadingsBySensorAndTimeRange(ctx context.Context, arg ListReadingsBySensorAndTimeRangeParams) ([]Gr33ncoreSensorReading, error) {
	rows, err := q.db.Query(ctx, listReadingsBySensorAndTimeRange, arg.SensorID, arg.ReadingTime, arg.ReadingTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreSensorReading{}
	for rows.Next() {
		var i Gr33ncoreSensorReading
		if err := rows.Scan(
			&i.ReadingTime,
			&i.SensorID,
			&i.ValueRaw,
			&i.ValueNormalized,
			&i.NormalizedUnitID,
			&i.ValueText,
			&i.ValueJson,
			&i.BatteryLevelPercent,
			&i.SignalStrengthDbm,
			&i.IsValid,
			&i.MetaData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
