// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_input_consumptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskInputConsumption = `-- name: CreateTaskInputConsumption :one
INSERT INTO gr33ncore.task_input_consumptions (
    farm_id, task_id, input_batch_id, quantity, unit_id, notes,
    recorded_by, cost_transaction_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, farm_id, task_id, input_batch_id, quantity, unit_id, notes, recorded_at, recorded_by, cost_transaction_id, created_at, updated_at
`

type CreateTaskInputConsumptionParams struct {
	FarmID            int64          `db:"farm_id" json:"farm_id"`
	TaskID            int64          `db:"task_id" json:"task_id"`
	InputBatchID      int64          `db:"input_batch_id" json:"input_batch_id"`
	Quantity          pgtype.Numeric `db:"quantity" json:"quantity"`
	UnitID            int64          `db:"unit_id" json:"unit_id"`
	Notes             *string        `db:"notes" json:"notes"`
	RecordedBy        pgtype.UUID    `db:"recorded_by" json:"recorded_by"`
	CostTransactionID *int64         `db:"cost_transaction_id" json:"cost_transaction_id"`
}

func (q *Queries) CreateTaskInputConsumption(ctx context.Context, arg CreateTaskInputConsumptionParams) (Gr33ncoreTaskInputConsumption, error) {
	row := q.db.QueryRow(ctx, createTaskInputConsumption,
		arg.FarmID,
		arg.TaskID,
		arg.InputBatchID,
		arg.Quantity,
		arg.UnitID,
		arg.Notes,
		arg.RecordedBy,
		arg.CostTransactionID,
	)
	var i Gr33ncoreTaskInputConsumption
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TaskID,
		&i.InputBatchID,
		&i.Quantity,
		&i.UnitID,
		&i.Notes,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.CostTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskInputConsumption = `-- name: DeleteTaskInputConsumption :exec
DELETE FROM gr33ncore.task_input_consumptions WHERE id = $1
`

func (q *Queries) DeleteTaskInputConsumption(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTaskInputConsumption, id)
	return err
}

const getTaskInputConsumptionByID = `-- name: GetTaskInputConsumptionByID :one
SELECT id, farm_id, task_id, input_batch_id, quantity, unit_id, notes, recorded_at, recorded_by, cost_transaction_id, created_at, updated_at FROM gr33ncore.task_input_consumptions
WHERE id = $1
`

func (q *Queries) GetTaskInputConsumptionByID(ctx context.Context, id int64) (Gr33ncoreTaskInputConsumption, error) {
	row := q.db.QueryRow(ctx, getTaskInputConsumptionByID, id)
	var i Gr33ncoreTaskInputConsumption
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TaskID,
		&i.InputBatchID,
		&i.Quantity,
		&i.UnitID,
		&i.Notes,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.CostTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskInputConsumptionsByTask = `-- name: ListTaskInputConsumptionsByTask :many

SELECT id, farm_id, task_id, input_batch_id, quantity, unit_id, notes, recorded_at, recorded_by, cost_transaction_id, created_at, updated_at FROM gr33ncore.task_input_consumptions
WHERE task_id = $1
ORDER BY recorded_at DESC, id DESC
`

// Phase 20.7 WS3 — task_input_consumptions CRUD. The handler wraps
// each Create in the autologger so the paired batch-decrement +
// cost_transactions row write happen atomically; Delete calls the
// compensating-refund path so the ledger stays append-only.
func (q *Queries) ListTaskInputConsumptionsByTask(ctx context.Context, taskID int64) ([]Gr33ncoreTaskInputConsumption, error) {
	rows, err := q.db.Query(ctx, listTaskInputConsumptionsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreTaskInputConsumption{}
	for rows.Next() {
		var i Gr33ncoreTaskInputConsumption
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.TaskID,
			&i.InputBatchID,
			&i.Quantity,
			&i.UnitID,
			&i.Notes,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.CostTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskInputConsumptionCostTx = `-- name: UpdateTaskInputConsumptionCostTx :exec
UPDATE gr33ncore.task_input_consumptions
SET cost_transaction_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTaskInputConsumptionCostTxParams struct {
	ID                int64  `db:"id" json:"id"`
	CostTransactionID *int64 `db:"cost_transaction_id" json:"cost_transaction_id"`
}

// The autologger may write the cost_transactions row after the
// consumption row exists (so the idempotency key can reference the
// consumption id). This backfills the link.
func (q *Queries) UpdateTaskInputConsumptionCostTx(ctx context.Context, arg UpdateTaskInputConsumptionCostTxParams) error {
	_, err := q.db.Exec(ctx, updateTaskInputConsumptionCostTx, arg.ID, arg.CostTransactionID)
	return err
}
