// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"gr33n-api/internal/platform/commontypes"
)

const createTask = `-- name: CreateTask :one

INSERT INTO gr33ncore.tasks (
    farm_id, zone_id, title, description, task_type, status, priority,
    assigned_to_user_id, due_date, estimated_duration_minutes,
    created_by_user_id, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW())
RETURNING id, farm_id, zone_id, title, description, task_type, status, priority, assigned_to_user_id, due_date, estimated_duration_minutes, actual_start_time, actual_end_time, related_module_schema, related_table_name, related_record_id, created_by_user_id, created_at, updated_at, updated_by_user_id, deleted_at
`

type CreateTaskParams struct {
	FarmID                   int64                      `db:"farm_id" json:"farm_id"`
	ZoneID                   *int64                     `db:"zone_id" json:"zone_id"`
	Title                    string                     `db:"title" json:"title"`
	Description              *string                    `db:"description" json:"description"`
	TaskType                 *string                    `db:"task_type" json:"task_type"`
	Status                   commontypes.TaskStatusEnum `db:"status" json:"status"`
	Priority                 *int32                     `db:"priority" json:"priority"`
	AssignedToUserID         pgtype.UUID                `db:"assigned_to_user_id" json:"assigned_to_user_id"`
	DueDate                  pgtype.Date                `db:"due_date" json:"due_date"`
	EstimatedDurationMinutes *int32                     `db:"estimated_duration_minutes" json:"estimated_duration_minutes"`
	CreatedByUserID          pgtype.UUID                `db:"created_by_user_id" json:"created_by_user_id"`
}

// ============================================================
// Queries: gr33ncore.tasks
// ============================================================
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Gr33ncoreTask, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.FarmID,
		arg.ZoneID,
		arg.Title,
		arg.Description,
		arg.TaskType,
		arg.Status,
		arg.Priority,
		arg.AssignedToUserID,
		arg.DueDate,
		arg.EstimatedDurationMinutes,
		arg.CreatedByUserID,
	)
	var i Gr33ncoreTask
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Title,
		&i.Description,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.AssignedToUserID,
		&i.DueDate,
		&i.EstimatedDurationMinutes,
		&i.ActualStartTime,
		&i.ActualEndTime,
		&i.RelatedModuleSchema,
		&i.RelatedTableName,
		&i.RelatedRecordID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, farm_id, zone_id, title, description, task_type, status, priority, assigned_to_user_id, due_date, estimated_duration_minutes, actual_start_time, actual_end_time, related_module_schema, related_table_name, related_record_id, created_by_user_id, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.tasks
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTaskByID(ctx context.Context, id int64) (Gr33ncoreTask, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Gr33ncoreTask
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Title,
		&i.Description,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.AssignedToUserID,
		&i.DueDate,
		&i.EstimatedDurationMinutes,
		&i.ActualStartTime,
		&i.ActualEndTime,
		&i.RelatedModuleSchema,
		&i.RelatedTableName,
		&i.RelatedRecordID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many
SELECT id, farm_id, zone_id, title, description, task_type, status, priority, assigned_to_user_id, due_date, estimated_duration_minutes, actual_start_time, actual_end_time, related_module_schema, related_table_name, related_record_id, created_by_user_id, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.tasks
WHERE assigned_to_user_id = $1 AND farm_id = $2 AND deleted_at IS NULL
ORDER BY due_date ASC NULLS LAST
`

type ListTasksByAssigneeParams struct {
	AssignedToUserID pgtype.UUID `db:"assigned_to_user_id" json:"assigned_to_user_id"`
	FarmID           int64       `db:"farm_id" json:"farm_id"`
}

func (q *Queries) ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]Gr33ncoreTask, error) {
	rows, err := q.db.Query(ctx, listTasksByAssignee, arg.AssignedToUserID, arg.FarmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreTask{}
	for rows.Next() {
		var i Gr33ncoreTask
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ZoneID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.AssignedToUserID,
			&i.DueDate,
			&i.EstimatedDurationMinutes,
			&i.ActualStartTime,
			&i.ActualEndTime,
			&i.RelatedModuleSchema,
			&i.RelatedTableName,
			&i.RelatedRecordID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByFarm = `-- name: ListTasksByFarm :many
SELECT id, farm_id, zone_id, title, description, task_type, status, priority, assigned_to_user_id, due_date, estimated_duration_minutes, actual_start_time, actual_end_time, related_module_schema, related_table_name, related_record_id, created_by_user_id, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.tasks
WHERE farm_id = $1 AND deleted_at IS NULL
ORDER BY due_date ASC NULLS LAST, priority DESC
`

func (q *Queries) ListTasksByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreTask, error) {
	rows, err := q.db.Query(ctx, listTasksByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreTask{}
	for rows.Next() {
		var i Gr33ncoreTask
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ZoneID,
			&i.Title,
			&i.Description,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.AssignedToUserID,
			&i.DueDate,
			&i.EstimatedDurationMinutes,
			&i.ActualStartTime,
			&i.ActualEndTime,
			&i.RelatedModuleSchema,
			&i.RelatedTableName,
			&i.RelatedRecordID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE gr33ncore.tasks
SET deleted_at = NOW(), updated_at = NOW(), updated_by_user_id = $2
WHERE id = $1
`

type SoftDeleteTaskParams struct {
	ID              int64       `db:"id" json:"id"`
	UpdatedByUserID pgtype.UUID `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.Exec(ctx, softDeleteTask, arg.ID, arg.UpdatedByUserID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE gr33ncore.tasks
SET status = $2, updated_by_user_id = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, farm_id, zone_id, title, description, task_type, status, priority, assigned_to_user_id, due_date, estimated_duration_minutes, actual_start_time, actual_end_time, related_module_schema, related_table_name, related_record_id, created_by_user_id, created_at, updated_at, updated_by_user_id, deleted_at
`

type UpdateTaskStatusParams struct {
	ID              int64                      `db:"id" json:"id"`
	Status          commontypes.TaskStatusEnum `db:"status" json:"status"`
	UpdatedByUserID pgtype.UUID                `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Gr33ncoreTask, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status, arg.UpdatedByUserID)
	var i Gr33ncoreTask
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ZoneID,
		&i.Title,
		&i.Description,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.AssignedToUserID,
		&i.DueDate,
		&i.EstimatedDurationMinutes,
		&i.ActualStartTime,
		&i.ActualEndTime,
		&i.RelatedModuleSchema,
		&i.RelatedTableName,
		&i.RelatedRecordID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}
