// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_activity_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUserActivityLog = `-- name: InsertUserActivityLog :exec

INSERT INTO gr33ncore.user_activity_log (
    user_id,
    farm_id,
    action_type,
    target_module_schema,
    target_table_name,
    target_record_id,
    target_record_description,
    user_agent,
    status,
    failure_reason,
    details
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    COALESCE($11::jsonb, '{}'::jsonb)
)
`

type InsertUserActivityLogParams struct {
	UserID                  pgtype.UUID                 `db:"user_id" json:"user_id"`
	FarmID                  *int64                      `db:"farm_id" json:"farm_id"`
	ActionType              Gr33ncoreUserActionTypeEnum `db:"action_type" json:"action_type"`
	TargetModuleSchema      *string                     `db:"target_module_schema" json:"target_module_schema"`
	TargetTableName         *string                     `db:"target_table_name" json:"target_table_name"`
	TargetRecordID          *string                     `db:"target_record_id" json:"target_record_id"`
	TargetRecordDescription *string                     `db:"target_record_description" json:"target_record_description"`
	UserAgent               *string                     `db:"user_agent" json:"user_agent"`
	Status                  *string                     `db:"status" json:"status"`
	FailureReason           *string                     `db:"failure_reason" json:"failure_reason"`
	Details                 []byte                      `db:"details" json:"details"`
}

// ============================================================
// Queries: gr33ncore.user_activity_log (compliance / audit trail)
// ============================================================
func (q *Queries) InsertUserActivityLog(ctx context.Context, arg InsertUserActivityLogParams) error {
	_, err := q.db.Exec(ctx, insertUserActivityLog,
		arg.UserID,
		arg.FarmID,
		arg.ActionType,
		arg.TargetModuleSchema,
		arg.TargetTableName,
		arg.TargetRecordID,
		arg.TargetRecordDescription,
		arg.UserAgent,
		arg.Status,
		arg.FailureReason,
		arg.Details,
	)
	return err
}

const listUserActivityLogByFarm = `-- name: ListUserActivityLogByFarm :many
SELECT
    id,
    user_id,
    farm_id,
    activity_time,
    action_type,
    target_module_schema,
    target_table_name,
    target_record_id,
    target_record_description,
    ip_address,
    user_agent,
    session_id,
    status,
    failure_reason,
    details,
    created_at
FROM gr33ncore.user_activity_log
WHERE farm_id = $1
ORDER BY activity_time DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListUserActivityLogByFarmParams struct {
	FarmID *int64 `db:"farm_id" json:"farm_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListUserActivityLogByFarm(ctx context.Context, arg ListUserActivityLogByFarmParams) ([]Gr33ncoreUserActivityLog, error) {
	rows, err := q.db.Query(ctx, listUserActivityLogByFarm, arg.FarmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreUserActivityLog{}
	for rows.Next() {
		var i Gr33ncoreUserActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FarmID,
			&i.ActivityTime,
			&i.ActionType,
			&i.TargetModuleSchema,
			&i.TargetTableName,
			&i.TargetRecordID,
			&i.TargetRecordDescription,
			&i.IpAddress,
			&i.UserAgent,
			&i.SessionID,
			&i.Status,
			&i.FailureReason,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActivityLogForOrganization = `-- name: ListUserActivityLogForOrganization :many
SELECT
    id,
    user_id,
    farm_id,
    activity_time,
    action_type,
    target_module_schema,
    target_table_name,
    target_record_id,
    target_record_description,
    ip_address,
    user_agent,
    session_id,
    status,
    failure_reason,
    details,
    created_at
FROM gr33ncore.user_activity_log
WHERE
    farm_id IN (
        SELECT f.id FROM gr33ncore.farms f
        WHERE f.organization_id = $1 AND f.deleted_at IS NULL
    )
    OR (
        (farm_id IS NULL OR farm_id = 0)
        AND (
            (details->>'organization_id')::bigint = $1
            OR (
                target_table_name = 'organizations'
                AND target_record_id = ($1::bigint)::text
            )
            OR (
                target_table_name = 'organization_memberships'
                AND target_record_id LIKE (($1::bigint)::text || ':%')
            )
        )
    )
ORDER BY activity_time DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListUserActivityLogForOrganizationParams struct {
	OrganizationID *int64 `db:"organization_id" json:"organization_id"`
	Limit          int32  `db:"limit" json:"limit"`
	Offset         int32  `db:"offset" json:"offset"`
}

// Org-wide audit: farms in the org plus org-only rows (NULL farm_id, details.organization_id, org membership targets).
func (q *Queries) ListUserActivityLogForOrganization(ctx context.Context, arg ListUserActivityLogForOrganizationParams) ([]Gr33ncoreUserActivityLog, error) {
	rows, err := q.db.Query(ctx, listUserActivityLogForOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreUserActivityLog{}
	for rows.Next() {
		var i Gr33ncoreUserActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FarmID,
			&i.ActivityTime,
			&i.ActionType,
			&i.TargetModuleSchema,
			&i.TargetTableName,
			&i.TargetRecordID,
			&i.TargetRecordDescription,
			&i.IpAddress,
			&i.UserAgent,
			&i.SessionID,
			&i.Status,
			&i.FailureReason,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
