// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zones.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createZone = `-- name: CreateZone :one

INSERT INTO gr33ncore.zones (
    farm_id, parent_zone_id, name, description, zone_type,
    area_sqm, meta_data, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, farm_id, parent_zone_id, name, description, zone_type, area_sqm, boundary_gis, meta_data, created_at, updated_at, updated_by_user_id, deleted_at
`

type CreateZoneParams struct {
	FarmID       int64          `db:"farm_id" json:"farm_id"`
	ParentZoneID *int64         `db:"parent_zone_id" json:"parent_zone_id"`
	Name         string         `db:"name" json:"name"`
	Description  *string        `db:"description" json:"description"`
	ZoneType     *string        `db:"zone_type" json:"zone_type"`
	AreaSqm      pgtype.Numeric `db:"area_sqm" json:"area_sqm"`
	MetaData     []byte         `db:"meta_data" json:"meta_data"`
}

// ============================================================
// Queries: gr33ncore.zones
// ============================================================
func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Gr33ncoreZone, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.FarmID,
		arg.ParentZoneID,
		arg.Name,
		arg.Description,
		arg.ZoneType,
		arg.AreaSqm,
		arg.MetaData,
	)
	var i Gr33ncoreZone
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ParentZoneID,
		&i.Name,
		&i.Description,
		&i.ZoneType,
		&i.AreaSqm,
		&i.BoundaryGis,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const getZoneByID = `-- name: GetZoneByID :one
SELECT id, farm_id, parent_zone_id, name, description, zone_type, area_sqm, boundary_gis, meta_data, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.zones
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetZoneByID(ctx context.Context, id int64) (Gr33ncoreZone, error) {
	row := q.db.QueryRow(ctx, getZoneByID, id)
	var i Gr33ncoreZone
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ParentZoneID,
		&i.Name,
		&i.Description,
		&i.ZoneType,
		&i.AreaSqm,
		&i.BoundaryGis,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}

const listZonesByFarm = `-- name: ListZonesByFarm :many
SELECT id, farm_id, parent_zone_id, name, description, zone_type, area_sqm, boundary_gis, meta_data, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.zones
WHERE farm_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListZonesByFarm(ctx context.Context, farmID int64) ([]Gr33ncoreZone, error) {
	rows, err := q.db.Query(ctx, listZonesByFarm, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreZone{}
	for rows.Next() {
		var i Gr33ncoreZone
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ParentZoneID,
			&i.Name,
			&i.Description,
			&i.ZoneType,
			&i.AreaSqm,
			&i.BoundaryGis,
			&i.MetaData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesByParent = `-- name: ListZonesByParent :many
SELECT id, farm_id, parent_zone_id, name, description, zone_type, area_sqm, boundary_gis, meta_data, created_at, updated_at, updated_by_user_id, deleted_at FROM gr33ncore.zones
WHERE parent_zone_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListZonesByParent(ctx context.Context, parentZoneID *int64) ([]Gr33ncoreZone, error) {
	rows, err := q.db.Query(ctx, listZonesByParent, parentZoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gr33ncoreZone{}
	for rows.Next() {
		var i Gr33ncoreZone
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.ParentZoneID,
			&i.Name,
			&i.Description,
			&i.ZoneType,
			&i.AreaSqm,
			&i.BoundaryGis,
			&i.MetaData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteZone = `-- name: SoftDeleteZone :exec
UPDATE gr33ncore.zones
SET deleted_at = NOW(), updated_at = NOW(), updated_by_user_id = $2
WHERE id = $1
`

type SoftDeleteZoneParams struct {
	ID              int64       `db:"id" json:"id"`
	UpdatedByUserID pgtype.UUID `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) SoftDeleteZone(ctx context.Context, arg SoftDeleteZoneParams) error {
	_, err := q.db.Exec(ctx, softDeleteZone, arg.ID, arg.UpdatedByUserID)
	return err
}

const updateZone = `-- name: UpdateZone :one
UPDATE gr33ncore.zones
SET name = $2, description = $3, zone_type = $4, area_sqm = $5,
    meta_data = $6, updated_by_user_id = $7, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, farm_id, parent_zone_id, name, description, zone_type, area_sqm, boundary_gis, meta_data, created_at, updated_at, updated_by_user_id, deleted_at
`

type UpdateZoneParams struct {
	ID              int64          `db:"id" json:"id"`
	Name            string         `db:"name" json:"name"`
	Description     *string        `db:"description" json:"description"`
	ZoneType        *string        `db:"zone_type" json:"zone_type"`
	AreaSqm         pgtype.Numeric `db:"area_sqm" json:"area_sqm"`
	MetaData        []byte         `db:"meta_data" json:"meta_data"`
	UpdatedByUserID pgtype.UUID    `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (Gr33ncoreZone, error) {
	row := q.db.QueryRow(ctx, updateZone,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ZoneType,
		arg.AreaSqm,
		arg.MetaData,
		arg.UpdatedByUserID,
	)
	var i Gr33ncoreZone
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.ParentZoneID,
		&i.Name,
		&i.Description,
		&i.ZoneType,
		&i.AreaSqm,
		&i.BoundaryGis,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.DeletedAt,
	)
	return i, err
}
